### ISSUE TITLE
Bug: DireWolf20 pack crashed when typing into the LaserIO tag filter search box

### ISSUE THREAD

**Issue by michaelingrum** [Direwolf20-MC/LaserIO#10]
Crash Report attached: [crash-2022-05-23_20.37.19-client.txt](https://github.com/Direwolf20-MC/LaserIO/files/8759383/crash-2022-05-23_20.37.19-client.txt)

I searched in the text box without any item in the lookup slot, but I don't think that was the issue. 
I was not able to recreate the issue.

**Comment by Direwolf20-MC** [comment]
Fixed in v1.0 of the mod
