### ISSUE TITLE
The term "RF" is used in a Patchouli text to mean "FE"

### ISSUE THREAD

**Issue by James103** [Direwolf20-MC/LaserIO#100]
### LaserIO version

4c88f0ddbbab7c4d20e6f657386cfb76ba84b1ea

### Minecraft Version

1.18.2

### Forge Version

40.1.x

### Modpack & Version

None

### Do you have optifine installed?

No

### Describe the issue

The Energy Cards page of the LaserIO manual has some typos on its last page.

### Steps to reproduce

1. Create a new instance, Minecraft 1.18.2, Forge 40.1.20 or later.
2. Install LaserIO and Patchouli.
3. Create a new world with cheats enabled.
4. Open the Patchouli book for LaserIO and select "Energy Cards".
5. Go to the last page.
6. Notice the following line (errors in bold): "Technical Note: The Forge Energy system supports energy storage up to **MAXINT** which is approximately 2.14 billion **RF**. If you are using a mod like Draconic Evolution or Mekanism, their storage cells can store greater than this amount by 'hacking' how Forge Energy works. As a result, this % indicator will not work on storage cells greater than 2.14 billion **RF**. Sorry! :)"

This line should be replaced with the following (changes in bold): "Technical Note: The Forge Energy system supports energy storage up to **MAX_INT** which is approximately 2.14 billion **FE**. If you are using a mod like Draconic Evolution or Mekanism, their storage cells can store greater than this amount by 'hacking' how Forge Energy works. As a result, this % indicator will not work on storage cells greater than 2.14 billion **FE**. Sorry! :)"

### Expected behaviour

No such errors

**Comment by Direwolf20-MC** [comment]
Resolved - thanks for the catch :)
