### ISSUE TITLE
Feature Request: ComputerCraft Bundled Cable Integration

### ISSUE THREAD

**Issue by treecubed** [Direwolf20-MC/LaserIO#101]
### Describe the feature you'd like to have added

It would be really cool if the laser nodes could act as a bundled cable for ComputerCraft. I feel like it would be a natural fit for the 16 channel setup of the redstone cards.

**Comment by Direwolf20-MC** [comment]
Sounds complex to implement though - I'll add it to my 'nice to have' list ;)
