### ISSUE TITLE
Feature Request: A way to somewhat label a network setup

### ISSUE THREAD

**Issue by ralmeida** [Direwolf20-MC/LaserIO#104]
### Describe the feature you'd like to have added

I've had this issue and I've seen others with this as well;

Once you have a node network setup and move on going back to it requires you to click thru the cards and re-remember the system you've setup. 

Instead maybe a way that on a "network" you could have a tab (seen at the top of the node UI when you open any node on the network) for Labels or "Map" where it allows you to manage by node type what labels you've given each channel.

```
|______________|      |________________|
|-- Node Tab --|      |-- Labels Tab --|               <--------- Add a tab to the Node UI
|---------------------------------------------|
| **Items** |--| Fluids |--| Power |--| Redstsone |  <--------- When the Labels tab is selected show a selection of types,
|---------------------------------------------|                 default Items selected
|- [ 0 - White ] - [ Enter Label Text ]                <--------- Add Labels to the Channel by Type
|- [ 1 - ....
```

One issue I see with this feature (outside of the overall implementation time of UI coding) is when you combine networks using the same channels, and maybe different labels. For this I would suggest some kind of warning prompt like "adding this node to the network may override Labels, connect again to override" (this can be done the same way the out of range notice is given currently)

This way the selected node and its network becomes the main source of labels for the combined network and the same channels are overridden by it. 

Overall I think it can lead to making the mod more friendly to users, and more useable in complex automations without the need to re-review all the cards and settings across a node network to make changes.

**Comment by Direwolf20-MC** [comment]
Sounds fun, but a LOT of effort to code :). Sorry gonna pass for now.

**Comment by macks2008** [comment]
yeah maybe start smaller like just being able to label individual cards without having to rename in an anvil... And then the cards could be where the labeling data is saved if you ever want to implement this feature or something like it
