### ISSUE TITLE
Allowed to backport?

### ISSUE THREAD

**Issue by Gurkysword12** [Direwolf20-MC/LaserIO#105]
### Describe the feature you'd like to have added

Am I allowed to backport the mod laserio to Minecraft version 1.16.5

**Comment by jollycar** [comment]
It's MIT licence: https://github.com/Direwolf20-MC/LaserIO/blob/main/LICENSE.txt

**Comment by Direwolf20-MC** [comment]
Yes - its MIT licensed so you can do whatever you like :)
