### ISSUE TITLE
Right click to cycle backwards, does not work for redstone control

### ISSUE THREAD

**Issue by NekoSpirits** [Direwolf20-MC/LaserIO#106]
### LaserIO version

1.3.3

### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Do you have optifine installed?

No

### Describe the issue

You cannot right click the redstone icon in cards to cycle backwards through the options, like other buttons.

### Steps to reproduce

1. Open MC...
2. Open card inside node
3. Right click redstone control
4. See that right clicking does not cycle backwards

### Expected behaviour

Cycle backwards through redstone behaviors on right click

### Screenshots

![javaw_UjhPMPLsKf](https://user-images.githubusercontent.com/20034469/180656450-5168ab08-3c54-4104-8123-a3a997e912eb.gif)

**Comment by Direwolf20-MC** [comment]
Ya, not all buttons have that right click to go back thing, its a bunch of extra logic so I only added it in a few places.
