### ISSUE TITLE
Node laser not showing for Entangled block

### ISSUE THREAD

**Issue by jollycar** [Direwolf20-MC/LaserIO#107]
### LaserIO version

1.3.2

### Minecraft Version

1.18.2

### Forge Version

40.1.67

### Modpack & Version

Custom modpack (based on DW20)

### Do you have optifine installed?

I have other rendering based mods installed: rubidium

### Describe the issue

When using a node on an entangled block (inventory) and inserting an extract item card (e.g. to the up direction). the rendering of laser is not shown. the node is actually working just fine. it is pure visually.

### Steps to reproduce

1. entangle an invertory (i used a storage drawer) (from the mod: entangled)
2. place node next to entangled block
3. use extract item card

### Expected behaviour

laser should show visually

### Screenshots

https://imgur.com/a/rLOdMuH

**Comment by jollycar** [comment]
Additional info: only occurs if the inventory block is in a different dimension

**Comment by Direwolf20-MC** [comment]
Is the inventory block in the different dimension chunk loaded?

This may not be something thats easy to fix, so I'll just mark as closed now, as a cross mod interaction issue - especially since its just visual :)
