### ISSUE TITLE
Node voiding productive bees honeycombs in centrifuge

### ISSUE THREAD

**Issue by crippie** [Direwolf20-MC/LaserIO#108]
### LaserIO version

1.3.1

### Minecraft Version

1.18.2

### Modpack & Version

All The Mods 7 0.4.22

### Do you have optifine installed?

No

### Describe the issue

When setting a node to insert honeycombs into the productive bees centrifuge. If the comb it is trying to insert does not match the comb type in the centrifuge it starts to void the combs while trying to insert. 

### Steps to reproduce

1.) Set up Productive Bees centrifuge with power.
2.) Set up a chest to hold various types of honeycomb. 
3.) set up a laser node to extract from chest and insert into the centrifuge.
4.) Either wait until one comb type runs out in chest, or change the order around so that a new comb type is in the front to be extracted. It will seemingly extract the comb but cannot insert it into the centrifuge due to a different comb type being there. And then the comb gets voided. 

### Expected behaviour

The laser node should not extract any combs not in the centrifuge until the centrifuge is empty. Do not void the combs.

**Comment by Direwolf20-MC** [comment]
Can you test with the latest LaserIO - i fixed a similar bug in 1.3.3

**Comment by crippie** [comment]
Newest modpack version came out today, just installed, it has laserIO 1.3.3. Tried as hard as I could to replicate the issue and could not. Looks like it is resolved. Bravo good sir, keep up the phenomenal work.
