### ISSUE TITLE
Ability to read/write redstone levels (0-15) and compare against set parameters and ability to enable/disable card if met

### ISSUE THREAD

**Issue by batty80** [Direwolf20-MC/LaserIO#112]
### Describe the feature you'd like to have added

Looking at the availability
to read redstone level (0-15) and act upon the reading according to parameters ie lower than, equal to, above, strong, weak
to output redstone levels (0-15), strong or weak redstone output
Enable or disable a card in a laser node if a redstone input parameter is met.

**Comment by Direwolf20-MC** [comment]
I don't want my redstone control to be that powerful - use another redstone mod to handle this like super circuit maker :)
