### ISSUE TITLE
LaserIO blocks interaction with wrench items

### ISSUE THREAD

**Issue by Vapaman** [Direwolf20-MC/LaserIO#113]
### Describe the feature you'd like to have added

LaserIOs blocks should interract with wrenches with the tag forge:wrenches. Basic functionality would be the ability to pick up the blocks with shift right click.

### Additional information

Rotation functionality isn't needed

**Comment by Direwolf20-MC** [comment]
Planned at some point, but the way wrenches work currently this isn't possible.
