### ISSUE TITLE
Detector Card

### ISSUE THREAD

**Issue by Crokoking** [Direwolf20-MC/LaserIO#114]
### Describe the feature you'd like to have added

The current redstone card is quite limited. I'd like a detector card that you can use to detect items in the connected inventory (configured via filter) and produce a redstone signal to a channel similar to a comparator. 
This way you could detect that an output chest is full and prevent inserting more intems into the input. That would be very useful for things like in-world crafting where the input isn't limited by an inventory and you can end up with tons of item entities if the ouptut fills up.

**Comment by Direwolf20-MC** [comment]
This is a planned feature - it'll be a new mode on Item/Fluid/Energy cards.
