### ISSUE TITLE
Node card slots are inventories

### ISSUE THREAD

**Issue by IamStig** [Direwolf20-MC/LaserIO#115]
### LaserIO version

1.3.3

### Minecraft Version

1.18.2

### Forge Version

40.1.67

### Modpack & Version

Direwolf20 1.18.2

### Do you have optifine installed?

No

### Describe the issue

Not calling as a bug - Nodes have 6 inventories, by design or not

### Steps to reproduce

1 Connect any side of a node to a pipe or conduit and a chest, bottom also interacts with hopper
2 Put card into that side of the node
3 Card is pulled out.

### Expected behaviour

Don't know... but was not expecting that 

### Additional information

It isn't a huge problem, likely edge case type thing. I was modifying a build, moving 2 blocks up and inserting a node was the simple solution, and I tried to put a node with a counter over a hopper only to discover the node went missing, figured out where and why but curios to find out if this was by design, accidental or the only way Dire knows to get the mod to work, I have no idea if there is another solution but I suspect there is, I mean I have never, that I can recall, connected pipes etc to an IF or thermal machine and extracted the upgrades. 

Just curious.

**Comment by Direwolf20-MC** [comment]
It’s intended :). I was hoping it would lead to some cool things (like automatically changing out cards) but usually it leads to problems with hoppers instead. Might remove it in 1.19
