### ISSUE TITLE
Interaction with Refined Storage Exporter

### ISSUE THREAD

**Issue by OneBangDash** [Direwolf20-MC/LaserIO#116]
**LaserIO version**
1.3.2

**Minecraft Version**
1.18.2

**Forge Version**
40.1.67

**Modpack & Version**
Direwolf20 1.18 1.8.0

**Do you have optifine installed?**
No

**Describe the issue**
LaserIO cannot extract fluids from Refined Storage exporters. 

**Steps to reproduce**
RF Exporter settings: Fluid mode, export lava
LaserIO node settings: Fluid extractor card, extract mode

**Expected behaviour**
the spawner does not look active even though it is active

**Screenshots**
No response

**Log files**
**No response**

**Additional information**
No response

**Comment by Direwolf20-MC** [comment]
Refined Storage exporters are not tanks, and therefore cannot be interacted with in this way. Use the refine storage fluid interface if you want to extract from it.
