### ISSUE TITLE
[Bug] LasernodeBE.java triggering "Redstone Input Changed - Updating Network" Constantly

### ISSUE THREAD

**Issue by TheonlyTazz** [Direwolf20-MC/LaserIO#118]
### LaserIO version

laserio-1.4.1.jar

### Minecraft Version

1.18.2

### Forge Version

40.1.69

### Modpack & Version

Direwolf20 1.18 (v1.8.0-1.9.0)

### Do you have optifine installed?

No

### Describe the issue

Consolespam by Laserio

### Steps to reproduce

[FTB Issue Tracker](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1238)
Issue got reported on the FTB Modpack Issue tracker, stating that the console gets flooded with "Redstone input ihanged - updating network"

I havent found the exact location of the block that is causing it, but after looking at the source code of LaserIO its clear that it comes from LaserIO

### Expected behaviour

Don't spam Console

### Additional information
Check FTB Issue tracker (link above) for full report

**Comment by Direwolf20-MC** [comment]
I definitely left some debug code in the mod. I’ll remove it and release a hot fix today

**Comment by Direwolf20-MC** [comment]
Resolved by: https://github.com/Direwolf20-MC/LaserIO/commit/a1ba5b7e69614b7ef8dd0bd7b0fbf6ab052ee8e0

Will release v1.4.2 now.
