### ISSUE TITLE
Voiding items when interacting with Create's basin

### ISSUE THREAD

**Issue by FishOutOfH20** [Direwolf20-MC/LaserIO#121]
### LaserIO version

1.3.3

### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Modpack & Version

Encrypted 1.2

### Do you have optifine installed?

No

### Describe the issue

If you use a basic filter when inserting into a basin from Create, it will void 48 items at a time since the basin can only hold 16 at a time.

### Steps to reproduce

1. Use an item card to pull from an inventory (drawer in my case) with at least a full stack.
2. Use another item card to insert into the basin.  The basin's capacity is 16 for the recipe.
3. With just a basic filter on the inserting card, it will pull 64 from the drawer, insert 16 into the basin, and void the other 48.
4. With a counting filter set to 16 on the inserting card, it will function correctly, and leave 48 in the drawer.

### Expected behaviour

When using a basic filter, it should not void any excess items.  It should take what it requires and leave the rest.

**Comment by Direwolf20-MC** [comment]
I am able to duplicate this issue - and I know why its happening - however, I'm not sure if its because I'm doing something wrong, or create is. I need to investigate further and will update this as I find out.

**Comment by Direwolf20-MC** [comment]
So it turns out what create is doing is *not great* but I should also be checking for this kind of shenanigans :) So i added some extra checks in to prevent it. Current commit resolves this for extract mode but not stocking yet. That'll be a different kind of fix.
