### ISSUE TITLE
Fluid card exact mode didn't pull the exact amount

### ISSUE THREAD

**Issue by Overseer9** [Direwolf20-MC/LaserIO#122]
### LaserIO version

1.4.2

### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Do you have optifine installed?

No

### Describe the issue

Fluid card didn't pull an exact ammound of fluid while exact mode is on

### Steps to reproduce

1. Setup ore processing with industrial foregoing
2. Add processing 2 addon into wasing factory
3. Put 40 raw iron into washing factory
4. Fluid card with exact mode with 4 buckets extract amount and inserting into a buffer tank
5. Wait until washing factory produce more than 1 bucket
6. The fluid card extracted the fluid even tho its not 4 buckets yet

### Expected behaviour

The fluid card with exact mode only extract the exact amount of fluid

### Additional information

I also found a weird behavior with fluid card, 
with 1 bucket extract amount extracting ether gas from a tank, it can't insert into fermentation station. And it start extract and inserting after i changed the extract amount to 10mb

**Comment by Direwolf20-MC** [comment]
Did you have the card set to extract 1 bucket at a time or 4 buckets? Exact mode refers to the extract amount - not the filter amount.

**Comment by Overseer9** [comment]
It seems to be fixed on Industrial foregoing side

I updated to industrial foregoing 3.3.1.4 and i can't reproduce the bug anymore
