### ISSUE TITLE
Any plan for ae2 and rs connection support?

### ISSUE THREAD

**Issue by foxwhite25** [Direwolf20-MC/LaserIO#124]
### Describe the feature you'd like to have added

A network card that transfers ae2 and/or rs signals, like those me conduit from enderio. 

Maybe overclocker can increase the number of channels that a card can support, and it is always active if there is a connection, so you need a node overclocker to use other operations.

**Comment by Direwolf20-MC** [comment]
No at this time :)

**Comment by hgjensen** [comment]
Hi Dire
Is this still a hard no?
Would love "ME Card" and "Dense ME Card" for instance. Especially now that GregTech(ceU-modern) has hit 1.20 - making massive AE2 networks a virtual certainty.

**Comment by Direwolf20-MC** [comment]
No sorry :) not at this time.
