### ISSUE TITLE
Crash/World Corruption when inserting into laser node past full

### ISSUE THREAD

**Issue by Vilandas** [Direwolf20-MC/LaserIO#125]
### LaserIO version

1.4.2

### Minecraft Version

1.18

### Forge Version

40.1.69

### Modpack & Version

Direwolf20 - 1.18 (v1.9.1)

### Do you have optifine installed?

No

### Describe the issue

Crash/World Corruption after right clicking an item card into a laser when it's already full

### Steps to reproduce

Place a laser.
Fill a side fully with cards (e.g. North side with 9 item cards)
Continuing to insert by right clicking on a the side "voids" card, but I don't think it's exactly voiding it.
If a container (e.g. a chest) is placed next to the side with the 9+ cards, game crashes and world corrupts.
This also happens if the container is already there and you right click a "10th" item on a side.

### Expected behaviour

Laser should not accept extra cards.

**Comment by Direwolf20-MC** [comment]
Thank you for finding and reporting this :) it is resolved and will be part of v1.4.3
