### ISSUE TITLE
Counting filter doesn't remember Item ID when replacing existing item with drag/drop

### ISSUE THREAD

**Issue by Cammyk48** [Direwolf20-MC/LaserIO#127]
### LaserIO version

1.4.2

### Minecraft Version

1.18.2

### Forge Version

1.18.2-forge-40.1.69

### Modpack & Version

Direwolf20 1.18

### Do you have optifine installed?

No

### Describe the issue

Replacing Items in Counting filter with Drag/Drop updates the count, but not the item ID

### Steps to reproduce

Get Default Counting Filter and two items
Place # of items in slot 1 & 2
Close/Reopen the Counting Filter and try to replace with # 2 and a different item.
Close/Reopen the Counting Filter and you see that the # is correctly modified, but not the item.

### Expected behaviour

The interface should keep what is done when you update it. Including the Item ID

### Screenshots

Placement1 is what the filter is originally
Placement2 is what the filter is updated to, before closing the interface
Placement3 is what the filter remembers from the Placement2

![Placement1_8 17 27](https://user-images.githubusercontent.com/40872481/187477950-4f9d0013-ca38-45e6-badd-2b1fb98006f3.png)
![Placement2_8 17 40](https://user-images.githubusercontent.com/40872481/187477956-fb600702-a465-4ba4-bc19-0d4f5d738137.png)
![Placement3_8 17 45](https://user-images.githubusercontent.com/40872481/187477963-9ed54da0-f48f-49a7-88c1-2feaa3dec625.png)

### Log files

[debug.log](https://github.com/Direwolf20-MC/LaserIO/files/9454256/debug.log)
[Uploading latest.log…]()

**Comment by Direwolf20-MC** [comment]
Confirmed, I'll look into fixing this for 1.19 -- For now just remove the itemstack from the filter before adding a new one. 

Thank you for reporting it :)

**Comment by Direwolf20-MC** [comment]
Resolved. Thank you :)
