### ISSUE TITLE
Laser IO crashing server

### ISSUE THREAD

**Issue by MadSklzMatt** [Direwolf20-MC/LaserIO#130]
### LaserIO version

1.4.2

### Minecraft Version

1.18.2

### Modpack & Version

Direwolf20 1.18

### Do you have optifine installed?

No

### Describe the issue

Never found the main issue because the mod had to be removed sadly. Anytime we went into the chunk with it, the entire server would immediately crash.

### Steps to reproduce

Sorry dunno but i have a log

### Expected behaviour

energy to transfer from extreme reactors to charging station from mining gadgets. Worked for one user for a few days, second user crashes the server.

### Screenshots

![image](https://user-images.githubusercontent.com/112675843/188050907-3fb4002b-23c2-4d68-a529-052c6f6cb36d.png)
continues to line 445

### Log files

https://mcpaste.io/d08b2d776c906e52

### Additional information

Sorry I don't have more info. I used the lasers with upgrades for a few days, no issues. My friend started using them tonight and suddenly the whole server crashes whenever the chunk is loaded. We chose to remove the mod since the server only has daily backups and the last one was 13 hours ago. Thanks and hope there's a fix cause this mod is probably the best energy transfer in the pack.

**Comment by Direwolf20-MC** [comment]
I haven't seen any more reports of this bug and can't reproduce it, if you can find a way to make it happen again please let me know how :). Thank you!

**Comment by Direwolf20-MC** [comment]
Actually I did find this :) its now resolved, thank you
