### ISSUE TITLE
Crashes 1.19.2

### ISSUE THREAD

**Issue by wuggyfoot** [Direwolf20-MC/LaserIO#132]
### LaserIO version

1.5.0

### Minecraft Version

1.19.2

### Forge Version

43.1.15

### Do you have optifine installed?

No

### Describe the issue

Crashes on load with LaserIO installed

### Steps to reproduce

1. Install LaserIO
2. Launch game
3. Crash

### Expected behaviour

I expected the mod to load flawlessly with no problems

### Log files

https://paste.ee/p/A5FJW 

### Additional information

Cool mod I like it, works on 1.18.2

**Comment by Direwolf20-MC** [comment]
Install patchouli :)
