### ISSUE TITLE
Facades & dyeable laser nodes

### ISSUE THREAD

**Issue by Vapaman** [Direwolf20-MC/LaserIO#133]
### Describe the feature you'd like to have added

**Facades for laser nodes**

Would suggest something similiar to pneumaticcraft's camoflage system, with camoflage is applied with a tool. Could also go with modular routers way of putting a block in the nodes interface, which the node then camoflages into. The tool method is preferable if the camoflage also applies to the laser connectors as those do not have a GUI.

**Dyeable laser nodes**

Purely for cosmetic purposes, but could be really useful for color coding networks of nodes. The basic 16 colors would suffice.

### Additional information

Right now laser nodes and only fit a certain range of color palettes and building styles. With this laser nodes wouldn't clash as much with different building styles.

**Comment by Direwolf20-MC** [comment]
Planned Feature :)
