### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by Nicon4454** [Direwolf20-MC/LaserIO#134]
### Describe the feature you'd like to have added

Hello would it be possible to add a config file and add an option to increase the range of the connectors.
-or-
Add and upgrade to the connectors so that we could go more than 8 blocks away say like 16.

**Comment by koukimonster91** [comment]
i would like to suggest another setting for the config file and that would be the ability to adjust the max amout of items for the stock setting

**Comment by OceanRift** [comment]
We demand config file!!!!

**Comment by sheaksadi** [comment]
having a config file would be great

**Comment by Shybella** [comment]
No config? wack, pretty bad example to set for beginners

**Comment by Direwolf20-MC** [comment]
There are two suggestions for a config in here, neither of which I want to have as config options.  The max items is a technical limitation (sort of) and the range is a balance one ;).  I have plans to add longer range connectors at some point, but until someone can give me a GOOD reason for a config file, I don't see a need for one just yet :)

**Comment by sheaksadi** [comment]
I really liked draconic wireless power connectors they had one that conects to machines that has a low range and one relay that connects multiple connectors from far . So was thinking making the connector range being increasealbe would be great . Damm draconic evaluation was cool. And my favourite part was those laser power connectors

**Comment by Shybella** [comment]
> There are two suggestions for a config in here, neither of which I want to have as config options. The max items is a technical limitation (sort of) and the range is a balance one ;). I have plans to add longer range connectors at some point, but until someone can give me a GOOD reason for a config file, I don't see a need for one just yet :)

Config option to control tick rate of item transfer
Config option to change the amount transferred per tick
Config option to disable/unregister the item
Config option to blacklist other machines from insert/extract from


Plenty more, again, I expected better from you. No excuse other than laziness.

**Comment by MichaelHillcox** [comment]
Closing as a decision has been clearly stated. PRs are always welcome.

**Comment by Direwolf20-MC** [comment]
> > There are two suggestions for a config in here, neither of which I want to have as config options. The max items is a technical limitation (sort of) and the range is a balance one ;). I have plans to add longer range connectors at some point, but until someone can give me a GOOD reason for a config file, I don't see a need for one just yet :)
> 
> Config option to control tick rate of item transfer. Config option to change the amount transferred per tick. Config option to disable/unregister the item from the game. Config option to blacklist other machines interacting with laserIOs insert/extract.
> 
> Plenty more, again, I expected better from you. No excuse other than laziness. This is basic stuff, modded MC is spaghettified when lots of mods are install, your mod isn't magic and magically works with every other mod bug/crash free.. Having these options allows for faster and more efficient debugging and problem solving.

You’re welcome to not use it. Or just submit a PR. Write the config code yourself. Anything else would be pure laziness on your part.
