### ISSUE TITLE
Stock 'Multiples' Mode

### ISSUE THREAD

**Issue by qn-T** [Direwolf20-MC/LaserIO#135]
### Describe the feature you'd like to have added

It would be nice to have the option when using Stock mode with a Counting Filter to insert multiples of the filter quantity.

A counting filter with all ore pieces at quantity 4 would stock either 4, 8, 16 ... 64 in the attached inventory.

The mode could be an extension of the Exact toggle.

### Additional information

Idea influenced by automating the Flux Compactor in Ex Machinis - making sure the compactor's inventory can never be filled with <4 pieces of 9 different ores and be unable to process new ore pieces.

**Comment by Renari** [comment]
I'm fairly certain this can be accomplished by setting your extraction card to extract 4 at a time and turning on exact mode.

**Comment by Direwolf20-MC** [comment]
Exact mode should be able to accomplish this :)
