### ISSUE TITLE
game crash -Ticking block entity

### ISSUE THREAD

**Issue by drakellion** [Direwolf20-MC/LaserIO#137]
### LaserIO version

1.4.3

### Minecraft Version

1.18.2

### Forge Version

40.1.79

### Modpack & Version

atm2sky 1.0.7

### Do you have optifine installed?

No

### Describe the issue

The game cashed after I linked a node that had an energy card on input. 

### Steps to reproduce

Can't open the game , it crash on loading the level .

### Expected behaviour

not crash 

### Log files

[](url)
[crash-2022-09-24_14.14.38-server.txt](https://github.com/Direwolf20-MC/LaserIO/files/9638622/crash-2022-09-24_14.14.38-server.txt)

**Comment by Direwolf20-MC** [comment]
Resolved by: https://github.com/Direwolf20-MC/LaserIO/commit/e52c572e05fed56815d2cc88ea0bdb8664bb39bd
