### ISSUE TITLE
Stocking mode with non-returnable sources spews items into world

### ISSUE THREAD

**Issue by HappyCerberus** [Direwolf20-MC/LaserIO#139]
### LaserIO version

1.4.3

### Minecraft Version

1.18.2

### Forge Version

40.1.79

### Modpack & Version

ATM7: To the Sky 1.0.8

### Do you have optifine installed?

No

### Describe the issue

Using laser IO with a barrel leads to items being thrown into the world

### Steps to reproduce

Extract item card from a barrel.

Stocking item card at the destination with a counting filter.

In a situation when the extract attempts to extract and the stocking destination is already at capacity, the item will be thrown into the world, since it can't be returned to the barrel.

### Expected behaviour

What should probably happen instead is that the item extract card should be able to hold one of each item as a buffer.

**Comment by Direwolf20-MC** [comment]
There is absolutely no code in this mode that spawns items in the world - I can't imagine how that would happen. Can you describe exactly your setup (maybe with screenshots)? Because I can't duplicate it based on your explanation.

**Comment by HappyCerberus** [comment]
OK, I will try to produce a minimal example.

But, just to clarify, without looking at the code, what I expect is happening that laserIO takes item out of inventory, the destination is already at limit, so it tries to put the item back into the inventory, which throws the item into the world (since the barrels are one-way only).

**Comment by Direwolf20-MC** [comment]
Right, but theres no native code that says 'Drop items in world' - you have to go out of your way to put code like that into your logic, and i'm 99% sure I don't have ANYTHING like that in LaserIO. 

When you say barrel, do you mean the vanilla minecraft barrel, or some mod's?

**Comment by HappyCerberus** [comment]
Ok, nvm. Thanks for the mod and for the videos.
