### ISSUE TITLE
Will LaserIO support Addon Mods/Custom Cards?

### ISSUE THREAD

**Issue by MaPePeR** [Direwolf20-MC/LaserIO#14]
Is it planned to have the possibility for other mods to create custom LaserIO Cards? E.g. Mekanism Gas Transfer? Or Refined Storage link cards? A Card to transfer Create's rotation-power through lasers? Ok, that last one might be just stupid. 😂 

I'm in no way affiliated with Mekanism, RS or Create, so I can't say if they would actually like to have or do something like that, just a curious question, if that is something you did consider when writing the mod.

**Comment by Direwolf20-MC** [comment]
Maybe some day :). Not right now though, too much left to do first.
