### ISSUE TITLE
Add Mekanism Gas Card

### ISSUE THREAD

**Issue by bruno-borges-2001** [Direwolf20-MC/LaserIO#140]
### Describe the feature you'd like to have added

I think a compatibility with Mekanism's Gases would be great (like with Gas Cards and filter support)

**Comment by andrewsf** [comment]
Make sure to [search for previous issues](https://github.com/Direwolf20-MC/LaserIO/issues?q=mekanism).

**Comment by jfelipearaujo** [comment]
Hi guys, I'm working on this request 🎉.

Currently I've figure out how to extract and insert gases.

But I need more time to test more features like stock and filters.

When the Gas Card become stable, I'll open a PR to @Direwolf20-MC check what I did and if is good to go :)

**Comment by jfelipearaujo** [comment]
@MichaelHillcox and @Direwolf20-MC , I've added you both to my repository. There you will find the [feature/add-mekanism-gas-card](https://github.com/jfelipearaujo/LaserIO/tree/feature/add-mekanism-gas-card) branch with a 98% functional version.

There are some points that I wasn't able to figure out yet, they are:
- File: EventTooltip.java
-> The tags collector from Mekanism is trick
- File: FilterTagScreen.java
-> Rendering a "bucket" or a "tank" is trick
- File: BaseCardCache.java
-> FilterMod and FilterTag wasn't implemented yet
- File: GetStackKey.java
-> Collecting NBT tags from Gas is trick

**Comment by MichaelHillcox** [comment]
Hay, thanks for working on this issue. Privately inviting us to your project is a little non-standard for this kinda thing. Once you have something ready, open up a Pull Request and we'll review

**Comment by Direwolf20-MC** [comment]
Planned Feature :)
