### ISSUE TITLE
Ender card upgrade / Wireless Card Upgrade

### ISSUE THREAD

**Issue by AceDrago** [Direwolf20-MC/LaserIO#141]
### Describe the feature you'd like to have added

Hello there, I a suggestion that might work if you have a card that can wirelessly connect to a chest or tank and or energy after upgrading the cards to the ender version by combining with a ender chest and a ender pearl for the upgrade, and to link them you shift right click on the chest or the tank that you want to link to so you can use more of the laser node slots and are not wasting the node and can maximize it to its fullest use.

**Comment by Direwolf20-MC** [comment]
Planned Feature :)
