### ISSUE TITLE
Create Mod Chute Extracts Item Cards from Node

### ISSUE THREAD

**Issue by Peekofwar** [Direwolf20-MC/LaserIO#144]
### LaserIO version

1.4.3

### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Do you have optifine installed?

No

### Describe the issue

When a node is placed above a Create Mod chute, the chute will extract the item cards out of the bottom side of the LaserIO node.

### Steps to reproduce

1. Place LaserIO node above Create Mod chute
2. Insert an item card on the bottom side of the node
3. Observe it vanish from the node

### Expected behaviour

The cards should not be extracted from the node and instead it should attempt to insert items into the chute.

### Screenshots

![2022-10-14_19 29 07](https://user-images.githubusercontent.com/10189526/195957440-d6b81b53-3759-46bd-8c1a-b5282edb39ef.png)

### Additional information

Create Mod v0.5.0.e

**Comment by Direwolf20-MC** [comment]
The nodes are inventories, like a chest, and therefore can be extracted from with a hopper. Intended functionality :) sorry! This has tripped up a few others in the past, and I might remove it. For now I want to keep it though

**Comment by Peekofwar** [comment]
> The nodes are inventories, like a chest, and therefore can be extracted from with a hopper. Intended functionality :) sorry! This has tripped up a few others in the past, and I might remove it. For now I want to keep it though

What if you added either a setting in the node to override this, or some kind of card or special node that can be crafted?

**Comment by Direwolf20-MC** [comment]
I will consider this as a feature request. You're not wrong, a lot of people have been confused by this:).  Remember you can use sneaky mode to insert into other sides of a block as a work around for now.
