### ISSUE TITLE
Feature Request: Redstone NOT gate option

### ISSUE THREAD

**Issue by SamusAranon** [Direwolf20-MC/LaserIO#145]
### Describe the feature you'd like to have added

On the Redstone cards could you program a NOT gate option, to automatically invert when signal should run or should not run. For example your episode today you were attempting to get a spawner to stop running when your blood alter was full and you had to add a lot of extra steps, with a NOT gate option on the redstone card you could have clicked the one button to flip the redstone output to what you needed.

**Comment by Direwolf20-MC** [comment]
I consider this one scope creep - I want to let redstone mods handle this functionality for now.
