### ISSUE TITLE
Feature request: Area card

### ISSUE THREAD

**Issue by PianoHallvard** [Direwolf20-MC/LaserIO#146]
### Describe the feature you'd like to have added

Area card to scan an area for certain traits/features, sort of like the pneumaticraft area tool with the drones and whatnots. 

So for example, if there are more than x mobs in area a*b*c, emit redstone signal on channel y

**Comment by Direwolf20-MC** [comment]
Not part of the scope of this mod, sorry :).

**Comment by PianoHallvard** [comment]
Ah, that's a shame. Would've been a really cool feature. I might just write an addon mod that does exactly this XD
