### ISSUE TITLE
Backbtn in Filter doesn't save "Match NBT"-State

### ISSUE THREAD

**Issue by katsutosh** [Direwolf20-MC/LaserIO#147]
### LaserIO version

1.5.0

### Minecraft Version

1.19.2

### Forge Version

43.1.43

### Modpack & Version

ATM 8 - 0.1.4

### Do you have optifine installed?

No

### Describe the issue

The Back Btn in the top left doesn't save the "Match NBT"-Btn State

### Steps to reproduce

- Open LaserIO Node
- Open Settings from item card
- Put "Basic Filter"-Card in
- Change "Match NBT"-Btn state to active
- click Return (left top arrow)

if i use ESC to close the Filterwindow it's works as expected

### Expected behaviour

save "Match NBT"-Btn State (active/disabled) on back btn

### Screenshots

Close With Back Btn: bugged
https://i.imgur.com/xr2lt5a.gif

Close with ESC: works as expected
https://i.imgur.com/gCfCGjX.gif

**Comment by Direwolf20-MC** [comment]
Resolved - thank you :)
