### ISSUE TITLE
Dimlet items not recognized by the Tag Filter

### ISSUE THREAD

**Issue by Demolishun** [Direwolf20-MC/LaserIO#148]
### LaserIO version

1.4.2

### Minecraft Version

1.18.2

### Forge Version

40.1.69

### Modpack & Version

Direwolf20 1.18.2 

### Do you have optifine installed?

No

### Describe the issue

Dimlets not recognized by the Tag Filter

### Steps to reproduce

Put dimlet in Tag Filter slot.  No dimlet tag names are listed.  On the contrary if I put a gold nugget in I get a bunch of options.  I was hoping to filter all the dimlets using the tag filter.

### Expected behaviour

I list of dimlet tags I can save in the tag filter.

**Comment by Direwolf20-MC** [comment]
I'm guessing that dimlets don't have tags like that - sorry :)
