### ISSUE TITLE
Crash/Bug related to interaction with Alchemistry

### ISSUE THREAD

**Issue by Mordu05** [Direwolf20-MC/LaserIO#149]
### LaserIO version

1.4.3

### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Modpack & Version

ATM7 Sky 1.1.3

### Do you have optifine installed?

No

### Describe the issue

Crash caused by Ticking Block Entity

### Steps to reproduce

1. Open ATM7 file in version 1.1.2
2. Set Up LaserIO automation into Alchemistry Chemical Dissolver.
3. Update modpack to version 1.1.3
4. Experience Crash. (I  believe)

### Expected behaviour

Successfully enter game

### Log files

[crash-2022-10-23_06.18.01-server.txt](https://github.com/Direwolf20-MC/LaserIO/files/9894051/crash-2022-10-23_06.18.01-server.txt)
[crash-2022-10-29_09.23.16-server.txt](https://github.com/Direwolf20-MC/LaserIO/files/9894052/crash-2022-10-29_09.23.16-server.txt)
[latest.log](https://github.com/Direwolf20-MC/LaserIO/files/9894056/latest.log)
[debug.log](https://github.com/Direwolf20-MC/LaserIO/files/9894057/debug.log)

### Additional information

This is the second time I have had this type of crash in this world, and my steps to reproduce are based on what was similar between the two times. Both nodes that were corrupted were set up to automate Alchemistry Dissolvers, and both crashes only occurred upon updating the pack, although updating to different versions. Up until updating the version of the pack, the nodes operated as expected.

I've included crash logs from both crashes, but I only have the Log Files as they exist after the most recent crash.

**Comment by Peeebo** [comment]
I can confirm this. After Update to 1.1.3  tried to insert a counting filter into the Alchemistry Chemical Dissolver. Server Crash.

**Comment by Mordu05** [comment]
Update: I believe it is related to some change that happened in version 1.1.2/1.1.3 of the modpack. I downgraded to modpack version 1.1.2 and it was still crashing, but when I downgraded to 1.1.1, I was able to get into the world and remove the problem Node. From there, I was able to upgrade back to version 1.1.3 and load the world fine.

**Comment by nperrygo** [comment]
Same issue here.  Node with an extract card worked fine in 1.1.1, but crashes on load in 1.1.2 and 1.1.3.   Downgrade to 1.1.1 and loads fine.  Remove node, upgrade back to 1.1.3 and can load into world.  If I re-place the node, as soon as I insert an item card game freezes then crashes out to launcher.

**Comment by Direwolf20-MC** [comment]
This *sounds* like a bug in Alchemistry, because I know that LaserIO didn't update between those two versions of the modpack. 

That said, let me see if i can protect against the crash. I'll investigate :)

**Comment by Direwolf20-MC** [comment]
Everything seems ok in my test world, aside from their items having a broken particle texture, which shouldn't cause a crash (and isn't for me). 

Is there anything else you can tell me about this setup?
![image](https://user-images.githubusercontent.com/39863894/199550391-02a13db2-fd21-4802-ac38-82be13f1b42b.png)

**Comment by Direwolf20-MC** [comment]
I'm going to conclude that the bug is on Alchemistry's side, based on the crash report, alchemistry is crashing when LaserIO trys to insert - i can't reproduce it to confirm though. If you can report this over on the Alchemistry git, that would probably be cool :). 

![image](https://user-images.githubusercontent.com/39863894/199551693-2021fd9c-59b2-4914-b199-f47780f92a3e.png)

**Comment by nperrygo** [comment]
After some more testing, I'd agree.  I tried switching to Pipez item pipes and it crashed in a similar way.  Thanks for looking into it!
