### ISSUE TITLE
Minecraft bottles

### ISSUE THREAD

**Issue by whinesley** [Direwolf20-MC/LaserIO#150]
### LaserIO version

1.4.3

### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Do you have optifine installed?

No

### Describe the issue

Nice Mod thanks.  The filtering does not differentiate between empty or full bottles.  minecraft:glass_bottle and minecraft:honey_bottle

### Steps to reproduce

1. setup two chests separated by a node.
2. put at least one empty bottle and one honey filled bottle in the a chest (chest A)
3. in the node facing chest A, insert a item card and set it to extract.
4. using a Tag filter, try to set it to an empty (minecraft:glass_bottle) or a honey filled (minecraft:honey_bottle) bottle.   They are not identified correctly.
FYI: I even tried typing "minecraft:glass_bottle" into the text field, but the ":" gets dropped in result displayed in the bottom window.

### Expected behaviour

the filter should be able to differentiate between empty and fill bottles

**Comment by Direwolf20-MC** [comment]
Bottle's don't have tags apparently - use a basic or counting filter instead :)
