### ISSUE TITLE
Give each node networks a random color

### ISSUE THREAD

**Issue by bcmpinc** [Direwolf20-MC/LaserIO#151]
### Describe the feature you'd like to have added

"Why isn't this working?" (10 mins later) "Oh, I forgot to connect the nodes".

Does that sound familiar to you? A visual indication of which nodes are part of the same network, would help make this common mistake a lot easier to debug. If each node network has its own color, it's clear that they're not part of the same network. An added benefit is that Youtubers no longer have to tell what is part of the same network as viewers can easily see what nodes belong to the same network and which don't.

This feature could be implemented as follows:
Assign a random color (instead of the default red) to each node when its placed. Assuming you use a *union find* data structure to determine what nodes are part of the same network, let the nodes and lasers be rendered using the color of the node that was selected as root node.

If the color of a node (and hence its network) is made configurable, this would partially implement feature request #133.

**Comment by Direwolf20-MC** [comment]
Planned feature :)
