### ISSUE TITLE
LaserIO not working with Flux Point again - does not transfer energy but has proper connection

### ISSUE THREAD

**Issue by Manbeartooth** [Direwolf20-MC/LaserIO#152]
### LaserIO version

1.4.4

### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Modpack & Version

ATM7 to the Sky 1.1.4

### Do you have optifine installed?

No

### Describe the issue

Flux network shows connected to the node but no energy is transfered

### Steps to reproduce

1. Updated to the latest ATM7 to the sky 1.1.4
2. Load into game
3. check any node that is connected to a flux point node
4. no energy is passing through

It does look like it is connecting as the flux point has the extended section on it.

Workaround:
Plug the flux point into a power cable, such as Mekanism cable and then the laser IO starts to pass power through again.

### Expected behaviour

Node with energy module should connect directly to Flux point

### Screenshots

![Working_laserio](https://user-images.githubusercontent.com/49558102/200029077-a714e67d-5571-42ce-b3cb-e49d7b592008.jpg)
![NotWorking_laserio](https://user-images.githubusercontent.com/49558102/200029082-de2b133e-5a0c-497f-80f2-1d561d647bca.jpg)

**Comment by Direwolf20-MC** [comment]
That’s super weird because it should be the same code that’s handling both connection types. Let me test that

**Comment by Starway2** [comment]
I can confirm that. Just updated the pack and loaded the world. No energy is passing, even some nodes dosn't want to work with items too.

**Comment by Direwolf20-MC** [comment]
Found my mistake :) I'll release a fixed version shortly.
