### ISSUE TITLE
Fluid card exact mode extracts less if not sufficient available

### ISSUE THREAD

**Issue by Tatsu-Kishi** [Direwolf20-MC/LaserIO#153]
### LaserIO version

1.4.4

### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Modpack & Version

ATM7 - Sky

### Do you have optifine installed?

No

### Describe the issue

Fluid card in exact mode sometimes extracts partial amount, but only inserts if the specified amount can be inserted

### Steps to reproduce

1. Tinkers Construct Foundry Ore processing with various orse constantly getting smelted
2. Configure extracting card exact mode 810mb with 4 overclocking cards to work every tick (basin holds 810mB aka 9 ingots)
3. Setup (multiple) empty casting basins with fluid insert cards
4. Get not-fully-filled basins (ie. the aluminum basin bottom left in screenshot)

### Expected behaviour

Only get fully filled casting basins

### Screenshots

![image](https://user-images.githubusercontent.com/3016344/200409332-8d7d6bf0-f022-428b-a73d-f2fba2d99fee.png)

### Additional information

This seems to be related to the "primary output fluid" switching around at times when it's almost depleted - however with there still being enough fluid to fully fill the partially-filled basin. I have tested with stocking mode that non-primary liquids are accessible by laserIO as well.

**Comment by Tatsu-Kishi** [comment]
As a workaround I have additional basins in stocking mode (one for each metal) now that pick up any leftover fluids, but it is just a workaround and not a solution, since I'd prefer those 12 basins to be metal-independent to increase overall processing speed.

**Comment by Renari** [comment]
From my testing this seems to happen because an extraction does not guarantee the amount of fluid extracted will be also the amount input on the other side, this causes a single extraction to split output among multiple destinations. Another workaround for this is to put each basin on it's own fluid channel, this prevents it from splitting the output.

**Comment by Direwolf20-MC** [comment]
This mode just makes sure it can extract the correct total amount, not insert it into a single basin. I Think stocking mode is the proper solution here.
