### ISSUE TITLE
Shift+Click from card holder into a node sometimes causes two cards to go in at the same time

### ISSUE THREAD

**Issue by Dima-Kevanishvili** [Direwolf20-MC/LaserIO#154]
### LaserIO version

1.4.5

### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Modpack & Version

FTB StoneBlock 3 - 1.1.0

### Do you have optifine installed?

No

### Describe the issue

Shift+Click from card holder into a node sometimes causes two cards to go in at the same time

### Steps to reproduce

1. Get a card holder with multiple cards of the same type
2. Open the node GUI
3. Shift+Left Click a card in the card holder GUI
4. Notice that sometimes there's two cards in the node now.

### Expected behaviour

Only one card to be transferred to the node

### Screenshots

Vid of reproduction: https://imgur.com/a/asPHl0x

### Additional information

Running this on M1 Pro Macbook and using its trackpad to play, the issue might stem from here (I haven't done any testing on a windows machine or with a mouse)

**Comment by Direwolf20-MC** [comment]
I’m pretty sure there’s another mod in the pack causing this because other UIs are having it happen for me and this didn’t happen in other packs.
