### ISSUE TITLE
Exception in server tick loop when feeding energy from one LaserNode to another and link them

### ISSUE THREAD

**Issue by chrischtea** [Direwolf20-MC/LaserIO#155]
### LaserIO version

1.4.3

### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Modpack & Version

AllTheMods7 1.18.2 0.4.34

### Do you have optifine installed?

No

### Describe the issue

server crash and corruption when feeding energy from one LaserNode to another and link them

### Steps to reproduce

1. place two nodes next to each other (touching on north and south side), do not link them
2. extract energy via energy card in northern node from west from Flux Plug (or point, can never tell the difference. the share energy with adjacent blocks-flux thingy)
3. in northern nodes' south side add energy card in insert mode
4. in southern nodes' north side add energy card in extract mode
5. link nodes with linking tool
6. crash

### Expected behaviour

dont do nothin, just dont crash

### Screenshots

![2022-11-09_21 57 01](https://user-images.githubusercontent.com/23280306/200953861-4328caf0-3262-4dd3-84dc-bdba87c2f542.png)

### Log files

[crash-2022-11-09_21.57.05-server.txt](https://github.com/Direwolf20-MC/LaserIO/files/9975571/crash-2022-11-09_21.57.05-server.txt)

### Additional information

Happend while showing someone, who never used LaserIO before. Was just about to explain linking to them when the server crashed. Had to surgically remove one node 'offline' to start the server back up again, as otherwise the nodes were chunk-loaded and crashed the server directly after start up.

**Comment by Direwolf20-MC** [comment]
Resolved in the latest version :). Update the mod.

**Comment by qchronod** [comment]
@Direwolf20-MC Don't know if this might help in the future, but I had a crash with the fixed 1.4.5 version.

ATM7-To the sky 1.1.5
Forge 40.1.84
LaserIO 1.4.5
[crash-2022-11-17_18.15.57-server.txt](https://github.com/Direwolf20-MC/LaserIO/files/10036650/crash-2022-11-17_18.15.57-server.txt)
Not sure if it's LaserIO or Powah that's causing the crash

Replacing all the Powah cables with mekanism stopped the server from crashing when updated to 1.4.5.

**Comment by Direwolf20-MC** [comment]
I’ll investigate thank you :). It might be powah or me not sure yet.

**Comment by Direwolf20-MC** [comment]
Closing for now, please let me know if this continues to happen in 1.20.x
