### ISSUE TITLE
Add less than option for sensor cards with counting filter.

### ISSUE THREAD

**Issue by Renari** [Direwolf20-MC/LaserIO#156]
### Describe the feature you'd like to have added

Currently a sensor card will emit a redstone signal if the requested item/fluid is greater than the amount in the counting card.

Equals support is implemented by using exact mode, this means we have support for:

amount >
amount =

However we do not have support for outputting a signal when the amount is lower than a specific value.

My suggestion is to change the exact mode button: 
![image](https://user-images.githubusercontent.com/1839179/203653161-a53351f6-8c6e-4e74-b936-442fa45311ae.png)
To instead be a greater than, less than or equal to button.

Greater than would mimic the old functionality with exact mode off, equal to mimics the old functionality with exact mode on, and less than would be new functionality.

**Comment by ratkinsonuk** [comment]
+1 for this. Having a nightmare trying to use LaserIO to put just one block of stone at a time into a Blood Magic altar.

**Comment by TronWoWGamer** [comment]
Would also like a way to filter count on zero items.  Like send a redstone signal if the inventory is empty so I can initiate an extract of items from another inventory (drawer into chest that get processed).  For now I will have to find another detection system.

**Comment by Direwolf20-MC** [comment]
Added to wishlist of features.
