### ISSUE TITLE
issue with the cards

### ISSUE THREAD

**Issue by fenixchi** [Direwolf20-MC/LaserIO#157]
### LaserIO version

1.4.5

### Minecraft Version

1.18.2

### Modpack & Version

ftb stoneblock 3 

### Do you have optifine installed?

No

### Describe the issue

using the /kill @e command removes all cards out of the node

### Steps to reproduce

1. use laserio as normal 
2. use /kill all @e 
3. all cards removed from all nodes

### Expected behaviour

cards should not be removed

**Comment by Direwolf20-MC** [comment]
I can’t imagine how that would happen since my nodes are not entities. Block entities yes but that command doesn’t affect those. 

I’ll see if I can replicate but can’t imagine why that would happen.

**Comment by fenixchi** [comment]
its the cards that are removed the nodes stay there


so are the cards classes as an entity?

**Comment by Joprebond** [comment]
Thiis happened when i was streaming and the kill command made the cards disappear from my card holder

**Comment by Direwolf20-MC** [comment]
Nope. There are no custom entities in the mod at all as I recall. The cards inside the node are like any other item inside something like a chest. 

Are you sure you’re checking the right side of the node.

**Comment by fenixchi** [comment]
its in the card holder the were removed from
im relying it from a streamer  as it happened on his stream

**Comment by Joprebond** [comment]
best i can say is you can come watch on my stream and we can try to reproduce it

**Comment by Direwolf20-MC** [comment]
Ohhh it was the card holder not the nodes. That makes more sense. I’ve had a few reports of card holders randomly losing their data

**Comment by Direwolf20-MC** [comment]
I'm going to assume this is related to the old cardholder bug, please let me know if it happens again on a more recent version or if you can reproduce it.

**Comment by Zamion101** [comment]
I can comfirm the data of the card holder gets wiped because of unknown bug. I'm currently playing Techopolis 2 in Skyblock preset and sometimes my Card Holder get wiped without interaction. It sits in my inventory and does not move from the original position (hotbar last slot) and still it got wiped multiple times.
