### ISSUE TITLE
Copy/Paste card settings

### ISSUE THREAD

**Issue by linuxgarou** [Direwolf20-MC/LaserIO#158]
### Describe the feature you'd like to have added

It would be helpful to have an option to copy the settings of a card that you are looking at to the clipboard, so that you can then paste them to a different card (similar to how XNet allows you to copy/paste connector settings).

**Comment by CyberFoxar** [comment]
As per #46 I would like the functionality to actually allow bulk adding/copying filters and overclocks, not just bulk modifying.

**Comment by CinnamonShaey** [comment]
upvote

**Comment by Direwolf20-MC** [comment]
Sounds interesting, and definitely something I'd like to add if I can get time to do it. I'll add it to my list of 'nice to have' features :).
