### ISSUE TITLE
Bug: Deleted Item Cards when updating mod version

### ISSUE THREAD

**Issue by jtrain564** [Direwolf20-MC/LaserIO#16]
Warning:  Updating the mod from 1.0.1 to 1.0.2 deleted all my item cards and broke all my node connections.

**Comment by Direwolf20-MC** [comment]
I’ll test this in my let’s play world asap

**Comment by Aloneatwar13** [comment]
Updated from the beta version to 1.0.2 and same thing happened, all cards and filters gone, and all newly placed nodes do not show a laser connection when linked with wrench.

**Comment by Direwolf20-MC** [comment]
Investigating...I pulled the mod off curse in the meantime

**Comment by Direwolf20-MC** [comment]
Found the bug - yup this is totally on me. Unfortunately you'll lose the cards for good, and the nodes will be broken until you break/replace them. Sorry! Working on a new version now it'll be out soon. I'd roll back your world if you can ;)

**Comment by Direwolf20-MC** [comment]
Resolved by: f10f4a0e28686f9cfbcdeaa23649c3175dea5716
