### ISSUE TITLE
Match Ore Dictionary option for item cards

### ISSUE THREAD

**Issue by TheVekter** [Direwolf20-MC/LaserIO#160]
### Describe the feature you'd like to have added

It'd be nice to have an option for having the item cards to match ore dictionary on items, so we don't need to use multiple cards to sort through different versions of ores.

**Comment by MichaelHillcox** [comment]
I think you can use tags here. Ore Dictionary's don't actually exist any more.

**Comment by Direwolf20-MC** [comment]
Mikey is correct :) use tags
