### ISSUE TITLE
Filter items by durability % like Ender IO conduits could.

### ISSUE THREAD

**Issue by doritobob269** [Direwolf20-MC/LaserIO#161]
### Describe the feature you'd like to have added

I'd like to be able to transport items when they hit below 50% durability (or any other percentage of durability remaining).
This could be either a setting in one of the existing filters or a whole new filter specific to durability. Ender IO used to have a durability filter and I know Laser IO's origins stem closely from Ender IO.

My specific example being I would like to transport the occultism miner foliot out of the dimensional mineshaft when it gets below 50% durability. Then placed in the cyclic anvil to be repaired and replaced in the dimensional mineshaft when fully repaired.

As of right now, I can filter matching metadata. The miner foliot has 1600 durability, so I have durabilities 804, 803, 802, 801, 800 set to be extracted, but if the miner foliot ever drops below 800 durability before being extracted, it will be used up in the dimensional mineshaft.

**Comment by Direwolf20-MC** [comment]
The challenge with this request is durability USED to be stored as Metadata, but now that its stored as NBT its possible that mods will use a different value for their durability. It will be inconsistent and unreliable, unless I made something more complex (Like Integrated Dynamics) and I think thats beyond the scope of what I'd like to do with this mod :). 

Integrated Dynamics could probably accomplish what you're after though!
