### ISSUE TITLE
Mode to insert whole recipes

### ISSUE THREAD

**Issue by yourb3stnightmare** [Direwolf20-MC/LaserIO#163]
### Describe the feature you'd like to have added

It would be cool if there was a mode to insert whole recipes, and only one recipe at a time. This is useful for things like the Powah laser crafter (whatever it's called) where it accept any combination of items. It could use the filter and counting filter to define recipes (the regular filter would insert and whole multiple of that recipe, while the counting filter would insert only one).

Currently you can kinda do this with the counting filter, but if there are multiple recipes in the chest, it tries to dump parts of both at the same time.

**Comment by Direwolf20-MC** [comment]
I think thats a little beyond the scope of what LaserIO wants to do, sorry! :)
