### ISSUE TITLE
Fluid Cards Ignore Overclockers

### ISSUE THREAD

**Issue by TronWoWGamer** [Direwolf20-MC/LaserIO#164]
### LaserIO version

1.4.5

### Minecraft Version

1.18.2

### Modpack & Version

Stoneblock 3

### Do you have optifine installed?

No

### Describe the issue

Fluid Card does not use the overclocker when extracting from mekanism tanks or industrial foregoing tanks and won't insert into blood magic altar

### Steps to reproduce

1. Run Stoneblock 3 (single player)
2. place nodes on Blood Magic Altar and either Elite Mekanism Fluid Tank or Industrial Foregoing Black Hole Tank
3. Add fluid cards to both altar and tanks for extract and insert
4. Add overclocker cards to extract (up to 4)
5. set amount to 8000 and ticks to 1
6. Also, using redstone cards to control the direction of extract/insert and this works just fine
7. -----
It still only extracts 20 mb a second

### Expected behaviour

I expected an entire bucket of blood to transfer from altar to tank and back

**Comment by IONayrus** [comment]
Blood Magic throttles In and Output of the Altar. This sounds very much related to this feature and not like a bug from LaserIO...

**Comment by Direwolf20-MC** [comment]
> Blood Magic throttles In and Output of the Altar. This sounds very much related to this feature and not like a bug from LaserIO.
> 
> Edit: In fact 20mb per second is the default speed the Altar operates when no accelartion/dislocation runes are added

This is correct :)
