### ISSUE TITLE
Use super call for getRemainingItems

### ISSUE THREAD

**Issue by Soaryn** [Direwolf20-MC/LaserIO#166]
https://github.com/Direwolf20-MC/LaserIO/blob/a6d9c4ee677e216b8e1d1514b088f463b6ea8199/src/main/java/com/direwolf20/laserio/datagen/customrecipes/CardClearRecipe.java#L25

Basically you should be adding your stuff to the existing recipe remainder items. This way any items used in the recipe (should it ever happen) provide a complete item list of what should remain in the grid. 

Easy test case is to add a water bucket in one of your recipes. The remainder should then be a bucket + what ever upgrades you had in your card

**Comment by Direwolf20-MC** [comment]
Resolved by: https://github.com/Direwolf20-MC/LaserIO/commit/32f8929d4a70e480f58a428276fc326c8c4f4249
