### ISSUE TITLE
Unexpected behaviour - exporting with counting filter and with ignore NBT

### ISSUE THREAD

**Issue by dm8mydog** [Direwolf20-MC/LaserIO#169]
### LaserIO version

1.4.5

### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Modpack & Version

ATM7TTS v1.2.2

### Do you have optifine installed?

No

### Describe the issue

Unexpected behaviour - exporting with counting filter.

### Steps to reproduce

This one's a bit quirky.

Use case: 
Using a LaserIO node to export from an inventory with large variety of same type of items with NBT data.
In this case: combs from Productive bees ( productivebees:configurable_honeycombs )
I wanted the node to leave some behind of each type, this works fine when the counting filter is specifically set to account for each individual comb within the filter ( but with **MATCH NBT**). 

What am I doing:
However there's a large number of different bee honeycombs from this mod so It ends up saturating all filter slots eventually for a full one side of a node (actually 8 slots out of 9); since I needed the space on that node, I switched it to a simpler catch-all extract with ignore NBT with just one item card with a counting filter. Now the Counting filter 'counts' all items of type productivebees:configurable_honeycombs all in one pool of item count, instead of the individual (different NBT) types.

I expected the counting filter to apply to each individual 'item' (same tag, different NBT) when ignore NBT is activated. It does not.

Sorry, long winded :P

### Expected behaviour

Expected the counting filter to apply to each individual item (same tag, different NBT) when ignore NBT is activated. It does not.

**Comment by IONayrus** [comment]
> ### Steps to reproduce
> I expected the counting filter to apply to each individual 'item' (same tag, different NBT) when ignore NBT is activated. It does not.
> 
> ### Expected behaviour
> Expected the counting filter to apply to each individual item (same tag, different NBT) when ignore NBT is activated. It does not.

I don't quite understand. If you have Items which are only different by NBT, why should it treat them as individual Items if you set Ignore NBT?

**Comment by dm8mydog** [comment]
Because that's the whole reason to even use a Counting filter, otherwise I'd just use a regular filter instead?
I believe that a counting filter in this scenario should leave one* (or N*-whatever the count is) of each type of NBT-flavoured item back in the source inventory.

**Comment by dm8mydog** [comment]
It's annoying that I myself agree with you on one hand...

...yet on the other hand I have to try and think what different ability the counting filter would bring compared to a non counting filter (in this scenario) and find myself second-guessing myself; and thinking that yeah, it should apply the count on the inventory once each per NBT-variable item... 

I dunno which half of me is right! :P

**Comment by Direwolf20-MC** [comment]
I see what you're saying, but unfortunately thats just not how it works. It would likely be tricky to implement that in a way that makes sense for most use cases :). Sorry!
