### ISSUE TITLE
ME pattern provider to Laser Node?

### ISSUE THREAD

**Issue by kisgergelyp** [Direwolf20-MC/LaserIO#173]
### Describe the feature you'd like to have added

I want to use the ME pattern provider on a Laser Node. The Pattern Access Terminal recognises that I put it on top of a Laser Node, but it won't pass the item to it or the Laser Node won't take the items. I know Laser Nodes don't have an internal inventory, but the items have a destination. Would it be possible to include this feature?

**Comment by Direwolf20-MC** [comment]
I'm sorry, i think your best bet here would be to put a chest between your pattern provider and the laser node, and have the node pull out of the chest.
