### ISSUE TITLE
Add Redstone enabled laser connectors

### ISSUE THREAD

**Issue by Dragnier** [Direwolf20-MC/LaserIO#176]
### Describe the feature you'd like to have added

Make redstone enabled laser connectors capable of redstone channel choice that act as repeaters on that channel. This way, you could bind a multi-logic tiled setup to one node via multiple connectors and have the redstone signal repeated instantly on all of those connectors.

Would have worked perfectly for Dire's latest episode of ATM 8 where he started Pneumaticraft and was setting up the fluid compressors; he could have used one node and two connectors instead of three nodes.

**Comment by Direwolf20-MC** [comment]
I purposefully don't want laser connectors doing much :). Sorry!
