### ISSUE TITLE
Feature Request: Sneak right click node opens opposite side

### ISSUE THREAD

**Issue by neldridge** [Direwolf20-MC/LaserIO#178]
### Describe the feature you'd like to have added

Currently, if you want to open a side that's facing a block you can't access, the easiest way is to click the opposite and then tab over manually.

It might be useful to shift right-click the node, and instead of it opening the side you're facing- it opens the opposite. 

Example:
![image](https://user-images.githubusercontent.com/720437/234894398-57440fd4-efcd-41c6-9f44-3008a833f519.png)
The create side is North but it's easiest to click from South and then click the North tab. Shift+right-click on south should open the North tab.

**Comment by Direwolf20-MC** [comment]
Adding this to my list of 'nice to have' features :) . I'll try to get these kinds of things added in 1.20
