### ISSUE TITLE
Cant connect to infuse port mekanism machines

### ISSUE THREAD

**Issue by URosenornL** [Direwolf20-MC/LaserIO#179]
### LaserIO version

1.5.2

### Minecraft Version

1.19.2

### Modpack & Version

ATM 8

### Do you have optifine installed?

No

### Describe the issue

Connect to infuse port mekanism machines

### Steps to reproduce

Try to connect Laserio to infuse port on mekanism machines like the metallurgic infuser

### Expected behaviour

See a laser between the laser node and mekanism machine

**Comment by Direwolf20-MC** [comment]
Aren't those gases? LaserIO Can't handle gas's atm
