### ISSUE TITLE
Placers, Breakers, Collectors, and Droppers

### ISSUE THREAD

**Issue by GGearZZ** [Direwolf20-MC/LaserIO#181]
### Describe the feature you'd like to have added

Good Day!
Would it be possible to add features to interact with items in the world?
Such as cards that handle block placement, block breaking, pickup/absorption, and a precision dropper?

Thank you for your time and the incredible mod! 😄

**Comment by Direwolf20-MC** [comment]
Sorry I feel like this is out of scope for this mods purpose :). Lots of other mods have this functionality.
