### ISSUE TITLE
Gui Render

### ISSUE THREAD

**Issue by Rumaruka** [Direwolf20-MC/LaserIO#183]
### LaserIO version

1.6.1

### Minecraft Version

1.20.1

### Forge Version

47.0.3

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

Render bug

### Steps to reproduce

1)Open hud tags filter
2)...
3)Profit

### Expected behaviour

correct hud render

### Screenshots

![image](https://github.com/Direwolf20-MC/LaserIO/assets/8148679/771c3257-d673-42da-856d-d1a2c1649fca)

**Comment by Direwolf20-MC** [comment]
Thanks I’ll investigate ! :)
