### ISSUE TITLE
LaserIO Render /w Oculus/Rubidium

### ISSUE THREAD

**Issue by quikenb** [Direwolf20-MC/LaserIO#184]
### LaserIO version

1.6.1

### Minecraft Version

1.20.1

### Forge Version

47.0.19

### Modpack & Version

ATM9 V0.0.15

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

LaserIO transfer lasers have immense green glow

### Steps to reproduce

Use complimentary shaders and the issue is right there.

### Expected behaviour

No green glow. As well as the laser lines showing

### Screenshots

![image](https://github.com/Direwolf20-MC/LaserIO/assets/18548078/6cdd16d4-2623-4940-ad65-662c28b78fa0)

### Log files

https://pastebin.com/8D40ugJ9

**Comment by Direwolf20-MC** [comment]
I have to guess that it’s related to that shaders mod but I honestly know very little about how those work :). If the shaders team has some insight into what I can do differently I’d be open to hearing! :)

**Comment by quikenb** [comment]
I have opened one on their end too - > https://github.com/ComplementaryDevelopment/ComplementaryReimagined/issues/33

Love your work btw <3

**Comment by EminGT** [comment]
The issue should be reported to the Oculus Shader Mod, not Complementary Shaders

**Comment by Direwolf20-MC** [comment]
I'm gonna close this for now, if it turns out my mod is doing something wrong and the Shader Mod folks need me to fix it, please re-open :). Thanks!

**Comment by LupusTheFallen** [comment]
There is a similar issue with Mining gadgets, but it can be resolved by changing RP support to basic or turning off/lowering bloom. I'm not sure about the technicalities of these mods, but if the LaserIO's connections could be implemented the same way Mining Gadgets' is, that could solve this issue.
