### ISSUE TITLE
Energy Card Sensor not working.

### ISSUE THREAD

**Issue by HeavyDeception** [Direwolf20-MC/LaserIO#187]
### LaserIO version

1.5.2

### Minecraft Version

1.19.2

### Forge Version

43.12.0

### Modpack & Version

All The Mods 8

### Do you have optifine installed?

No

### Describe the issue

Energy Card Sensor mod is not creating a Redstone signal when Cell hits 50%.

### Steps to reproduce

1. Place Redstone Flux Cell charge to 50%
2. Place Laser Node and add Energy Card on Sensor mod
3. Set energy limit to 50.

### Expected behaviour

A redstone signal is sent o the channel set.

### Screenshots

https://puu.sh/JKCbv/dd7d8b16ea.png

https://puu.sh/JKCbw/dce5e4bd65.png

https://puu.sh/JKCbA/011f3e1e24.png

### Additional information

I have tried to add a filter to it as the book says that it needs one, but I am not allowed to do so.

https://puu.sh/JKCav/3b9cb59e82.png

**Comment by Direwolf20-MC** [comment]
I tested this in 1.19.2 in a test world with just Thermal and LaserIO. This was an Thermal Expansion Cube right?

It looks like it worked to me, did you allow interaction with the side of the cube that the laser node with a sensor card is in? Is there a yellow laser drawn between the node and the cube as shown here?

![image](https://github.com/Direwolf20-MC/LaserIO/assets/39863894/046ca774-6a8e-4454-9990-b0d6636a9cd5)

**Comment by HeavyDeception** [comment]
This is indeed user error I even asked on the discord for help sending images, but it looks like it was all on me. I apologize.
I don't know what I did wrong yet, but it's working today.

**Comment by HeavyDeception** [comment]
But this has given me an idea for a Feature Request about the power card and the book.

**Comment by HeavyDeception** [comment]
But this has given me an idea for a Feature Request about the power card and the book.
