### ISSUE TITLE
Energy Card Sensor  Min-Max

### ISSUE THREAD

**Issue by HeavyDeception** [Direwolf20-MC/LaserIO#189]
### Describe the feature you'd like to have added

Allow for the Sensor to read the Energy in a Block when it hits the minimum set % send a redstone signal when it hits the maximum set % stop the redstone signal, or vice versa maximum % send a redstone minimum stop it.

Also, could a note be added to the book that the Energy cards don't need a filter.

Please and thank you.

**Comment by Direwolf20-MC** [comment]
You can accomplish something similar using 2 cards on different channels and a little vanilla redstone :)

I’ll update the book though!
