### ISSUE TITLE
Suggestion/Question: Voiding Excess Item in the system?

### ISSUE THREAD

**Issue by Aloneatwar13** [Direwolf20-MC/LaserIO#19]
Any way to void extra items in the system once the dedicated chest in the system is full? Planned feature or upgrade card or is there already a way to do this that I am not comprehending?

Ex.  Dumping my pocket storage into a dump chest that then sorts all the materials to a grid of chests...but the system gets clogged with all the excess cobble and deepslate and things once the chest for these items are full and then fill the overflow/unsorted/misc. chest until eventually even the dump chest has no where to put anything.  Any chance for a workaround other than having to pick up all the excess items back up out of the system?

**Comment by Direwolf20-MC** [comment]
Use a trash can from the trash cans mod as the last priority. :).  No plans to implement item voiding at this time.
