### ISSUE TITLE
question on 1.6.4 version laser io

### ISSUE THREAD

**Issue by Vadewolf** [Direwolf20-MC/LaserIO#191]
### Describe the feature you'd like to have added

technically changed but pls make the requirement for patchouli not a hard requirement pls

### Additional information

pls change the laser io to not force require patchouli pls

**Comment by Direwolf20-MC** [comment]
I'll make the change in the next version and test it.

**Comment by Vadewolf** [comment]
thank you abd dude keep up the good work ure mods are awesome
