### ISSUE TITLE
Tag Filters not displaying all tags

### ISSUE THREAD

**Issue by Feliixtc** [Direwolf20-MC/LaserIO#192]
### LaserIO version

1.6.4

### Minecraft Version

1.20.1

### Forge Version

47.1.19

### Do you have optifine installed?

No

### Describe the issue

Tag filter not listing some or all tags of an item

### Steps to reproduce

1) Craft/Spawn a tag filter. 
2) Insert items to show tags.
   - Examples of no tag items: flint, bone meal, ink sacs, hoppers, pistons, paper, sugar cane... many more
   - Examples of missing tag items: golden apple, glow berries, grass block, leaf blocks...
3) Very limited sorting via tag filters :(

### Expected behaviour

when inserting item into tag filter, the filter shows all available tags pertaining to the item.

### Additional information

Some items such as the leaf blocks show a universal tag for ALL leaves, but not the tag for specific types of leaves

**Comment by Direwolf20-MC** [comment]
Typically flint doesn't have tags, and Leaves don't have tags that specify the leaves type. 

I'm pretty sure these are working the way they are meant to. Can you tell me what tags you expect to be on flint?

As far as I can tell (I just tested) the tag filter *is* showing all tags associated with the item in the slot. 

Can you elaborate on whats not working?

**Comment by Feliixtc** [comment]
Well, take the golden apple for example. When you put it in, it only shows a tag for minecraft:piglin_loved. It doesn't show the minecraft:golden_apple.

**Comment by Direwolf20-MC** [comment]
Right that’s how tags work :). I think you might be confusing tags with item names.

**Comment by Feliixtc** [comment]
Oh... I suppose that would make sense. No bug to report then, just a bit of ignorance on my end.
