### ISSUE TITLE
[Bug]: Unable to Pull Fluid out of Cauldron 

### ISSUE THREAD

**Issue by manmaed** [Direwolf20-MC/LaserIO#194]
### LaserIO version

1.5.2

### Minecraft Version

1.19.2

### Forge Version

43.2.21

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

Unable to Pull Fluid out of Cauldron 

### Steps to reproduce

1. place nodes around Minecraft Cauldron 
2. insert fluid card
3. place Lava in Cauldron
4. give fluid a tank to go in
5. notice no movement of fluid (and no laser connected to Cauldron)

### Expected behaviour

to be able to pull lava or other fluids out of a cauldron

### Screenshots

Cauldron: ![](https://ss.manmaed.net/1690655717.png)
Node Setup: ![](https://ss.manmaed.net/1690655763.png)
Connect to tank: ![](https://ss.manmaed.net/1690655792.png)
Tank Setup: ![](https://ss.manmaed.net/1690655822.png)

**Comment by Direwolf20-MC** [comment]
This is the vanilla minecraft cauldron correct? Do they support pulling fluids out of them with any piping system like Mekanism pipes or anything else?

**Comment by manmaed** [comment]
yes its the vanilla minecraft cauldron but just tried with Mekanism pipes and thay dont connect so maybe is not a fluid container in Forge?

**Comment by Direwolf20-MC** [comment]
Yup exactly :). Vanilla Minecraft doesn’t have fluid transport so vanilla blocks don’t support it or work like tanks. Sorry !

**Comment by manmaed** [comment]
Sad :(

**Comment by StarskyXIII** [comment]
There is a mod that allows the cauldron to interact with pipes.
https://legacy.curseforge.com/minecraft/mc-mods/capable-cauldrons
