### ISSUE TITLE
Can't include colon when adding entry to tag filter

### ISSUE THREAD

**Issue by hollis21** [Direwolf20-MC/LaserIO#195]
### LaserIO version

1.5.2

### Minecraft Version

1.19.2

### Forge Version

43.2.14

### Modpack & Version

Direwolf20 1.19 - 1.12.0

### Do you have optifine installed?

No

### Describe the issue

When entering tags into the tag filter, colons are stripped making typed in tags like "forge:ores" become "forgeores".

### Steps to reproduce

1. Open minecraft.
2. Right click with a Tag Filter in main hand.
3. Type `forge:ores` into text edit box.
4. Hit enter.
5. Observe `forgeores` was added to tag list.

### Expected behaviour

Given the above steps, `forge:ores` should be added to the tag list.

### Screenshots

![image](https://github.com/Direwolf20-MC/LaserIO/assets/1259600/bf9f8ba3-6ef9-44cd-be8d-00bec5b27657)
![image](https://github.com/Direwolf20-MC/LaserIO/assets/1259600/de609b5e-be40-410c-adbc-59a1dc17c914)

**Comment by Direwolf20-MC** [comment]
Thanks, I've fixed this in 1.20.1 :)
