### ISSUE TITLE
Exact amount weirdness with multiple Insert cards

### ISSUE THREAD

**Issue by Vatsune** [Direwolf20-MC/LaserIO#197]
### LaserIO version

1.5.2

### Minecraft Version

1.19.2

### Forge Version

43.2.14

### Modpack & Version

All The Mods 8

### Do you have optifine installed?

No

### Describe the issue

Extract Card extracts half of the set exact amount of fluid when connected to two Inserter Cards

### Steps to reproduce

1. Three fluid containers with a shared Laser node
2. One has Extract Card set to 2000 amount (with Overclocker), set to Exact
3. The other two have Inserter Cards with default settings
4. Placing one bucket of water (1000mB) will result in the fluid being extracted and inserted into one of the other tanks despite being half of the exact amount specified

https://github.com/Direwolf20-MC/LaserIO/assets/103251857/bdb2b6de-4a57-44d4-9b8b-bae4cf82edbf

### Expected behaviour

One bucket of water shouldn't be extracted if the exact amount is set to 2000

**Comment by Direwolf20-MC** [comment]
This should be resolved in the next version, thank you for the detailed report! :)
