### ISSUE TITLE
"Match NBT" option does not work as expected on counting filter

### ISSUE THREAD

**Issue by AmmoniumX** [Direwolf20-MC/LaserIO#198]
### LaserIO version

1.6.4

### Minecraft Version

1.20.1

### Forge Version

47.1.44

### Do you have optifine installed?

No

### Describe the issue

Counting filter does not respect multiple items with same ID, but different NBT

### Steps to reproduce

1. Open Minecraft World.
2. Grab two items with the same ID, but different NBT data (an easy example would be two enchanted books with different enchantments, such as Aqua Affinity and Silk Touch)
3. Setup basic LaserIO system, extracting from one chest to another
4. On one chest, place an item card set to "extract", no additional settings or filters added.
5. On the other chest, place an item card set to "insert", with a counting filter and set "Match NBT" on.
6. Set the counting filter one of each of the two enchanted books
7. Place both enchanted books on the input chest.
8. **Result**: only one of the two enchanted books will be transported to the output chest.

### Expected behaviour

Both of the enchanted books with different NBT data would be sent, as defined in the counting filter

### Screenshots

![Counting Filter Setup](https://github.com/Direwolf20-MC/LaserIO/assets/75765000/bfc7935d-8985-48f3-acb3-cb3e1a38fa87)

![Output Chest](https://github.com/Direwolf20-MC/LaserIO/assets/75765000/a2848ae9-098a-4e3f-a711-0c04c210afa5)
![Input Chest](https://github.com/Direwolf20-MC/LaserIO/assets/75765000/71fe7bfa-198f-48ef-b878-c34932392a38)

### Additional information

The bug happens with _any_ items that have the same ID but different NBT, I ran into this while trying to automate ultimate singularities from Extended Crafting, as every single singularity has the same ID, but differ in their NBT value

**Comment by Direwolf20-MC** [comment]
This bug has likely existed since forever and no ones ever caught it :). Nice catch! Resolved in the next version :)!
