### ISSUE TITLE
Suggestion - Multiple "Ordered Tags" (Composite Tags?)

### ISSUE THREAD

**Issue by ariosos** [Direwolf20-MC/LaserIO#20]
Unless I'm missing something, LaserIO should have multiple tags that narrow down items that should go into an inventory. For example, Thermal Expansion has tons of seeds. I would like if there's a tag that says, "First, find all items with the Mod Tag "Thermal Expansion". Second, place all Minecraft/Seeds from the matching Thermal Expansion mod tag into this chest". So, an items would have to match both "[Thermal Expansion Mod] AND [Minecraft/Seeds]". Likewise, a composite tag that can say, "All Thermal Expansion mod items AND NOT Minecraft/Seeds". So, a semi-query script.

**Comment by Direwolf20-MC** [comment]
The main challenge with this is ui - how to present this in a good way to a user. Also with only one filter per card it’s not trivial to do that kind of logic. 

I’ll see if I can come up with some kind of solution but for now it’s not a high priority. Sorry! Maybe after I get liquids and energy working.
