### ISSUE TITLE
NBT Filter doesn't filter correctly

### ISSUE THREAD

**Issue by Jona898** [Direwolf20-MC/LaserIO#200]
### LaserIO version

1.6.5

### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Modpack & Version

ATM9 0.0.58

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

I try to filter Apotheosis items with the tag affix_data, sometimes the items get sorted incorectly

### Steps to reproduce

1. Build a chest with 2 lasers with nbt filters. Use one filter for whitelist, other to blacklist the same tag. For example Enchantments.
2. Sort these into 2 different chests.
3. Fill source chest with items
4. Look into sorted inventories

### Expected behaviour

Items are correctly sorted after nbt tags

**Comment by Direwolf20-MC** [comment]
Closing for now as I assume this is fixed in 1.20 and above, if not just let me know.
