### ISSUE TITLE
NBT filter crash

### ISSUE THREAD

**Issue by zombiebush** [Direwolf20-MC/LaserIO#201]
### LaserIO version

1.6.5

### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

i deleted a line of text in the nbt filter and tried to exit the gui and game crashed

### Steps to reproduce

open nbt filter gui
type someting
delete said something
hit e to close gui

### Expected behaviour

i expected the gui to close

### Log files

[crash-2023-08-31_13.07.31-client.txt](https://github.com/Direwolf20-MC/LaserIO/files/12490047/crash-2023-08-31_13.07.31-client.txt)

**Comment by Direwolf20-MC** [comment]
Could not replicate - but added some code that might help prevent it?
