### ISSUE TITLE
1.19.2 Update request

### ISSUE THREAD

**Issue by svenfire99** [Direwolf20-MC/LaserIO#202]
### Describe the feature you'd like to have added

I recently played ATM9 (1.20.1) and had the latest featured and everything and I loved LaserIO, was the first time I tried it and helped a lot with making the base look compact and slim. But my partner wanted to do a complete pack so we switched back from ATM9 to ATM8 (1.19.2), but sadly I noticed none of the features I loved in the .20 version are in the .19
I would love to have the NBT filter at least again in the .19 and would help a lot with sorting items.

### Additional information

Update 1.19.2 with latest features, (NBT Filter, Card Holder holding filters, Advanced node)

**Comment by Direwolf20-MC** [comment]
Sorry but its a lot of work to backport a mod's new features :)
