### ISSUE TITLE
Advanced Laser Connector in Mining Dimension adding extra data

### ISSUE THREAD

**Issue by destrugter** [Direwolf20-MC/LaserIO#203]
### LaserIO version

1.6.5

### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Modpack & Version

ATM9 - 0.0.65

### Do you have optifine installed?

No

### Describe the issue

Advanced Laser Connector in Mining Dimension adding extra data which causes items to not stack

### Steps to reproduce

In a different dimension, transfer items from a storage container using the Advanced Laser Connector to the Overworld. In the Overword, add a container and connect it to a node. On the insert node add a basic filter to receive the item. When the item is transferred, the resulting item won't stack with any existing items.

### Expected behaviour

Items should stack

### Screenshots

![image](https://github.com/Direwolf20-MC/LaserIO/assets/2092138/83fcb634-53a9-4cb5-bea1-bfa73d43b541)
![image](https://github.com/Direwolf20-MC/LaserIO/assets/2092138/08888b36-8e85-40cd-bb90-16f5a5532440)

**Comment by Direwolf20-MC** [comment]
I am *Very* much having trouble reproducing this particular bug - I may have accidently done it once, but can't get it to replicate. Can you give me any more details on the laserIO setup that may have caused it?

**Comment by destrugter** [comment]
My setup was basically:

Created a mob farm in All The Mods 9 Mining Dimension
Mob farm drops get collected by a Sophisticated Backpack with a magnet
LaserIO node extracts from the backpack
LaserIO node is connected to a Advanced Laser Connector
Receiving Advanced Laser Connector in the overworld
LaserIO node is inserting to a Sophisticated Storage barrel for overflow purposes
LaserIO node is extracting from the barrel with a filter (for example, slimeballs)

The items would get stuck inside that barrel and refuse to insert into my Functional Storage drawers because of that extra space in the NBT. Having said all of that, I don't know now if it's specifically LaserIO's fault. I've been seeing other weird NBT related things like placing torches and breaking them and they won't stack now so I may have just made a mistake. Sorry about that, I think this can be closed if you can't recreate it.

**Comment by Direwolf20-MC** [comment]
I’ll leave it open for now in case someone else has the same problem :). It’s definitely possible that it’s me - I think I had a similar bug at one time in the past.

**Comment by Direwolf20-MC** [comment]
I'm gonna close this for now, if you can get it to reliably happen please let me know how :)
