### ISSUE TITLE
Laser Nodes get destroyed by water

### ISSUE THREAD

**Issue by sreny1** [Direwolf20-MC/LaserIO#204]
### LaserIO version

1.6.5

### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Modpack & Version

ATM9 0.1.7

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

Laser Nodes get destroyed by water

### Steps to reproduce

1. place Laser Nodes
2. place water above or within the same block
3. Laser Node gets destroyed

### Expected behaviour

Laser Node doesnt get destroyed by water

### Additional information

i would hope this isn't intentional, so i put this as a bug instead of feature request.
I would like to not break all the carefully setup Laser Nodes due to a single misclick with a bucket (again) :)

**Comment by Direwolf20-MC** [comment]
Resolved by: https://github.com/Direwolf20-MC/LaserIO/commit/3b2419fe5b57d6c5c33045b3201967ecd8bf23ae

Thanks for the report :)
