### ISSUE TITLE
Redstone Card Tooltip Always Shows Channel 0

### ISSUE THREAD

**Issue by jdratlif** [Direwolf20-MC/LaserIO#205]
### LaserIO version

1.4.5

### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Modpack & Version

Mechanical Mastery 1.5.0

### Do you have optifine installed?

No

### Describe the issue

Tooltip on Redstone Cards Always Shows Channel 0, no matter what channel is really set

### Steps to reproduce

Make node and redstone card. Configure redstone card to any channel other than 0. Hover over tooltip and it will say redstone channel 0.

### Expected behaviour

I expect it to say the redstone channel it is on.

**Comment by Direwolf20-MC** [comment]
Sorry, 1.18 is out of support at this time :) Its fixed in new versions though
