### ISSUE TITLE
Weird laser rendering with shaders enabled

### ISSUE THREAD

**Issue by Wolfonthehill14** [Direwolf20-MC/LaserIO#207]
### LaserIO version

1.6.6

### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Modpack & Version

All the Mods 9 - 0.1.12

### Do you have optifine installed?

No

### Describe the issue

When shaders are enabled, light blooming occurs on the laser that points to an inventory when the node has a card inserted and connected to the inventory. Also, the line that shows when two laser nodes are connected also disappears when shaders are enabled. I have gone through the shader settings and tried many different combinations to still have shaders enabled and not have this light blooming effect on the laser.

### Steps to reproduce

Download the All the Mods 9 Modpack and enable shaders that come with the modpack. It does not matter, but I am using the "potato" shader settings for this test.

Place down a couple of nodes and chests and insert the item cards in the correct sides to attach the laser to the chest inventory.

The same light bloom happens with fluid cards in a tank as well.

### Expected behaviour

Refer to the second screenshot. 

### Screenshots

![2023-10-08_11 10 19](https://github.com/Direwolf20-MC/LaserIO/assets/19322182/ece90c4d-3831-4fe6-b9a1-a4a546592fa2)

Screenshot with shaders enabled with no cards inserted

![2023-10-08_11 10 45](https://github.com/Direwolf20-MC/LaserIO/assets/19322182/4daeedcb-2fa1-4295-a4bf-919bc037dad2)

Screenshot with shaders disabled with cards inserted (Normal Behavior)

![2023-10-08_11 10 55](https://github.com/Direwolf20-MC/LaserIO/assets/19322182/b282c7a4-63f8-42df-8688-d0c109a5b4f6)

Screenshot with shaders enabled with cards inserted

![2023-10-08_11 25 56](https://github.com/Direwolf20-MC/LaserIO/assets/19322182/e9d481e0-48ef-4399-bf3e-c12c84d60b0e)

Screenshot with shaders enabled with fluid card inserted

![2023-10-08_11 26 05](https://github.com/Direwolf20-MC/LaserIO/assets/19322182/f2625c49-9d11-408c-a6d1-4a3ffb1e9df2)

Screenshot with shaders disabled with fluid card inserted

**Comment by Ridog** [comment]
Confirmed same behavior in most recent version of ATM9

**Comment by Direwolf20-MC** [comment]
Unfortunately I'm not really sure if this is something I can fix on my side?
