### ISSUE TITLE
Redstone Input and Output cards on the same block cause a toggle.

### ISSUE THREAD

**Issue by AerYareli** [Direwolf20-MC/LaserIO#208]
### LaserIO version

1.4.5

### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Modpack & Version

Mechanical Mastery r1.5.0

### Do you have optifine installed?

No

### Describe the issue

Redstone Cards don't update when a input and output card are on one side.

### Steps to reproduce

1. Place Laser Node
2. Any block on the north side(any side, I'm just using a direction for clarification) with 2 redstone cards on the north side, 1 is channel 1 output on high, other is channel 2 input
3. Place Lever on the south side with 1 redstone card, channel 1 input
4. Place redstone lamp(or dust) on west side with 1 redstone card, channel 2 output, high or low
5. Switching the lever will "power" the block but not update the channel 2 redstone card
6. Turning off the lever will turn off channel 1 but now power channel 2 thus turning the redstone lamp on

### Expected behaviour

Switching the lever powers the block and lamp

### Screenshots

![2023-10-14_14 48 05](https://github.com/Direwolf20-MC/LaserIO/assets/106533856/6d3866a8-a5c4-45e1-8687-68ebf7c9d7b4)

### Additional information

I assume it has something to do with redstone order ticks but overlocking the node or switching around the cards don't effect the issue at all, another theory is maybe the laser node has some similarities to quasi connectivity from vanilla, since "updating" the block by placing or remove a block next to it fixes the channels

**Comment by Direwolf20-MC** [comment]
Vanilla redstone is cursed- this is known :).  I believe you are correct that the order of ticks has something to do with this, but I have no idea how to work around it in an efficient way. I'm going to chalk this up as a weird edge case.
