### ISSUE TITLE
Cutting advanced laser connector crashes game

### ISSUE THREAD

**Issue by saddle116** [Direwolf20-MC/LaserIO#209]
### LaserIO version

1.6.6

### Minecraft Version

1.20

### Modpack & Version

Direwolf20 1.20

### Do you have optifine installed?

No

### Describe the issue

Crash when using building tools cut-paste gadget to cut linked advanced laser connector

### Steps to reproduce

Link two advanced laser connectors across dimensions (tried with mining-dimension to overworld and nether to overworld)

Select area containing one laser connector with cut-paste gadget from building tools

Cut

*World saves, game crashes*

Upon restarting, area was successfully cut and is ready for pasting as expected. Paste works as expected, connector remains linked

### Expected behaviour

Game does not crash upon cutting

**Comment by Direwolf20-MC** [comment]
Thanks for the report will check it out :)

**Comment by Direwolf20-MC** [comment]
Found the bug, thank you!
