### ISSUE TITLE
Suggestion: Snapshot feature for stocking card

### ISSUE THREAD

**Issue by rebio** [Direwolf20-MC/LaserIO#21]
An idea I got from Lets Play S11E12: A button that let's you snapshot the content of an inventory and keep in stock what is in the chest with exact quantity and maybe even storage slot.
Storage slot could be interesting if you want the inventory (eg. chest) to be organised in a specific way (eg. row 1: metals, row 2: gems, row 3: dusts, row 4: building blocks)

**Comment by Direwolf20-MC** [comment]
Too much strain on performance to keep items in the right slots sadly. Snapshot mode is unlikely as well due to the limits on stocking filter size.
