### ISSUE TITLE
Alternative to covers.

### ISSUE THREAD

**Issue by swestrup** [Direwolf20-MC/LaserIO#212]
### Describe the feature you'd like to have added

I know that a request for covers was already put in, and I would be happy with that. But I was thinking it would be nice to have a 'camouflage card' that you could put in and hand a block, and the laserio node would take on the appearance of that block. For advanced camouflage one could specify up to six blocks, and have a different texture on each side.

**Comment by Direwolf20-MC** [comment]
Its a cool idea I'll take under advisement, but its a lot of complexity to add :).  For now I'm gonna hold off, but maybe some day!
