### ISSUE TITLE
Refined Storage auto crafting issue

### ISSUE THREAD

**Issue by bigtruckin78** [Direwolf20-MC/LaserIO#213]
### LaserIO version

1.6.6

### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Modpack & Version

ATM 9 0.2.12

### Do you have optifine installed?

No

### Describe the issue

Trying to auto craft advanced filters in Refined Storage. Example. Patterns for counting filter and all underlying components are installed in Refined. Try to auto craft a counting filter and it will not work because it will not see the basic filter recipe. Tried exact mode in patterns with same result. 

### Steps to reproduce

Set up an advanced filter (counting, nbt, mod, ect) in Refined storage auto crafter including all underlying recipes. 

Try to auto craft the advanced filter and it will not be able to complete.

### Expected behaviour

Should be able to auto craft filter if all underlying recipes are included.

**Comment by Direwolf20-MC** [comment]
I can’t imagine how that would be an issue on my end. Ensure the output of the basic recipe is a basic filter without any nbt tags on it (freshly crafted).
