### ISSUE TITLE
Ctrl+Shift doesn't work on Fluid Card Counting Filters

### ISSUE THREAD

**Issue by Direwolf20-MC** [Direwolf20-MC/LaserIO#216]
### LaserIO version

Latest

### Minecraft Version

Latest

### Do you have optifine installed?

No

### Describe the issue

See subject

### Steps to reproduce

See subject

### Expected behaviour

Fix it Dire

**Comment by jlp1528** [comment]
LOL this made my day! Fix it Dire! XD
You might want to look into whether this is caused by inventory sorting mods if you haven't already. Happy fixing!

**Comment by Direwolf20-MC** [comment]
It absolutely works in my dev environment - some other mod must be causing this!

**Comment by Direwolf20-MC** [comment]
Lets see what happens in 1.21, and if it still is an issue
