### ISSUE TITLE
green  shine when using shader packs

### ISSUE THREAD

**Issue by magicbanana666** [Direwolf20-MC/LaserIO#217]
### LaserIO version

1.6.7

### Minecraft Version

1.20.1

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

when using shader packs the laser io mod and mining gadget are not usable because of a giant green shine around the blocks/lasers

### Steps to reproduce

user optifine or oculus and install a shader pack 
look at a laser io with cards in it or use the laser from mining gadget and you will see an enormous giant sheen

### Expected behaviour

a nice sheen but not the giant green shine

### Screenshots

![image](https://github.com/Direwolf20-MC/LaserIO/assets/151096720/f2bd0b33-201d-4bb9-bb1a-3698269fdd08)

**Comment by MichaelHillcox** [comment]
What shader pack do you see this with specifically?

**Comment by peisach** [comment]
Complementary reimagined.  I have seen the effect in a few different mod
packs.

Daniel

**Comment by cxf213** [comment]
![2023-12-10_17 32 05](https://github.com/Direwolf20-MC/LaserIO/assets/26163328/ff19ffb6-fee8-456c-9286-03c8ff637d34)
ComplementaryShaders_v4.7.2

![2023-12-10_17 32 13](https://github.com/Direwolf20-MC/LaserIO/assets/26163328/c8780f22-f704-49ee-bb27-48f090154af6)
MakeUp-UltraFast-8.8e

i have the problem too.

**Comment by MindBrain27** [comment]
I have the same green glow as above using almost any shader pack with occulus. I tried 10 shaders and they were all a massive green glow.

**Comment by Ubaje** [comment]
turn off bloom in shaders. "Options..." -> "Video Settings..." -> "Shader Packs..." -> "Shader Pack Settings..." -> "Camera" -> "Bloom": Off

**Comment by peisach** [comment]
That works.  Thanks!

Daniel
