### ISSUE TITLE
fluid insert cards do not oredict

### ISSUE THREAD

**Issue by jlp1528** [Direwolf20-MC/LaserIO#218]
### LaserIO version

1.6.7

### Minecraft Version

1.20.1

### Forge Version

47.1.76

### Modpack & Version

Direwolf20 1.20 (1.7.0)

### Do you have optifine installed?

No

### Describe the issue

I keep having this problem with Fluid XP. There are many oredict entries including XP Juice, Cognitium, and mob essence. If one of them is already present in a container but the source does not match (different oredict entry) the fluid will not insert.

### Steps to reproduce

1. Insert an oredicted fluid into any LaserIO-able tank.
2. Attempt add fluid to the tank with a fluid insert card. Use a different oredict entry of the same type of fluid.
3. Fluid does not insert.

### Expected behaviour

I expect proper fluid oredicting. ;)

**Comment by MichaelHillcox** [comment]
The ore dictionary is a thing of the past. Unfortunately what you're explaining is just how the fluid system in minecraft works. Assuming you're playing a modpack, we could open up the option to handle fluids via tags but this would be really hacky as we'd need to replace one fluid for another which isn't idea... 

Not really sure on the best way forwards here

**Comment by Direwolf20-MC** [comment]
I agree with Mikey - since MOST fluid containers can only accept one kind of fluid, you rarely want to allow different types into the same filter - so for now, if you want to allow this, just put all 3 fluid types into the whitelist.  :)
