### ISSUE TITLE
Laser Node not showing Yellow energy laser when attached to EnderIO Energy Conduit

### ISSUE THREAD

**Issue by Natervater** [Direwolf20-MC/LaserIO#219]
### LaserIO version

1.6.7

### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Modpack & Version

Direwolf20 1.20

### Do you have optifine installed?

No

### Describe the issue

Small graphical issue: Laser Node not showing Yellow energy laser when attached to EnderIO Energy Conduit but power does flow

### Steps to reproduce

1. Run Energy conduit with power
2. Place energy node next to conduit
3. add yellow card to node to extract power
4. Yellow beam indicating its attached does not appear

### Expected behaviour

Yellow laser indicating transfer appears

### Screenshots

![laser1](https://github.com/Direwolf20-MC/LaserIO/assets/54920173/908f7513-2410-400e-98aa-1830339d105e)
![laser2](https://github.com/Direwolf20-MC/LaserIO/assets/54920173/7011d852-77bf-45f8-9080-78e7bb664da3)
![laser3](https://github.com/Direwolf20-MC/LaserIO/assets/54920173/442429fe-9703-4ecb-9a8d-01699bdd1409)

### Additional information

Huge fan of the mod Direwolf! Thank you for all the hard work! Let me know if I can help test issues!

**Comment by Direwolf20-MC** [comment]
This is a weirdness with EnderIO I believe - I've gotten it to work, but its really wonky.  Its about how EnderIO handles its connections.
