### ISSUE TITLE
Bug: Dragging items into filter from JEI causes game crash

### ISSUE THREAD

**Issue by jtrain564** [Direwolf20-MC/LaserIO#22]
Found another bug for you Dire.  On mod version 1.0.3, I ran into an odd issue where dragging an item into the filter from JEI would cause the item to disappear from JEI and be replaced with an invisible item with the tag "Minecraft:air".  Clicking on that item again in JEI would crash the game.  Performing the same action with JEI using a Refined Storage Pattern Grid does not produce the same results in JEI which leads me to believe it is a mod interaction.

Edit:  Found in a much larger modpack, but still repeatable in a simple world with only JEI and LaserIO installed.

**Comment by Direwolf20-MC** [comment]
Notes for myself to follow:
Can't reproduce on the version of JEI in my dev environment, will update JEI and try again shortly.

**Comment by jtrain564** [comment]
Here's my crash report from my test world using only JEI and LaserIO
[Crash Report.txt](https://github.com/Direwolf20-MC/LaserIO/files/8835435/Crash.Report.txt)
.

**Comment by Direwolf20-MC** [comment]
Fixed: https://github.com/Direwolf20-MC/LaserIO/commit/74658ba377274d78a0cf442683f3429cb29d2ebd
