### ISSUE TITLE
Card cloner crashing the client when sneaking (tooltip) when copied card is energy

### ISSUE THREAD

**Issue by Anoyomouse** [Direwolf20-MC/LaserIO#220]
### LaserIO version

1.6.7

### Minecraft Version

1.20.0

### Forge Version

neoforge-1.20.1-47.1.76

### Modpack & Version

Direwolf20 - 1.20 - 1.7.0

### Do you have optifine installed?

No

### Describe the issue

Card cloner crashing the client when sneaking (tooltip) when copied card is energy

### Steps to reproduce

1. Open laser node
2. Add an energy card, and add in overclockers (optional I think)
3. Copy the contents of the card with the card cloner
4. Hold shift while hovering over the card cloner
5. Crash to desktop

### Expected behaviour

The card cloner should display the information from the energy card

### Log files

https://paste.feed-the-beast.com/view/0c421637

### Additional information

As first reported by Volrath on the DW20 discord server, and reproduced by myself.

I have isolated it down to:
https://github.com/Direwolf20-MC/LaserIO/blob/d0035d7c9c7210b70cbc13cb63043e8821c4412a/src/main/java/com/direwolf20/laserio/common/items/CardCloner.java#L155
Which is called from:
https://github.com/Direwolf20-MC/LaserIO/blob/d0035d7c9c7210b70cbc13cb63043e8821c4412a/src/main/java/com/direwolf20/laserio/common/items/CardCloner.java#L98

Specifically for energy cards (I had copied a card with overclockers)

**Comment by Direwolf20-MC** [comment]
Should be resolved now :)
