### ISSUE TITLE
crash loop when extracting from  armory cabinets

### ISSUE THREAD

**Issue by wraithhawit** [Direwolf20-MC/LaserIO#222]
### LaserIO version

1.6.6

### Minecraft Version

1.20.1 

### Modpack & Version

ATM9 0.2.12 

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

server is in a crash loop

### Steps to reproduce

1. armory cabinet with swords and armors
2. 9 extracting item cards overclocked to max with 8 node overclocks
3. inserting with filter into trash can

### Expected behaviour

.

### Log files

[----_Minecraft_Crash_Report_---- (1).txt](https://github.com/Direwolf20-MC/LaserIO/files/13482367/----_Minecraft_Crash_Report_----.1.txt)

**Comment by Direwolf20-MC** [comment]
How many 'slots' are inside this inventory? I assume a very large number, and that is likely the culprit.  Extract cards iterate over all slots in an inventory looking for a match, if that inventory has hundreds or thousands of slots, it can take a while to go over it all.  Suggestion is to not use so many overclockers on a very large inventory like that.
