### ISSUE TITLE
Card Extension

### ISSUE THREAD

**Issue by FlorentTomi** [Direwolf20-MC/LaserIO#223]
### Describe the feature you'd like to have added

It would be nice to have the possibility to extend the card pool from other mods, by having a dedicated extension API.
Example:
- Mekanism Gas/LaserIO mod extension
- (Bad example but still an example) Create/LaserIO mod extension

API usage example:
```
import com.direwolf20.laserio.api.API;
...

API.CardRegistry.add(new ResourceLocation(extensionModId, "customcard"), customCardSupplier);
```

**Comment by Direwolf20-MC** [comment]
Gas cards are planned to be supported - I just keep losing time:).

**Comment by FlorentTomi** [comment]
It was more about implementing an external API we can tap in ;) (eg. like Jade or JEI)
It would probably be a lot of work, but it would help delegate the mod integration.
