### ISSUE TITLE
Compatibility with Pipez and AE2

### ISSUE THREAD

**Issue by DarkWolfe5** [Direwolf20-MC/LaserIO#225]
### Describe the feature you'd like to have added

I've been trying to set up a rather complex network, and some areas LaserIO is great, others I use Pipez, and occasionally I need the AE2 interfacing, for crafting and the like. 
Problem is, attempting to connect a laser node to a pipez pipe never shows a binding laser with any card in. Ditto with AE2 buses (storage, import, and export). I assume AE2 and Pipez are not currently supported by LaserIO.

I'd love to be able to use an AE2 storage bus to transfer items/fluids back and forth between LaserIO network and AE2 network.

**Comment by Direwolf20-MC** [comment]
Use an interface for the ae2 network :). Pipez isn’t really gonna happen unfortunately.

**Comment by DarkWolfe5** [comment]
Well, I WAS going to test that out tonight, but apparently the nodes aren't fully compatible with Mekanism mechanical pipes (for fluids) and/or the Mekanism pump.
I have one connected to the pump with an extract fluid card and another nearby with an insert fluid card. Both are linked to each other, the cards are both on the same channel, and there's the blue lasers to both the pump and pipe, but no water seems to be flowing. Because of that my whole power system is bone dry and dead as a door nail. :-(
I'm also using energy cards to pull from the grid and insert into the pump, and both are in the right place for the pump (I just re-checked online). It seemed like it was pulling power from the Mekanism universal cables just fine when I first set it up yesterday. I could see machines that had depleted return to full power.

Is there something I'm doing wrong, or do the fluid cards just not work with Mekanism pipes?
