### ISSUE TITLE
Channels on Sensors

### ISSUE THREAD

**Issue by Pontiac76** [Direwolf20-MC/LaserIO#226]
### LaserIO version

1.6.7

### Minecraft Version

1.20.1

### Modpack & Version

Direwolf20 - 1.20

### Do you have optifine installed?

No

### Describe the issue

Hovering and clicking activates channels, but, no channel button is showing

### Steps to reproduce

Switch the item card into sensor mode, and the icon that represents the channel button at the lower-left, just above the players inventory, is not shown, however, you can hover, and select a channel.

I don't know if this icon should be shown, or if the functionality of clicking to select a channel should disabled, but, as it sits, the UI isn't representing the suggested activities for either case.

### Expected behaviour

Either show the button for the channel, or, not.

### Screenshots

![image](https://github.com/Direwolf20-MC/LaserIO/assets/4532020/d0f72002-676f-49f2-a63d-40399c37ff66)

**Comment by Direwolf20-MC** [comment]
Cards ignore their channel when on sensor mode (as there’s really no functionality for that). As a result the button is hidden. It’s weird that it’s still available to be clicked but it won’t hurt anything. I’ll check into it sometime :)
