### ISSUE TITLE
Card Holder can reset the cards

### ISSUE THREAD

**Issue by Pontiac76** [Direwolf20-MC/LaserIO#227]
### Describe the feature you'd like to have added

Having a set of already-configured cards in the card holder can be a bit of a pain to reset.  To do so, you'd have to first turn off the card holders auto-collect function, eject the affected cards, put the cards in a crafting table (2x2 or 3x3), then put the card back into the holder.

Instead, I suggest either 
- a single button that'll reset all cards in the card holders inventory to default setting, re-sort/re-organize the cards
- {key modifier}-[right/left]click to reset the individual cards.

**Comment by Direwolf20-MC** [comment]
I'll add it to the 'nice to have' features list :)
