### ISSUE TITLE
Card Cloner crashes client

### ISSUE THREAD

**Issue by Pontiac76** [Direwolf20-MC/LaserIO#229]
### LaserIO version

1.6.7

### Minecraft Version

1.20

### Modpack & Version

Direwolf20 1.20

### Do you have optifine installed?

No

### Describe the issue

Card Cloner crashes client

### Steps to reproduce

Craft the Card Cloner
Place on hot bar
Hover over the Cloner
Press Shift
Client crashes after a second or two.

I'm playing on a server of my own, on my LAN, not exposed to the internet.

### Expected behaviour

Nooooo crashy crashy.  I actually expected to see how to use the card, since I wanted to copy/paste RF card settings.

### Log files

https://pastebin.com/raw/RAi3BQ7G

**Comment by Pontiac76** [comment]
I just happened to catch this in the FTB launcher

[20:06:58] [Render thread/WARN] [co.re.re.sc.gr.st.ItemGridStack/]: Could not retrieve item tooltip of laserio:card_cloner

Not sure what triggered that.

**Comment by PolygonError** [comment]
also experienced this in All The Mods 9
did you have card overclockers in the card you cloned from?

LaserIO version
1.6.7

Minecraft Version
1.20.1

Forge Version
47.2.16

Modpack & Version
All The Mods 9 - 0.2.32

Do you have optifine installed?
No

Describe the issue
Playing on multiplayer server, not on LAN.

Log files
https://pastebin.com/Py2iMG5N

**Comment by Pontiac76** [comment]
That IS a possibility?  I did shift-click on one of the power cards that were configured with 4 overclockers, tried going to another card but I didn't notice anything.  I then saw the popup about shift, acted on it, and the client crashed.  I don't think the server said anything, but didn't think to look.

**Comment by ElementalWisp** [comment]
Got the same error in crash log.

**Comment by Pontiac76** [comment]
Closing.  Already in #220
