### ISSUE TITLE
Shift-right_clicking tag filter   into/out of slot in item card crashes game

### ISSUE THREAD

**Issue by Tomoyukiryu** [Direwolf20-MC/LaserIO#23]

**Comment by Direwolf20-MC** [comment]
Can't reproduce -- need a crash log.

**Comment by Tomoyukiryu** [comment]
I can't seem to reproduce the thing myself ,but here is crush log anyway
[2022-06-01-4.log](https://github.com/Direwolf20-MC/LaserIO/files/8836101/2022-06-01-4.log)

**Comment by Tomoyukiryu** [comment]
and Sorry that I didn't post the crush log earlier

**Comment by Direwolf20-MC** [comment]
Thanks :) I got it.
