### ISSUE TITLE
Channel Select Window.

### ISSUE THREAD

**Issue by HeavyDeception** [Direwolf20-MC/LaserIO#233]
### Describe the feature you'd like to have added

When holding shift and clicking on the Channel color selector it brings up a window to select from the 16 channels.

### Additional information

The reason for this request is I find myself changing channels and having items or fluids filling blocks I don't want to fill with the item or fluid this way to can just go to that channel and not cycle.

**Comment by Direwolf20-MC** [comment]
Definitely understand the reason for the request, but its non-trivial to implement :).  For now I'd just say to set your channels before doing stuff, and I'll see if I can come up with another solution.
