### ISSUE TITLE
[Feature request] Node-local Redstone control of Cards

### ISSUE THREAD

**Issue by CarlSmotricz** [Direwolf20-MC/LaserIO#235]
### Describe the feature you'd like to have added

Item/Fluid/Energy cards can be controlled by network-global Redstone signals on one of 16 channels. While useful, this is also a bit limiting insofar as no matter how big the network, a maximum of 16 different signals can be effective.

I propose allowing, alternately, for a card to be controlled by the Redstone level of the Node it's in, so the function of one or more cards in a Node can be controlled by applying an external signal to the Node rather than generating a channel-bound signal via a Sensor or Redstone Card.

This would allow LaserIO Nodes to be directly Redstone controlled in a way similar to (e.g.) Hoppers or Pipez Pipes.

In the Card UI, this could be represented by
- a 17th state of the Redstone Channel button or
- a checkbox labelled "Node Redstone level" or such, which could disable the Redstone Channel button.

**Comment by Direwolf20-MC** [comment]
That seems awfully complex and unintuitive :).  At best, I might consider disabling the whole node when it gets a redstone signal - so that all cards get disabled.  No promises though :)

**Comment by Ryan6794** [comment]
Did a mechanic like this ever get implemented? I could really use it.

**Comment by CarlSmotricz** [comment]
Nope, Direwolf rejected it.

I understand why. It would add features that would be hard to grasp
intuitively. I think even I had trouble understanding the description of
the proposed change, and I'm the one who wrote it!

What my suggestion is missing is an elegant, intuitively understandable way
to represent it in a GUI.

**Comment by Ryan6794** [comment]
That's a shame. Having a way to use a redstone signal locally to disable a node is a key factor or my automation at the moment.
