### ISSUE TITLE
card holder can crash the game

### ISSUE THREAD

**Issue by greatmonkey** [Direwolf20-MC/LaserIO#236]
### LaserIO version

1.6.7

### Minecraft Version

1.20.1

### Forge Version

47.2.19

### Modpack & Version

ATM9

### Do you have optifine installed?

No

### Describe the issue

card cloner crashes the game after it gets bad data in it

### Steps to reproduce

I had copied a fluid card and pasted it just find on other cards, then tried to copy an energy card and paste that onto another energy card however it caused my game to crash and if that card go's into my active hand then the game will crash after.

### Expected behaviour

game to not crash

### Log files

https://mclo.gs/t4GNIps

**Comment by Direwolf20-MC** [comment]
Nevermind found it -- need overclockers :).  Fixed!
