### ISSUE TITLE
Node colour

### ISSUE THREAD

**Issue by artrorrr** [Direwolf20-MC/LaserIO#237]
### Describe the feature you'd like to have added

Similar to how the colour of ''core'' of a laser node can be changed, 
why not the frames, instead of just being white/grey? 

### Additional information

Since I saw last dw20 play series and started playing atm9, I can't use anything other than LaserIO. 
The only issue I have - colour of the frame, especially when trying to colour match with other mods/blocks. 
(great mod btw)

**Comment by Direwolf20-MC** [comment]
I'll add it to the wish list for when/if I get some extra time :)
