### ISSUE TITLE
Node overclocker won't work

### ISSUE THREAD

**Issue by elsombrero777** [Direwolf20-MC/LaserIO#242]
### LaserIO version

1.6.7

### Minecraft Version

1.20.1

### Forge Version

47.2.19

### Modpack & Version

AllTheMods9 - 0.2.39

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

I'm trying to use 2 extract cards on the same side of a node using 1 node overclocker, but only one extract card is pulling items from the chest, both extract cards are using the same config and thereby the same channel at 64 items/t.

### Steps to reproduce

1. place a node next to a @sophisticatedstorage diamond chest
2. insert 2 extract cards on the chest side with 4 card overclockers each and config them to the same channel and 64 items/t
3. insert a node overclocker on the 2 card's side
4. insert various blocks on the chest and you'll realise only one card is extracting stuff

### Expected behaviour

Since 1 node overclock is enough for 2 cards both should work

### Screenshots

https://imgur.com/a/ZYLEte3

**Comment by Direwolf20-MC** [comment]
Can't seem to reproduce this in my dev environment, i'm able to pull from a vanilla chest and a sophisticate storage diamond chest just fine, the particles existing on both lasers show that its working. Is it possibly a mod in your pack thats conflicting somehow?

![image](https://github.com/Direwolf20-MC/LaserIO/assets/39863894/4813a691-8f55-4a9a-85ec-040ee28cfb0f)
