### ISSUE TITLE
Editing Energy card doesn't show card holder GUI on the left

### ISSUE THREAD

**Issue by PantACRO4life** [Direwolf20-MC/LaserIO#246]
### LaserIO version

1.6.8

### Minecraft Version

1.20.1

### Forge Version

47.2.19

### Do you have optifine installed?

No

### Describe the issue

Editing Energy card doesn't show card holder Inventory GUI on the left

### Steps to reproduce

1. Open Energy card to edit it while you have card holder in your inventory.

You won't see a card holder GUI inventory on the left.

### Expected behaviour

see a card holder GUI inventory on the left

### Screenshots

Energy card 
![image](https://github.com/Direwolf20-MC/LaserIO/assets/6643071/5515ca78-90a5-4257-a4a5-3c8933e35b23)

VS ITEM CARD.
![image](https://github.com/Direwolf20-MC/LaserIO/assets/6643071/d4932140-1ee3-4a9b-8567-88cbaa979533)

**Comment by Direwolf20-MC** [comment]
Removed the need for this in 1.20.4

**Comment by PantACRO4life** [comment]
ok but not all the mods are yet on 1.20.1. 
can I fix it on my side ? if so can you share which part it was ?

Thank you

**Comment by Direwolf20-MC** [comment]
Energy cards no longer need overclockers at all

https://github.com/Direwolf20-MC/LaserIO/pull/239
