### ISSUE TITLE
Backport 1.7.1 to 1.20.1?

### ISSUE THREAD

**Issue by Victor333Huesca** [Direwolf20-MC/LaserIO#248]
### Describe the feature you'd like to have added

Do you consider backporting the 1.7.1 release to minecraft 1.20.1?
Or is it too big of a hassle to do so now that the main branch have been moved to 1.20.4.
Most modpacks are still on 1.20.1 for the time being (like `atm9` or `ftb direwolf20 1.20` to name a few).

I know that _1.6.8_ was supposed to be the last release on minecraft 1.20.1.
From 1.6.8 changelog:
> Final release in 1.20.1 -- Unless I #direDerp'd somethin fierce in this one :)

Release 1.7.1 added chemical gas card, which can be considered as a major QoL improvement if you ask me (thanks for that, eager to test it)!

**Comment by dylithian** [comment]
I'd like to add my voice to this and say that I agree. I'm running a server on the Direwolf20 pack for 1.20 and given that that's still running on 1.20.1, it would be delightful to have gas card compatibility for what I would argue is the most robust I/O solution in the pack.

**Comment by Direwolf20-MC** [comment]
It’s a lot of work to back port a feature. I’m sorry but I’ll have to pass for now as I’d rather spend time on more fun stuff :) 

1.21 is just around the corner :)
