### ISSUE TITLE
LaserIO / AE2 - Node not extracting from Inscriber

### ISSUE THREAD

**Issue by EdwardLemayDev** [Direwolf20-MC/LaserIO#25]
Laser Node doesn't extract finished processor when the Inscriber's middle slot has something in it. Once you remove the item from the middle slot it works fine

**Comment by WyFryMU** [comment]
Seems like the same issue I'm having with Mekanism machines #24

**Comment by EdwardLemayDev** [comment]
Maybe, I think it might be a problem with the fact that the Inscriber use the same faces for multiple slots. But I really don't know how either are coded

**Comment by Direwolf20-MC** [comment]
Can you guys try with the latest version 1.03 and let me know if it’s still happening ?

**Comment by EdwardLemayDev** [comment]
It seems to work fine with version 1.0.3. It extracted from the Inscriber even with redstone in the middle slot. Btw the side control is so nice to have with AE2 Inscriber !!
