### ISSUE TITLE
LaserIO nodes expose their card inventory to be extracted from

### ISSUE THREAD

**Issue by mikerooni** [Direwolf20-MC/LaserIO#250]
### LaserIO version

1.6.8

### Minecraft Version

1.20.1

### Do you have optifine installed?

No

### Describe the issue

LaserIO nodes expose their card inventory to other blocks interacting with them. This leads to other mods' blocks/pipes/machines/etc. extracting cards from the node, instead of extracting what the node is actually transferring.

### Steps to reproduce

This has been reported to me in the context of GregTech CEu Modern, so I'll use it for this example:

1. Place a LaserIO node next to an item input bus from GT and leave the bus enabled
2. Place a card in the LaserIO node
3. The GT input bus (when left enabled) will attempt to extract items from adjacent inventories and thereby pull the card from the LaserIO node

### Expected behaviour

It should not be possible to extract cards from LaserIO nodes

### Additional information

While this is technically a duplicate of #144, I genuinely believe this is a bug and _not_ a feature, as it completely breaks LaserIO functionality when trying to insert into anything that also has the ability to extract from an adjacent inventory.

LaserIO nodes should not expose their card inventory as a capability.  
If this is **really** necessary, it should be an optional toggle for each node, though I can personally not think of any situation that would actually require this.

**Comment by mikerooni** [comment]
@Knifepony pinging you since you reported this to me

**Comment by Direwolf20-MC** [comment]
I had intended to remove this in 1.21 - but forgot.  I worry that doing so now will break some things, so I'll aim to do it in 1.22 :)
