### ISSUE TITLE
Itemsink Filter?

### ISSUE THREAD

**Issue by PianoHallvard** [Direwolf20-MC/LaserIO#252]
### Describe the feature you'd like to have added

Similar to the old Logistics Pipes ItemSink module, this would insert items into an inventory only if said inventory already contains those items.
Would be a neat feature

**Comment by Direwolf20-MC** [comment]
I wanted something like this, but the cost (in terms of TPS) of scanning an inventory every time you insert something to see if something like it already exists is kind of large.
