### ISSUE TITLE
Item card in sensor mode with tag filter doesn't work properly

### ISSUE THREAD

**Issue by djmattyg007** [Direwolf20-MC/LaserIO#253]
### LaserIO version

1.5.2

### Minecraft Version

1.19.2

### Forge Version

43.3.5

### Modpack & Version

FTB Skies 1.4.1

### Do you have optifine installed?

No

### Describe the issue

Item cards in sensor mode don't work correctly when configured with a tag filter. Both "AND" and "OR" modes are buggy in different ways.

### Steps to reproduce

I have a tag filter configured like this:

![image](https://github.com/Direwolf20-MC/LaserIO/assets/489338/e91d97c7-23c5-4557-82c6-224a410d436c)

I have the tag filter inside an item card in sensor mode, configured in "OR" mode like this:

![image](https://github.com/Direwolf20-MC/LaserIO/assets/489338/ecc59596-3723-4c35-9d7b-d037031230c3)

I have it connected to a chest with a gold chestplate in it. There should be a redstone signal, but there isn't one.

![image](https://github.com/Direwolf20-MC/LaserIO/assets/489338/b3a5ff68-c33b-493e-bc47-30dce412de6b)

It turns out it does emit a redstone pulse the first time the condition becomes true after configuring (or re-configuring) the item card, but it never emits a signal of any nature after that.

If I change the card to operate in "AND" mode, it correctly emits a signal:

![image](https://github.com/Direwolf20-MC/LaserIO/assets/489338/14453e26-6753-45c3-a985-e69058dc4b67)

But it keeps emitting a signal even after the items are removed from the chest:

![image](https://github.com/Direwolf20-MC/LaserIO/assets/489338/7594051b-d6de-4621-ac79-ce22da2b0925)

### Expected behaviour

The redstone signal should be persistent when the conditions are met, as per the mod's documentation in the book

**Comment by Direwolf20-MC** [comment]
This is now resolved in newer versions :) thank you!
