### ISSUE TITLE
Card Holder Shenanigans

### ISSUE THREAD

**Issue by PianoHallvard** [Direwolf20-MC/LaserIO#254]
### Describe the feature you'd like to have added

Sometimes when I go to craft filters other than the regular one, when I've crafted the regular filter, it gets swooped into the card holder. 
My suggestion is to either 
1: make it so the player can "filter" the card holder to blacklist certain card-holder-enabled items
or 2: Make the card holder show up in crafting tables

**Comment by Direwolf20-MC** [comment]
The 'vacuum' ability can be turned off :).  I would recommend leaving it off, and only turning it on as needed.
