### ISSUE TITLE
Crash between Hyperbox and LaserIO

### ISSUE THREAD

**Issue by Frostbyt3** [Direwolf20-MC/LaserIO#256]
### LaserIO version

1.6.8

### Minecraft Version

1.20.1

### Forge Version

47.2.23

### Modpack & Version

Custom Modpack

### Do you have optifine installed?

No

### Describe the issue

Server Crash when attempting to break a Hyperbox with Advanced Laser inside

### Steps to reproduce

1. Place Hyperbox
2. Place Advanced Laser Connector inside and link it to the overworld.
3. Connect Advanced Laser Connector to a Laser Node with an Energy Card inside of it.
4. Break Hyperbox and pick it up.

### Expected behaviour

Server should not crash upon breaking a Hyperbox

### Log files

https://pastebin.com/AT7hiR5t

**Comment by Direwolf20-MC** [comment]
This probably wouldn't happen anymore, but I added a nullcheck in that method to be extra safe :)
