### ISSUE TITLE
Card Holder does not support right-clicking itemstacks

### ISSUE THREAD

**Issue by wrincewind** [Direwolf20-MC/LaserIO#257]
### LaserIO version

1.6.8

### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Modpack & Version

All The Mods 9 - 0.2.56

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

If you have a stack of filters in your card holder (e.g. Basic Filters) and right-click on the stack, nothing happens. Doing the same thing to the stack when it's in your inventory gives you half the stack, as expected. 

### Steps to reproduce

1) place a stack of item filters into your Card Holder's inventory
2) right click the stack. (observe that nothing happens)
3) left click the stack to pick up the whole thing, and move it to your main inventory.
4) right click the moved stack. (observe that you can pick up half the stack this way).

Relatedly, the 'scroll over an item stack to push/pull 1 item at a time' feature from Mouse Tweaks does not work either. I suspect this is a holdover from the Card Holder being designed to stack otherwise-unstackable items, and thus it isn't behaving quite as expected for these mods. 

### Expected behaviour

Itemstacks should be split when right-clicked on.

**Comment by Direwolf20-MC** [comment]
This is by design - the card holder is a little weird because its allowing you to stack items you wouldn't normally be allowed to stack. Such as the item/fluid/etc cards. 

Previously right click allowed you to edit the cards, but that functionality got lost on one of the upgrades, i'll look at bringing it back :)
