### ISSUE TITLE
Feature Suggestion: Laser lines show when holding the wrench

### ISSUE THREAD

**Issue by soulbreather** [Direwolf20-MC/LaserIO#26]
### Describe the feature you'd like to have added

The laser lines will only show up in the world if the player holds the wrench.

### Additional information

I find it annoying at times that you can see the lasers go through walls and machines all the time, it would make sense to only draw the lasers when the player is connecting nodes. Or maybe this feature could be made a toggle on the wrench or in the config, so either the laser lines are always drawn or only drawn when holding the wrench.

**Comment by dasshark** [comment]
I too would like to request this.  Similar to how AE2 hides facades while holding the network tool.

**Comment by PianoHallvard** [comment]
Also it would be cool, if you were holding the wrench, if it would show nodes through blocks. Like a little outline, maybe with the connections too

**Comment by linuxgarou** [comment]
Another option is to show all nodes (and relays, and laser connections) in a network when you left-click the laser wrench on a node in that network.

**Comment by Direwolf20-MC** [comment]
Added to the wishlist of features :)
