### ISSUE TITLE
All Features on all Versions?

### ISSUE THREAD

**Issue by TheUntamed** [Direwolf20-MC/LaserIO#260]
### Describe the feature you'd like to have added

Hello,
It's a question and potential Feature Request Combined:
Do all features of the mod (Laser Nodes with Item, Fluid, Energy, ..) cards exist for all minecraft versions (1.18; 1.19; 1.20)?
Or do 1.18 and 1.19 only contain parts of it?
If the later I would request a backport of the features to those version.

**Comment by Direwolf20-MC** [comment]
Most features are on older versions. Newer ones have some newer features.
