### ISSUE TITLE
Default item transfer amount should be 8

### ISSUE THREAD

**Issue by iammael** [Direwolf20-MC/LaserIO#261]
### Describe the feature you'd like to have added

I think the default item transfer should be 8 (hence title). Here's my reasoning:

There are actually very few setups where we precisely want 1 item per second. It is good to have as a possibility, but most of the times, 1 i/s ends up being too slow and we have to go through the GUI to change it to 8 (multiply by the number of node connections).

Since, as far as I understand, it doesn't change anything performance-wise to move 1 item or 8, plus the fact that a node already has the capacity to transfer 8 i/s without overclocking anyway, I think it would make sense for the transfer amount to be 8 by default as it fits most setups (at least early/mid game).

It would even prevent players from unnecessarily overclocking nodes by setting the amount and speed to the max just because they can (thus affecting performance now), for setups that would run just fine with 8 i/s.

**Comment by Direwolf20-MC** [comment]
I'll consider making this change in 1.22 - if I made it now, it would set everyone's '1' card to an '8' potentially breaking existing builds
