### ISSUE TITLE
Laserio GUI tabs auto-detecting blocks attached

### ISSUE THREAD

**Issue by Mitchm0nstr** [Direwolf20-MC/LaserIO#262]
### Describe the feature you'd like to have added

I think it would be nice if the options for N,S,E,W,U,D should be autoxdetected based on the blocks it’s next to. I obviously don’t know how to code, or would speak more in-depth, but like how Enderio had a physical connection that automatically attached to the blocks it’s near. The wrench could be used to add a slot for if the tab isn’t detecting.

### Additional information

The laser node could still look the same, but the gui tabs shouldn’t all show 100% of the time. This might helps with if you only have it attached to two blocks you’d be able to easily tell which block is which.

**Comment by Direwolf20-MC** [comment]
It’s a neat idea but honestly my preference is to keep it the way it is. Thanks for the idea though!
