### ISSUE TITLE
Sped Up Particles

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [Direwolf20-MC/LaserIO#267]
### LaserIO version

1.9.1

### Minecraft Version

1.21

### Forge Version

Neoforge 21.0.25

### Modpack & Version

Craftoria 0.0.5

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

When transferring a lot of items at once using LaserIO, if the nodes are within render distance, particles from block breaking are sped up. 

### Steps to reproduce

setup nodes to transfer a LOT of items at once.
break and place blocks.

### Expected behaviour

not sped up particles 

### Screenshots

[Evidence](https://www.youtube.com/live/ByqyUY4QXQ0?si=eTgDALVCibXfoaPW&t=17101) at the time stamp it's set to.

**Comment by Direwolf20-MC** [comment]
It’s likely not speeding up the particles. There’s a limit to the number of particles you can have on screen. My new ones are probably killing the breaking ones. 

I’ll look into lowering the particle count at higher speeds :)

**Comment by Kazuhiko-Gushiken** [comment]
@Direwolf20-MC A little extra I just noticed, with 5 maxed out item transfers, it generates about 16,400 particles. 
Before
![image](https://github.com/Direwolf20-MC/LaserIO/assets/132615999/692a8571-dceb-4591-9090-e78632d00166)

After
![image](https://github.com/Direwolf20-MC/LaserIO/assets/132615999/15f8f123-90ce-43b9-86a1-ca32b43b49f2)

**Comment by Direwolf20-MC** [comment]
Just tested with 10 cards going, and am sitting at around 8,000ish particles on my system. Not sure how you got 16k with only 5 cards. I think what I'll do to mitigate this is add a 'no particles' option to the node, to skip particle rendering on that node.

**Comment by Direwolf20-MC** [comment]
https://github.com/Direwolf20-MC/LaserIO/commit/46729d58bf4a7864be5e56f7ece000b7f62752ea
