### ISSUE TITLE
Other transport mods pulling Insert/extract cards from node.

### ISSUE THREAD

**Issue by CLASIX** [Direwolf20-MC/LaserIO#27]
### LaserIO version

1.0.3

### Minecraft Version

1.18.2

### Forge Version

40.1.25

### Modpack & Version

DW20 1.18

### Do you have optifine installed?

Yes

### Describe the issue

Im not even sure if this is intended or not. I imagine it is not. Also, not even sure if this is a dire problem or just how the mods interact and cant be fixed. So please excuse my ignorance. Basically. Other transport mods (Tesseract, Pipez etc) will pull the cards from the node.

### Steps to reproduce

1. Place laser down and configure it to extract on correct side
2. place tesseract down and configure laser to insert on correct side
3. be sad when the tesseract pulls the insert card

Also, thank you for the mod Dire. It is really well thought out and for the most part behaves exactly as you would expect it to. We were definitely missing a highly customizable transport mod, and LaserIO really brings that to the table and then some.   

### Expected behaviour

Card stays in node

**Comment by Direwolf20-MC** [comment]
It’s intended that you can remove cards with pipes and other mods. Unless I’m misunderstanding your concern :). The node is an inventory like any other so you can extract from it.

**Comment by CLASIX** [comment]
Okay cool! Just making sure it was not a bug. Now that I think about it a little more, this can be remedied pretty easily with a blacklist filter on the pipe or other transport mod, to not accept the card. So really, the way you have it is more beneficial because it can be used both ways, rather than just always having it not be able to be extracted. Thanks dire!

**Comment by WyFryMU** [comment]
> It’s intended that you can remove cards with pipes and other mods. Unless I’m misunderstanding your concern :). The node is an inventory like any other so you can extract from it.

When trying to insert items into a tesseract from a laser node, the tesseract takes the Insert item card from the laser node when I believe it shouldn't be because then the node can't insert into the tesseract

**Comment by Direwolf20-MC** [comment]
> > It’s intended that you can remove cards with pipes and other mods. Unless I’m misunderstanding your concern :). The node is an inventory like any other so you can extract from it.
> 
> When trying to insert items into a tesseract from a laser node, the tesseract takes the Insert item card from the laser node when I believe it shouldn't be because then the node can't insert into the tesseract

Is the tesseract  set to auto pull from adjacent inventory ?

**Comment by WyFryMU** [comment]
> > > It’s intended that you can remove cards with pipes and other mods. Unless I’m misunderstanding your concern :). The node is an inventory like any other so you can extract from it.
> > 
> > 
> > When trying to insert items into a tesseract from a laser node, the tesseract takes the Insert item card from the laser node when I believe it shouldn't be because then the node can't insert into the tesseract
> 
> Is the tesseract set to auto pull from adjacent inventory ?

Oh y'know, that's it. Thank you!
