### ISSUE TITLE
Unable to connect nodes together with wrench

### ISSUE THREAD

**Issue by dretheroman** [Direwolf20-MC/LaserIO#270]
### LaserIO version

1.6.8

### Minecraft Version

1.20.1

### (Neo)Forge Version

47.2.20

### Modpack & Version

ATM9 To The Sky - 1.0.6

### Do you have optifine installed?

No

### Describe the issue

When trying to bind two node together with wrench nothing happens. It's possible I'm overlooking something.

### Steps to reproduce

1. Open ATM9 To the Sky.
2. Place two nodes down.
3. Check alpha on on lasers.
4. Using Laserio  wrench shift-click first node then right click second node.
5.  Shows no connection on my end. 
Here is an example https://streamable.com/8h8co2

### Expected behaviour

Expectation is nodes to be able to connect with Laserio wrench.

**Comment by Direwolf20-MC** [comment]
Can you confirm if this is rendering issue only (lasers not drawn but nodes still work) or not? I haven’t touched 1.20.1 in a while so I can’t imagine this would be anything other than another mod causing an issue.

**Comment by dretheroman** [comment]
Hey Dire! So now that you mention it, I did a test and it does seem to be a rendering issue. I used 2 nodes to transfer from chest to chest and it worked. 

Just as a test I turned off the complimentary pack shaders.

Low and behold. 
![Nodes connecting](https://github.com/Direwolf20-MC/LaserIO/assets/150714162/4bc8f1fb-6c2d-4ec0-9c8c-4ef92aa6cdb0)

**Comment by Direwolf20-MC** [comment]
Shaders gonna get cha :). I’ll see if I can figure out how to support them.
