### ISSUE TITLE
Chemical Card Node interaction with Mek causes crash on server

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [Direwolf20-MC/LaserIO#271]
### LaserIO version

1.9.1

### Minecraft Version

1.21

### (Neo)Forge Version

Neoforge 21.0.42

### Modpack & Version

Craftoria 0.0.10

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

Chemical Card Node interaction with Mek causes crash on server

### Steps to reproduce

1. open mc
2. open world
3. place down mek machine
4. node on top
5. chemical card down
6. crash

### Expected behaviour

not crash

### Log files

https://gist.github.com/Kazuhiko-Gushiken/758a871fdce11cc09cbf5dd332dc4e77

**Comment by WhitePhant0m** [comment]
Here's a recording of me replicating it in SP
https://youtu.be/nYylNpCKQiU

**Comment by Direwolf20-MC** [comment]
Thanks for the video that actually helped quite a bit :).  Should be resolved in the next version
