### ISSUE TITLE
[1.21 patchouli-snapshot] Modes.json won't build a usable patchouli book in 1.21

### ISSUE THREAD

**Issue by Wolf1098** [Direwolf20-MC/LaserIO#272]
### LaserIO version

1.9.1

### Minecraft Version

1.21

### (Neo)Forge Version

21.0.24-beta

### Modpack & Version

ATM10

### Do you have optifine installed?

No

### Describe the issue

modes.json causes empty book

### Steps to reproduce

with patchouli from @MrBysco 's 1.21 fork, targeting neoforge 21.0.24 instead of 21.0.42, might be the issue there???? 

### Expected behaviour

Patchouli should be able to load

### **Bugged screenshot**
![image](https://github.com/Direwolf20-MC/LaserIO/assets/11269584/f896b9b5-dbb5-4f6f-8ac4-ab074e5f36fb)

![image](https://github.com/Direwolf20-MC/LaserIO/assets/11269584/f8f2833f-d2ff-432a-9a60-7e6db8b61e81)
### _**bugged partial fix**_
![image](https://github.com/Direwolf20-MC/LaserIO/assets/11269584/9ffc4c66-ebe6-4ffc-8da4-779f733b551b)
<img width="1280" alt="image" src="https://github.com/Direwolf20-MC/LaserIO/assets/11269584/9f4c7097-1baf-4a41-8f3a-24b8469140da">

### _**Expected state**_
![image](https://github.com/Direwolf20-MC/LaserIO/assets/11269584/fdede76b-d4f7-4554-8917-056e87b60575)

### Log files

[latest.log](https://github.com/user-attachments/files/16062342/latest.log)
[debug.log](https://github.com/user-attachments/files/16062343/debug.log)
[excerpt gist](https://gist.github.com/Wolf1098/5c2b0a0cc53ca5776289d886d249b8fb)

### Additional information

adding #1 to the modes.json item: field gets the book to generate, but the modes page for the cards show the wrong mode in the nbt data... modes.json I used

```
 {
  "name": "Modes",
  "sortnum": 1,
  "category": "laserio:mechanics",
  "icon": "laserio:textures/gui/buttons/modestocker.png",
  "pages": [
    {
      "type": "patchouli:text",
      "text": "Modes determine what a card fundamentally does. The following pages define each mode type currently available.$(br2)Each type of card (Item/Fluid/Energy) supports the the following three modes. Item cards are used as an example.$(br2)Redstone cards will support a different set of modes."
    },
    {
      "type": "patchouli:spotlight",
      "item": "laserio:card_item{channel:0b,exact:0b,inv:{Items:[],Size:2},itemextractamt:1b,itemextractspeed:20,mode:0b,priority:0s,regulate:0b,roundRobin:0,sneaky:-1b}",
      "text": "Insert Mode cards are a validate destination for objects being extracted by Extract Mode cards.$(br2)Stock mode cards will attempt to pull from Insert Mode cards."
    },
    {
      "type": "patchouli:spotlight",
      "item": "laserio:card_item#1{channel:0b,exact:0b,inv:{Items:[],Size:2},itemextractamt:1b,itemextractspeed:20,mode:1b,priority:0s,regulate:0b,roundRobin:0,sneaky:-1b}",
      "text": "Extract Mode cards attempt to remove objects from their adjacent block. Items, for example, will be removed from an adjacent chest and sent to an insert card."
    },
    {
      "type": "patchouli:spotlight",
      "item": "laserio:card_item#1{channel:0b,exact:0b,inv:{Items:[],Size:2},itemextractamt:1b,itemextractspeed:20,mode:2b,priority:0s,regulate:0b,roundRobin:0,sneaky:-1b}",
      "text": "Stock Mode cards attempt to find the designated items in their filter, and pull them from other Insert Nodes in the same network.$(br2)Stock mode cards require a filter set to Allow."
    },
    {
      "type": "patchouli:spotlight",
      "item": "laserio:card_item#1{channel:0b,exact:0b,inv:{Items:[],Size:2},itemextractamt:1b,itemextractspeed:20,mode:3b,priority:0s,regulate:0b,roundRobin:0,sneaky:-1b}",
      "text": "Sensor cards do not move objects around, but instead look at an adjacent inventory, and will emit a redstone signal on the redstone channel if the inventory matches the filter.$(br2)Sensor mode cards require a filter."
    }
  ]
}
```

**Comment by Wolf1098** [comment]
I have personally have forked a copy of patchouli that has a prerelease 1.21-snapshot jar that is a copy of what i was using to test the book

**Comment by Mrbysco** [comment]
You're reporting an issue for an unfinished port to 1.21 that can change at any time?
