### ISSUE TITLE
Reset Basic FIlter can stack with newly crafted ones

### ISSUE THREAD

**Issue by ChengYi0224** [Direwolf20-MC/LaserIO#274]
### LaserIO version

1.6.8

### Minecraft Version

1.20.1

### (Neo)Forge Version

47.2.20

### Modpack & Version

all the mods 9 - to the sky 1.0.5

### Do you have optifine installed?

No

### Describe the issue

When the basic filter is crafted to reset the tags, it can't stack with those newly crafted ones. Maybe their tags are different

### Steps to reproduce

1. Craft some basic filters
2. Re-craft those basic filters
3. Try to stack them with other newly crafted basic filters

### Expected behaviour

Those re-crafted basic filters and newly crafted ones should be able to stack together

**Comment by Direwolf20-MC** [comment]
This is resolved in newer versions of Laserio
