### ISSUE TITLE
Ability to add notes to node

### ISSUE THREAD

**Issue by PrakashW94** [Direwolf20-MC/LaserIO#275]
### Describe the feature you'd like to have added

Once networks start getting more complex, it can become more difficult to debug issues and work out what's happening in the network. It would be nice if we had the ability to add notes to a side of a node, perhaps inserting some paper would enable an open text field or something similar where the user could add their own documentation.

Worth mentioning, the original idea I had was some way to draw a network diagram showing what goes where on what channels etc but I'm not sure how complex that would be to implement, adding notes to a node feels like a simpler addition that could be still be super useful.

**Comment by Direwolf20-MC** [comment]
Adding some kind of way to see what all is on a network is definitely an idea i have, still figuring it out though :)
