### ISSUE TITLE
Chemical card doesn't have a nbt clear recipe.

### ISSUE THREAD

**Issue by WhitePhant0m** [Direwolf20-MC/LaserIO#277]
### LaserIO version

1.9.1

### Minecraft Version

1.21

### (Neo)Forge Version

21.0.86

### Do you have optifine installed?

No

### Describe the issue

Chemical card doesn't have a nbt clear recipe.

### Steps to reproduce

Try to clear nbt of chemical card with the same recipe as other cards, notice that you can't.

### Expected behaviour

Chemical card having a nbt clear recipe.

**Comment by Direwolf20-MC** [comment]
Resolved in the next version - thanks! :)
