### ISSUE TITLE
Run inventory interaction ugprades keybind from sophisticated storage causes crash on some modded blocks

### ISSUE THREAD

**Issue by Saereth** [Direwolf20-MC/LaserIO#280]
### LaserIO version

laserio-1.9.1.jar

### Minecraft Version

1.20.4

### (Neo)Forge Version

20.4.237

### Modpack & Version

FTB Neotech 1.5

### Do you have optifine installed?

Yes

### Describe the issue

Run inventory interaction ugprades keybind from sophisticated storage causes crash on some modded blocks

### Steps to reproduce

Neoforge 1.20.4 - 20.4.237
sophisticatedstorage-1.20.4-0.10.24.802
sophisticatedcore-1.20.4-0.6.21.608

Steps to reproduce:
put down a laser node from LaserIO and while lookint at it press the key bind for inventory interaction upgrade resulting in a crash

### Expected behaviour

Not crashing

### Log files

Crash log:
https://mclo.gs/f4fQVYQ

### Additional information

I originally reported this as a sophisticated storage issue but p3pper referred me back to you stating the issue is on your end
https://github.com/P3pp3rF1y/SophisticatedStorage/issues/447

**Comment by Direwolf20-MC** [comment]
This is resolved in newer versions - sorry for the inconvenience!

https://github.com/Direwolf20-MC/LaserIO/commit/bca84c3a73a81cca990426c4b937cf451e30519a
