### ISSUE TITLE
Fluid transfer causing everyone on the server to be disconnected

### ISSUE THREAD

**Issue by WhitePhant0m** [Direwolf20-MC/LaserIO#281]
### LaserIO version

1.9.1

### Minecraft Version

1.21

### (Neo)Forge Version

21.0.139

### Modpack & Version

Craftoria v0.5.0

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

Fluid transfer causing everyone on the server to be disconnected

### Steps to reproduce

Not sure about the exacts, but I was trying to transfer mekanisms liquid lithium from a thermal evap tower into a rotary condensator, after which everyone kept getting disconnected as long as my chunks were loaded.

If it's not replicatable with this info, I can try to record replicating this later, if needed.

### Expected behaviour

No DC

### Log files

[The error](https://mclo.gs/VF9leqL)

**Comment by Direwolf20-MC** [comment]
I couldn't reproduce it but i added some code to help prevent it - hopefully ;)
