### ISSUE TITLE
game crashes on login

### ISSUE THREAD

**Issue by Destral1** [Direwolf20-MC/LaserIO#282]
### LaserIO version

1.9.4

### Minecraft Version

1.21

### (Neo)Forge Version

21.0.148

### Modpack & Version

All the Mods 10 10-0.24

### Do you have optifine installed?

No

### Describe the issue

I try to open my world. game crashes

### Steps to reproduce

1. open my world
2. crash

### Expected behaviour

not crashing

### Log files

[crash-2024-08-03_03.31.47-server.txt](https://github.com/user-attachments/files/16478735/crash-2024-08-03_03.31.47-server.txt)
[debug.log](https://github.com/user-attachments/files/16478737/debug.log)
[latest.log](https://github.com/user-attachments/files/16478741/latest.log)

**Comment by Destral1** [comment]
I fixed my world by editing the forge config to delete ticking blockentities.

**Comment by Direwolf20-MC** [comment]
Which block entity from Modern Industrialization were you pulling items out of using stocker mode?

**Comment by Direwolf20-MC** [comment]
I added a check to prevent this crash, but I have no idea how it happened :)

**Comment by Destral1** [comment]
so my setup looks like this:
![image](https://github.com/user-attachments/assets/18cdd42f-48bc-411a-968a-4d35a0a562bc)
every machine on the wall has a laser node with these cards
![image](https://github.com/user-attachments/assets/fbbe4522-264d-4578-be03-e92906b9443c)
and there's a buffer inventory like this:
![image](https://github.com/user-attachments/assets/0ef433be-280c-40ae-b9d7-1b2a16a9e381)
![image](https://github.com/user-attachments/assets/ce1bbc38-0b4a-4670-ae9d-9dea276e8203)

does that help?

**Comment by Destral1** [comment]
the specific node that broke was in the top row, second form the left

**Comment by Destral1** [comment]
there's an electric wiremill on top and an assembler on bottom
