### ISSUE TITLE
Crash with mod filter

### ISSUE THREAD

**Issue by NJM1564** [Direwolf20-MC/LaserIO#284]
### LaserIO version

1.9.4

### Minecraft Version

1.21

### (Neo)Forge Version

21.0.151

### Modpack & Version

All the mods 10 10-0.27

### Do you have optifine installed?

No

### Describe the issue

Filtering mod crashes when filtering travaalers backpacks

### Steps to reproduce

I did some checking and it also bit the big one when I tried shulker boxes.
Looks like it's probably do to not liking containers.

It also deletes the container item. I'd recommend immediately blacklisting anything that is a container them as a stop gap to prevent losing any important items if they do not know how to recover them from backups. Unless you can fix the issue properly quickly.

### Expected behaviour

Disrecuard contaner data.

**Comment by Direwolf20-MC** [comment]
This likely would have crashed with any container like you said :) and with any filter even! 

Should be fixed now, thanks for the report!
