### ISSUE TITLE
game breaks when rendering modern industrialization fluids (I think)

### ISSUE THREAD

**Issue by Destral1** [Direwolf20-MC/LaserIO#287]
### LaserIO version

1.9.5

### Minecraft Version

1.21

### (Neo)Forge Version

21.0.151

### Modpack & Version

All the Mods 10 10-0.27

### Do you have optifine installed?

No

### Describe the issue

Was using laserio to fill a reactor with water and take out steam, game crashed when the steam tank filled

### Steps to reproduce

1. use lasers to stock MI fluids
2. error

### Expected behaviour

no error

### Screenshots

![image](https://github.com/user-attachments/assets/d98e10ca-00c4-4532-ae11-9a43b1c8dde4)

### Log files

[debug.log](https://github.com/user-attachments/files/16511439/debug.log)
[latest.log](https://github.com/user-attachments/files/16511444/latest.log)

### Additional information

does not happen when particles are disabled

**Comment by Direwolf20-MC** [comment]
Are you sure you were on 1.9.5 when this happened? I fixed this bug in 1.9.5, so if you were maybe in 1.9.4 it would make more sense.  If you were definitely in 1.9.5 i'll have to figure out what i missed :)

**Comment by Direwolf20-MC** [comment]
Nevermind, I just figured out what I missed :) - Should be fixed in 1.9.7
