### ISSUE TITLE
Add ability to filter based on specific value of a NBT tag

### ISSUE THREAD

**Issue by ThePhoenixIO** [Direwolf20-MC/LaserIO#288]
### Describe the feature you'd like to have added

It would be great to add a filter (or option to the NBT filter) to allow the filter to compare the value of a NBT tag on an item and only insert or extract by that single tag. In other words its not as strict as "match NBT" but is more strict than the current NBT filter. 

### Additional information

For example when working with Productive bees, it would be great to be able to selectively extract gen extracts that have the specific "productivebees_gene_attribute" NBT value of "productivebees:draconic" to one inventory and all others to another.

**Comment by Direwolf20-MC** [comment]
I would definitely like to do this, but its way more complex than you might think :).  Its on my list to try to find a way though, so i'll close this for now.
