### ISSUE TITLE
Inventory deleted while using cards/filters

### ISSUE THREAD

**Issue by DotoreZee** [Direwolf20-MC/LaserIO#289]
### LaserIO version

1.6.8

### Minecraft Version

1.20.1

### (Neo)Forge Version

47.2.20

### Modpack & Version

All the Mods 9 - To the Sky (1.1.0)

### Do you have optifine installed?

No

### Describe the issue

Inventory gets deleted while configuring the cards or filters, inside the node or in hand if you sort your inventory

### Steps to reproduce

1. Open the card/filter to configure it (while in node or in hand)
2. Sort inventory by pressing middle mouse or the sorting button on the right side of the inventory
3. The whole inventory gets deleted (even the card itself if it's in your hand)

### Expected behaviour

Sorting inventory

**Comment by Direwolf20-MC** [comment]
This shouldn't happen in 1.21 - but let me know if it does :D
