### ISSUE TITLE
Invalid character in Tag filter causing crash

### ISSUE THREAD

**Issue by ldet** [Direwolf20-MC/LaserIO#29]
### LaserIO version

1.0.3

### Minecraft Version

1.18.2

### Forge Version

40.1.31

### Modpack & Version

ATM 7 0.4.7

### Do you have optifine installed?

No

### Describe the issue

Putting a "*" in tag filter text input crashes the client. The dedicated server did not crash

### Steps to reproduce

1. Try to do a wildcard in Tag filter: forge:raw_ores/*
2. Crash

### Expected behaviour

not crashing

### Log files

https://pastebin.com/raw/9K7yF8VD

**Comment by i2smrt4u** [comment]
I also achieved this by attempting to use the JEI search tag "#attack"

**Comment by Direwolf20-MC** [comment]
Fixed :)

https://github.com/Direwolf20-MC/LaserIO/commit/1227843c0991df1a42f6754353d9ee49bdab0490
