### ISSUE TITLE
Energy not transferring to mekanism machines

### ISSUE THREAD

**Issue by Dvginkel** [Direwolf20-MC/LaserIO#290]
### LaserIO version

1.9.6

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.0.163

### Modpack & Version

ATM10 on a server

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

When trying to use laserio with energy card to get power to mekanism machine, energy isn't transffered

### Steps to reproduce

1. Place Laser Node next to Basic Universal Cable from Mekanism
2. Place an Energy Card set to insert into the Laser Node
3. Place an Energy Card set to extract into the Laser Node configure to insert into mekanism machine

### Expected behaviour

Expected behaviour is that energy is being sent to the machine

### Screenshots

The problem / issue was noticed on a server, and thought I'd test it in singleplayer aswell but didnt work either. This screenshot is taken from an creative world.
![image](https://github.com/user-attachments/assets/fafe68b0-a52d-4383-b51a-f13f113ff1ab)

These screenshots are from the card configuration in the laser node, extracting from the Basic universal Cable:
![image](https://github.com/user-attachments/assets/4ee08fc2-c942-4782-96c8-cc831f35d537)
Energy card settings / configuration:
![image](https://github.com/user-attachments/assets/e2c65cd6-43ad-4809-bf23-b3aa698fdd16)

These screenshots are for inserting energy into the mekanism machine
![image](https://github.com/user-attachments/assets/c27f6d36-1c94-48b0-8b9a-197e3046ced3)
Energy card settings:
![image](https://github.com/user-attachments/assets/6553018a-4919-4e34-b035-f665a6952ff4)

### Log files

No errors or entries in either debug.log or latest.log found regarding laserio and/or mekanism. 

If you need either or both logs, let me know and I'll grab them from the server and add them :-)

**Comment by Direwolf20-MC** [comment]
Try connecting directly to the cube, rather than the energy pipe.  Or try breaking the pipe and replacing, see if it "connects" to the node. 

I don't think that'll be something I can fix, unfortunately :)

**Comment by Dvginkel** [comment]
> Try connecting directly to the cube, rather than the energy pipe. Or try breaking the pipe and replacing, see if it "connects" to the node.
> 
> I don't think that'll be something I can fix, unfortunately :)

Attaching directly to the cube indeed works, as I found out by accident. I forgot to update this report with that info. But it works so I'm happy :-)
