### ISSUE TITLE
#281 but with chemical cards

### ISSUE THREAD

**Issue by WhitePhant0m** [Direwolf20-MC/LaserIO#291]
### LaserIO version

1.9.6

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.2

### Modpack & Version

[Craftoria v0.7.0](https://www.curseforge.com/minecraft/modpacks/craftoria/files/5611431)

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

Chemical transfer causing everyone on the server to be disconnected

### Steps to reproduce

As with #281, not sure about exacts, was transferring chemicals from machines to other machines, until the disconnects started to happen.

### Expected behaviour

No DC

### Log files

[Related error](https://mclo.gs/TkUrxJA#L35)

**Comment by Direwolf20-MC** [comment]
Weird. I thought I handled this for chemicals the same way I did fluids.  I’ll double check :)

**Comment by Direwolf20-MC** [comment]
Should be fixed in 1.9.7 - let me know if not :)

**Comment by WhitePhant0m** [comment]
Seems to have fixed it, at least the setup I had is no longer crashing 👍
