### ISSUE TITLE
Update Patchouli's book cards entries

### ISSUE THREAD

**Issue by rischiopoco** [Direwolf20-MC/LaserIO#292]
Starting from 1.20.4 most of the cards' entries in the book are not up to date because:

- Each card's entry contrains how much the card transfers over 1 tick with 0-4 Overclockers, tho this value can now be configured using a config file so the book won't always be consistent;
- Energy cards are maxed by default now but in the book it says that they can be upgraded using Overclockers;
- Fluid cards' default transfer rates with and without Overclockers have been changed since 1.20.1 but the book entry isn't up to date;
- There isn't an entry for Chemical Cards.

**Comment by Direwolf20-MC** [comment]
All updated - thank you! :)
