### ISSUE TITLE
Needs an update to work with latest Mekasnim, due to breaking changes in their Chemical API

### ISSUE THREAD

**Issue by WhitePhant0m** [Direwolf20-MC/LaserIO#294]
Just wanting to let you know, in-case you weren't aware. Also making this issue to track it myself.

https://github.com/mekanism/Mekanism/commit/b74b68b1d108fc9335f6748725b6c5a50ccea801
1.9.9 and lower have also been marked as incompatible by Mekanism.

**Comment by Direwolf20-MC** [comment]
Thanks - Just started on this tonight, and I think its ready :)
