### ISSUE TITLE
[Bug] Consistent Crash Error when opening Laser IO Data filter configuration screen

### ISSUE THREAD

**Issue by Slaymeister** [Direwolf20-MC/LaserIO#298]
### LaserIO version

1.9.10

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.54

### Modpack & Version

Vanilla+LaserIO only

### Do you have optifine installed?

No

### Describe the issue

When you right click the data filter, the user disconnects. I am generally playing with ATM10, but this report and the associated logs have been pared down to just vanilla and LaserIO in a clean install, which successfully repros the issue.

### Steps to reproduce

Install Vanilla with NeoForge, add in LaserIO
Launch and give laserio:filter_nbt
Right click the air with the card to cause disconnect.

### Expected behaviour

Configuration screen? Just learning this mod. Something not a forced disconnect.

### Screenshots

![image](https://github.com/user-attachments/assets/2b0975c4-b35e-49e2-bafa-25d9a7c4756d)

### Log files

https://1drv.ms/u/s!Aj3i3s_bJkfxodFaIjT-RYZXm14PTg?e=ozMrLt
Sharing link will expire in 30 days.

### Additional information

I am playing directly on my client, no server attachment. The failure is seen as a client disconnect by Minecraft, so it does not generate a crash log. Full log is linked above. Disconnect is listed in the log as 

[Render thread/WARN] [net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl/]: Client disconnected with reason: Failed to open a screen with advanced data: java.lang.IndexOutOfBoundsException: readerIndex(5) + length(1) exceeds writerIndex(5): UnpooledHeapByteBuf(ridx: 5, widx: 5, cap: 5/5)

**Comment by Direwolf20-MC** [comment]
Fixed - thanks!

**Comment by Slaymeister** [comment]
Great! Thank you! Is this going into the curseforge publishing process soon?

**Comment by Direwolf20-MC** [comment]
Yup submitted as 1.9.11 should be approved soon if not already

**Comment by Slaymeister** [comment]
It's there!  Thanks again!
