### ISSUE TITLE
Suggestion: ability to transfer fluid by quantity

### ISSUE THREAD

**Issue by Hobbit44** [Direwolf20-MC/LaserIO#3]
So with the direwolf20 1.18 pack the tinkers mod has a 1.3x ore multiplier so you end up with extra nuggets.

The suggestion would be to have a card that transfers only when  x amount is available. So you could have 288mb for an ingot, 1000mb for a bucket. But that means that you could have multiple sources or tanks of molten metal waiting for transfer and it would only fill when appropriate.

**Comment by Direwolf20-MC** [comment]
This is a planned feature, it will be the 'exact' mode that items currently have, just for liquids.
