### ISSUE TITLE
Specific order of insertion filter

### ISSUE THREAD

**Issue by edotenseilove** [Direwolf20-MC/LaserIO#30]
### Describe the feature you'd like to have added

Hello I would like to suggest an adition of a specific order of insertion upgrade(with count) filter because I think that feature is not that common with most of the item transportation mods and yet would be much appriciated with some mods (maybe it would check if the first item of a filter is in tageted inventory and if yes move onto next one and so no)

Have a great day.

**Comment by Direwolf20-MC** [comment]
The stocking module should work this way - can you try!

**Comment by Direwolf20-MC** [comment]
Hrm, sounds like an inventory match module....I think this should exist as a different filter - I'll consider it but no promises :). I'll add it to my internal tracker as optional.
