### ISSUE TITLE
Suggestion: Connected laser corresponds to card slot.

### ISSUE THREAD

**Issue by Bucket777** [Direwolf20-MC/LaserIO#31]
Sorry I haven't test this, only been watching your lets play and Mod spot light...

Just a small visual tweak. 
I do not like how the laser connects from the top left coner first.

Can you please make it so that when the card is inserted in the middle of the 3x3 grid the laser also renders from the middle.
Same with the other slots, if a card is inserted top left, the laser shows top left, etc.

This wil also help with seeing channel colours in position of the card.

**Comment by Direwolf20-MC** [comment]
That’s how it works already. Are you saying it doesn’t work that way?

**Comment by Bucket777** [comment]
Thanks. It does work that way.

May I then ask that when inserting the card via shift-click and right-click that it goes into the center slot first?

Great work thus far.

**Comment by Direwolf20-MC** [comment]
Thanks :) but not planned for that right now.
