### ISSUE TITLE
Card Holder Trys to pull cards even when its full

### ISSUE THREAD

**Issue by JCMCGroup-Joshua** [Direwolf20-MC/LaserIO#318]
### LaserIO version

1.6.8

### Minecraft Version

1.20.1

### (Neo)Forge Version

Forge - 47.3.0

### Do you have optifine installed?

No

### Describe the issue

the card holder will try to pull cards from the players inventory even when the card holder has no free slots causing the cards to disapear visually from the inventory and will sometimes flash 

### Steps to reproduce

Try to collect multiple different cards with different configs, and try to collect more cards than the holder can hold

### Expected behaviour

the card holder will stop the trying to pull the cards

### Screenshots

![2024-11-24_00 30 55](https://github.com/user-attachments/assets/8a9cdc39-4bc1-49d2-a348-8111def6793c)
![2024-11-24_00 30 29](https://github.com/user-attachments/assets/0699ff91-8756-4909-94d3-88d66a7fa0b6)
![2024-11-24_00 30 34](https://github.com/user-attachments/assets/61b7c024-ecd2-4b2d-b947-1dcab6bdbf95)
![2024-11-24_00 30 34_4](https://github.com/user-attachments/assets/6c093212-9b6d-4d2e-a4c8-a134258cbe00)
![2024-11-24_00 30 33](https://github.com/user-attachments/assets/a468b4ef-babe-49e0-9b99-5afb42219e18)

### Additional information

I tried to get a screenshot that showed the desync but was unable to.

**Comment by Direwolf20-MC** [comment]
This *shouldn't* happen, but can you tell me if it is still in 1.21?
