### ISSUE TITLE
Tiered Energy Cards (as a config option for packdevs)

### ISSUE THREAD

**Issue by ThePansmith** [Direwolf20-MC/LaserIO#319]
### Describe the feature you'd like to have added

A config for LaserIO that lets you replace the "1 energy card + overclockers" system with tiered energy cards, which cannot be overclocked. 

This would primarily see use for packdevs, as they could define a list of energy cards, then give them recipes via KubeJS/etc.

### Additional information

I imagine syntax would only need to be `(name, rf/t)`, so `("conductive", 512)`, as an example.

Autogenerated textures wouldn't be needed, as packdevs can easily set those.

**Comment by Direwolf20-MC** [comment]
I put a lot of effort into removing that :) sorry.
