### ISSUE TITLE
Card Overclocker Voiding Issue

### ISSUE THREAD

**Issue by Garrus2** [Direwolf20-MC/LaserIO#32]
### LaserIO version

1.0.7

### Minecraft Version

1.18.2

### Forge Version

40.1.47

### Modpack & Version

Direwolf20 1.18 v1.4.0

### Do you have optifine installed?

No

### Describe the issue

The card overclockers get voided instead of staying in the card inventory or going to the hotbar when you shift click the card overclockers out of the item cards with a full inventory (tried with both insert and extract modes).  

### Steps to reproduce

1. Place a item card inside a node 
2. Place card overclockers does not matter number (I used 3)
3. Fill inventory with junk (does not matter what) Hotbar can be filled, empty, or one shot left does not matter
4. Shift click card overclockers into inventory and watch as they are voided

### Expected behaviour

I expect the card overclockers to stay in the inventory or on to open hotbar slot.

### Additional information

My hotbar had an open slot but it still voided them so, I think it is an issue with where the cards are being sent from a shift click because the node overclockers don't have the issue and can go into your hotbar. I tried with an open slot in the inventory and it worked fine. Also, tested with both survival and creative same result.

**Comment by Direwolf20-MC** [comment]
That’s absolutely possible :) I made a mess of the shift click code when I added the card holder. Will investigate.

**Comment by Direwolf20-MC** [comment]
Found the bug :) Should be fixed!
