### ISSUE TITLE
Stocking Void issue with 2+ items in filter

### ISSUE THREAD

**Issue by gman4161** [Direwolf20-MC/LaserIO#33]
### LaserIO version

1.0.7

### Minecraft Version

1.18.2

### Modpack & Version

Direwolf 20 1.18.2 1.4

### Do you have optifine installed?

No

### Describe the issue

I have a stocking card with a filter for sticks and saplings for a furnace side. if there's half a stack of 1 item and the filter has multiple items set, it will try to fill the half stack with the other item on the filter, voiding it. I have discovered it has something to do with trying to insert more. if there's a full stack, nothing will happen, but when there is <64 items, it will try to fill the stack, but if there are no more of the current item, it will attempt to pull the other item(s) from the filter, but because it cannot insert(there's still some of other item) it pulls from the inventory anyway and goes nowhere(voids).

### Steps to reproduce

setup a stock upgrade onto a furnace side
insert filter of 2+ items
setup a storage method containing both items
finished.

### Expected behaviour

If there is <full stack, but no more items, don't pull other items.

### Screenshots

![image](https://user-images.githubusercontent.com/28549680/172420717-d9146d77-c11b-434e-8e09-06a294941aff.png)

### Additional information

This was from the latest update at time of posting(1.4)

**Comment by Direwolf20-MC** [comment]
Oh yea, thats a derp on my part :). Trying to be efficient and introduced a bug because I forget to do a final validation.  It'll be resolved in the fluid update shortly.
