### ISSUE TITLE
Feture request: Seperet chanels for stocker/regulate mode.

### ISSUE THREAD

**Issue by NJM1564** [Direwolf20-MC/LaserIO#36]
### Describe the feature you'd like to have added

Feature request: Separate channels for stocker/regulate mode.
With things as they are now if you try to pull from more than one inventory to stock a third you could end up with items passing back and forth from one of the supplier inventories to the other and back. If they had a separate channel for pulling items and pushing items from the stocked inventory that could be fixed.
Use case: I'd trying to keep x items stocked in minecolonies racks. I'm pulling from RS interfaces. Do to limited size of interfaces slots I need 2 interfaces and they pull items back and forth.
(I know I can set up filters but that will get very tedious very quickly.)

**Comment by Direwolf20-MC** [comment]
You should be able to accomplish this with 2 sets of cards on different channels, no?
