### ISSUE TITLE
Server Side Error

### ISSUE THREAD

**Issue by FreePyro001** [Direwolf20-MC/LaserIO#39]
### LaserIO version

1.1.1

### Minecraft Version

1.18.2

### Forge Version

40.1.31

### Modpack & Version

ATM7 0.4.9

### Do you have optifine installed?

No

### Describe the issue

Server starting up and I get a FLUIDFLOWPARTICLE runtime exception. 

### Steps to reproduce

Download the ATM7 Server files and install.
Update laserio to the latest version of 1.1.1 and start up the server. 
The server does not start due to a java runtime exception with fluid flow particle

### Expected behaviour

The server to start and not crash

### Log files

[latest.log](https://github.com/Direwolf20-MC/LaserIO/files/8879686/latest.log)

**Comment by Direwolf20-MC** [comment]
Did you mean to close this ? If so what was the resolution ?

**Comment by FreePyro001** [comment]
Yes I did. First restarted computer for the 3rd time, somehow the old version of the mod got back in the folder even after I deleted it so that was causing the crash. When I first started it wasn't in there so I am not sure why or how that happened. So I deleted old version again and it worked fine.
