### ISSUE TITLE
Suggestion: Learning item filter

### ISSUE THREAD

**Issue by Shaikhain** [Direwolf20-MC/LaserIO#4]
The idea would be to make early to midgame itemsorting less annoying.

It would work like this: you shift+rightclick the filter on a chest or another inventory. 
The card remembers it and every time a new item gets put into the chest that item will be added to an allow-list. That means after your first few mining trips you manually sort stuff from your inventory into an ore chest for example and the filter remembers these. Next time you come back you just dump all your stuff in clean-my-inventory-chest from which the items can be laser-sorted into your own 'categories'

It might need some limitations but i think that would be a cool feature without invalidating the other cards as they allow the more in depth stuff

**Comment by Direwolf20-MC** [comment]
I considered this as a 'polymorph' filter, but for now don't really have plans to implement it. I'll keep it on the 'maybe' list, but have other priorities right now :). Thanks for the suggestion!
