### ISSUE TITLE
Ability to go back form the Card UI back to the Laser Node UI

### ISSUE THREAD

**Issue by ralmeida** [Direwolf20-MC/LaserIO#44]
### Describe the feature you'd like to have added

When working with the Laser Node you right click a card to view the details.

From here there is no apparent way to get back to the Laser Node UI without going out and back in.

It would be cool if there was a back button on the ui maybe at the bottom left, to allow us to go back to the Node UI.

**Comment by Direwolf20-MC** [comment]
This is available in the latest released version 1.2.0. :)
