### ISSUE TITLE
Feature Suggestion: Gas cards and tier node upgrades

### ISSUE THREAD

**Issue by FreePyro001** [Direwolf20-MC/LaserIO#45]
### Describe the feature you'd like to have added

It would be a cool to see a gas card implemented that would support gases like from mekanism and other mods. 
Tier node upgrade would allow maybe like a golden node that would have more slots per side instead of 3x3 it would be a 5x5 or something that way you can do a lot more with the nodes if needed.

**Comment by Direwolf20-MC** [comment]
Gases are planned. Larger nodes not needed really. :)
