### ISSUE TITLE
Crafting Add-on "filter" cards

### ISSUE THREAD

**Issue by alecium** [Direwolf20-MC/LaserIO#47]
### Describe the feature you'd like to have added

The idea would be a card that is similar to a filter card that you can add into a Item Card that is set on stocking or Insert mode.  It could be assigned a recipe, and then it would search the LaserIO channel network for the required materials to craft that recipe, craft the item, and deposit it into the attached inventory that the Item Card is instructed to insert to.

For example, if you set a item card to insert Oak Planks into a chest, and added a Crafting Filter Card to the Item Card, then LaserIO would search all the attached chests/inventories on the channel network for Oak Logs and Stripped Oak Logs and craft them into Oak Planks.  The oak planks would then be inserted into the attached chest until it is full or until the Stocking amount requirement is fulfilled.

Sort of a simple form of autocrafting a single type of item.  AE2 had a similar ability to autocraft a infinite amount of a single type of item.

### Additional information

If you like the idea and want to ask me any questions, feel free to DM me via Discord (I am a member of the Direcord20 discord group).

**Comment by Direwolf20-MC** [comment]
I don’t really want to get into crafting with this mod. Sorry :)
