### ISSUE TITLE
Chute from Create can take the cards out of the Laser Node. 

### ISSUE THREAD

**Issue by michaelingrum** [Direwolf20-MC/LaserIO#48]
### LaserIO version

1.2.0

### Minecraft Version

1.18.2

### Forge Version

40.1.47

### Modpack & Version

Direwolf20 v1.5.0

### Do you have optifine installed?

No

### Describe the issue

When placing am item card in the node on the bottom side it gets removed by a Create chute. 

### Steps to reproduce

1. Place a laser node above a Create Chute
2. Place a card in the bottom side of the node. (It doesn't take them out of other sides)

You can also put a chute above a node, drop a card into the chute, and it will be inserted into the node. 

### Expected behaviour

I expected that the cards can only be removed by players. 

### Additional information

An easy workaround is to just put the node next to the chute instead of on top of it.

**Comment by Direwolf20-MC** [comment]
Nodes are inventories like any other (chests for example) so anything can interact with them. Several people have been confused by this so i might consider changing it - but for now it’s intended.
