### ISSUE TITLE
Suggestion: Customization 

### ISSUE THREAD

**Issue by Shaikhain** [Direwolf20-MC/LaserIO#5]
You can delete this but here are some ideas for some customization approaches:

1. I really like the framing table in storage drawers, i have zero clue how complex something like that is to set up but it would open up so much potential to use the lasers in every building theme.
2. A way to remove the connecting laser visual - maybe right clicking a glass pane or something like that might be cool to allow disabling the visual effect. For maintenance purposes it could still be shown while holding the wrench
3. Is the laser connector just a relay at the moment? It would be cool if they could be used as a simpler laser that just connects to the one side its placed on

**Comment by Direwolf20-MC** [comment]
Thanks for the suggestions! :)

1. If you mean something like facade's these are planned, but low on the priority list. I want to get fluids/energy/redstone working first.
2. I plan to allow you to customize the laser connections between nodes completely per network - so you can have a 'blue' network and a 'red' network. This would include an Alpha control, which you can set to zero if you wish. I might add a 'needs wrench' setting to this kind of setup as well.
3. No plans for this, would be way too complex and unnecessary.
