### ISSUE TITLE
Can't fill things to more than max int (ie. mekanism induction matrix)

### ISSUE THREAD

**Issue by TheGoldenProof** [Direwolf20-MC/LaserIO#50]
### LaserIO version

1.2.0

### Minecraft Version

1.18.2

### Modpack & Version

Direwolf20 1.18

### Do you have optifine installed?

No

### Describe the issue

When inserting power into an induction matrix from mekanism, the matrix capped out at 2.14 GFE even though the capacity was 25.60 GFE

### Steps to reproduce

1. Build Mekanism Induction Matrix with capacity > 2.14 GFE
2. Fill with power via LaserIO
3. Energy will not go above 2.14 GFE

### Expected behaviour

Energy goes above 2.14 GFE

### Screenshots

![image](https://user-images.githubusercontent.com/7574714/174470634-6c5b770a-02cc-49d6-b8f2-0dbb8348f623.png)

### Additional information

(my guess is)
The inserting energy card is calculating the energy limit with ints (100% of 25.60 GFE = 2,147,... GFE).
EDIT:
After looking at the LaserIO code, Forge API, and Mekanism, it seems this isn't as simple of an issue as "don't cast it to an int" because forge IEnergyStorage uses ints, while mekanism uses it's own IEnergyContainer that uses `FloatingLong`s.

**Comment by Direwolf20-MC** [comment]
Will investigate.

**Comment by Direwolf20-MC** [comment]
Despite @KingLemming's rantings this bug is now resolved, thank you for the report :)
