### ISSUE TITLE
Client crashes when entering resonating crystal into the tag filter

### ISSUE THREAD

**Issue by aziel13** [Direwolf20-MC/LaserIO#51]
### LaserIO version

1.0.7

### Minecraft Version

1.18.2

### Forge Version

40.1.47

### Modpack & Version

Direwolf20 - 1.18.2 (1.4.1)

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

Client crashes when entering resonating crystal into the tag filter

### Steps to reproduce

1. type resonating crystal into a tag filter text input box
2. click plus
3. client locks up
4. The words saving world are displayed, reguardless of whether you are in singleplayer or multiplayer
5. the client crashes to desktop.  Servers appear to be unaffected.

### Expected behaviour

add the words resonating crystal to the tag filter.

### Log files

[crash-2022-06-19_13.52.31-client.txt](https://github.com/Direwolf20-MC/LaserIO/files/8936091/crash-2022-06-19_13.52.31-client.txt)

### Additional information

The rendering mod I am using is rubidium, a forge port of sodium.

So that I can use the oculus mod for shaders.

**Comment by aziel13** [comment]
it also crashes if you type deep_resonance:resonating crystal

**Comment by Direwolf20-MC** [comment]
Should work ok if you update. Try on 1.2.0
