### ISSUE TITLE
Small nodes to tidy up laser lines

### ISSUE THREAD

**Issue by Sougent** [Direwolf20-MC/LaserIO#52]
### Describe the feature you'd like to have added

A bit of a silly request, but here it goes.   I don't mind seeing the lasers, but having them untidily shooting willy nilly at all angles could put an eye out.   Yes, one could place additional laser nodes around to tidy things up but that seems like overkill so I would like to request relay nodes or mirrors that could bounce the lasers at right angles but are less expensive and complicated to make.   Say glass and silver plus whatever other ingredients to make a "mirror" or prism to bend the lasers.

**Comment by Direwolf20-MC** [comment]
Thats exactly what the laser connectors are for - are you not seeing those, or are you looking for something else?

**Comment by Sougent** [comment]
> Thats exactly what the laser connectors are for - are you not seeing those, or are you looking for something else?

Ah, it was not obvious to me since they are an ingredient for the node.   And naturally, I didn't rtfm.
