### ISSUE TITLE
RFToolsPower Interaction

### ISSUE THREAD

**Issue by blain8807** [Direwolf20-MC/LaserIO#53]
### LaserIO version

1.2.0

### Minecraft Version

1.18.2

### Forge Version

40.1.47

### Modpack & Version

Direwolf 20 1.18 1.5.1

### Do you have optifine installed?

No

### Describe the issue

Laser IO can insert power into RFToolsPower Blocks but cannot extract power from those same blocks.

### Steps to reproduce

1. Place 1 Dimensional Cell (any level) with no link card
2. Charge Dimensional Cell (DC 1) 
3. Select and set Output side on DC1
4. Place LaserIO Node on output side of DC1
5. Insert an Energy Card set to extract on side facing the output side of DC1
6. Place a second Dimensional Cell (DC2) with no link card
7. Set Input side on DC2 facing the LaserIO Node
8. Insert an Energy Card set to insert on the side facing the input side of DC2

### Expected behaviour

Power should transfer from one cell to the second cell through the Laser IO node.

### Additional information

This appears to happen with both the Dimensional Cells and the Power Cells for pulling energy from a Laser IO node. 
However when inserting energy into a cell from a LaserIO node connect to another system (an MV Accumulator for example) (MV Accumulator > LaserIO Node > Dimensional Cell) into the RFTools Power cells it appears to work correctly.

**Comment by Direwolf20-MC** [comment]
Will investigate.

**Comment by Direwolf20-MC** [comment]
I'm almost certain this is an issue on RFTool's side - i stepped through the code over there, and those cubes are set to disallow extracting- unsure if a bug or something I might be doing wrong- I pinged McJty to ask :)

![image](https://user-images.githubusercontent.com/39863894/174688593-134595f7-ee60-4cbd-9ead-267ce368da8f.png)

**Comment by Direwolf20-MC** [comment]
This should be fixed by https://github.com/Direwolf20-MC/LaserIO/commit/728b3bcf07b3db6b6c477b46eeccb23c57a514e0

I'll release v1.3.1 shortly to include this commit.

Let me know if not :D
