### ISSUE TITLE
Feature Suggestion: Pipez Energy Pipe Integration

### ISSUE THREAD

**Issue by bordey12** [Direwolf20-MC/LaserIO#54]
### Describe the feature you'd like to have added

When trying to construct an energy transfer system it would be very useful to combine the features of Pipez's energy pipes as well as the laser nodes energy transfer system. For example using a laser node to extract from a flux cell and transfer it long distances, which works fine, and then using a Pipez energy pipe to cover shorter distances that would not be worth it to cover using laser nodes.
An example of the type of setup shown below.

<img width="723" alt="Pipez Integration" src="https://user-images.githubusercontent.com/107891274/174681728-b440896f-2afa-4d0d-8274-89f663ad1fa0.png">

As it is there seems to be no interaction between the two blocks whatsoever.
For reference there is an energy card set to insert in the laser node on the left, as well as on the right.

**Comment by Direwolf20-MC** [comment]
I assume pipez, like my nodes, don’t actually store any energy in themselves just transfer it.  This is why it didn’t connect currently. Sorry not planned :).

**Comment by bordey12** [comment]
Very understandable. Thanks for the quick response.
