### ISSUE TITLE
Hopper removes modules from LaserIO Node

### ISSUE THREAD

**Issue by mattnic586** [Direwolf20-MC/LaserIO#56]
### LaserIO version

1.2

### Minecraft Version

1.18.2

### Forge Version

40.1.47

### Modpack & Version

Direwolf20 1.18.2 v1.5.1

### Do you have optifine installed?

No

### Describe the issue

A hopper under a laser node will remove the modules

### Steps to reproduce

place hopper in world
place laser node above hopper
place item module in laser node
wait...
The module will be pulled out of the laser node and put into the hopper.

### Expected behaviour

I expect the modules would not be removed by the hopper.

### Screenshots

none

### Log files

none

### Additional information

I did test this in a multiplayer and single player and received the same results.

**Comment by Direwolf20-MC** [comment]
Currently LaserIO nodes are an inventory like any other - so hoppers and other pipe system can interact with them. On one hand, this adds some cool effects :). On the other, it can cause this.  At this time I don't want to remove it, but its possible I will someday.
