### ISSUE TITLE
Can't extract from FluxNetworks Flux Points

### ISSUE THREAD

**Issue by jinks** [Direwolf20-MC/LaserIO#57]
### LaserIO version

1.2.0

### Minecraft Version

1.18.2

### Forge Version

40.1.31

### Modpack & Version

ATM7 - 0.4.13

### Do you have optifine installed?

No

### Describe the issue

LaserIO won't extract power from Flux Points, also the point doesn't render the small connection anchors it usually does towards consumers. FluxNetworks tends to intelligently try to determine consumers which I guess fails here. It doesn't matter if the Laser Node or the Flux Point are placed first. I did not test inserting into Flux Plugs.

### Steps to reproduce

1. place Laser Node
2. put Energy Card set to extract in one side
3. place Flux Point on that side of the Laser Node
4. see Laser but no connection

Step 1+2 and 3 can be reversed with the same result.
Using a Flux Cell from Thermal as intermediary makes the system work.

### Expected behaviour

FE Connection between both blocks and transfer of energy.

### Screenshots

![2022-06-22_21 42 41](https://user-images.githubusercontent.com/285602/175123489-3c646436-032e-42af-b7ed-bbeb2e05da59.png)
![2022-06-22_21 49 34](https://user-images.githubusercontent.com/285602/175123815-1a497fc5-7a98-4e45-bf1e-86a058706715.png)

**Comment by Direwolf20-MC** [comment]
Similar issue to : #53 

Will need to add support for this kind of thing. I'll add it as an augmentation.

**Comment by Direwolf20-MC** [comment]
This should be fixed by https://github.com/Direwolf20-MC/LaserIO/commit/728b3bcf07b3db6b6c477b46eeccb23c57a514e0

I'll release v1.3.1 shortly to include this commit.

Let me know if not :D
