### ISSUE TITLE
Don`t Render Lasers

### ISSUE THREAD

**Issue by Rumaruka** [Direwolf20-MC/LaserIO#58]
### LaserIO version

1.3.0

### Minecraft Version

1.18.2

### Forge Version

40.1.52

### Modpack & Version

FTB Present Direwolf20 1.18

### Do you have optifine installed?

No

### Describe the issue

Don`t render lasers

### Steps to reproduce

1)Grab wrench
2)Try use
3)See screenshots or watch video
But mod work perfectly

Video: https://youtu.be/CwaDueupGZE

### Expected behaviour

Laser rendered ¯\_(ツ)_/¯

### Screenshots

![Uploading 2022-06-23_22.28.25.png…]()

**Comment by Direwolf20-MC** [comment]
This is a bug with tempads. Find the tempad client confit and set fancy doors to false. Or wait for 1.6.1 of the pack to come out likely tomorrow.
