### ISSUE TITLE
Energy cards don't interact with Mekanism's Umiversal Cables

### ISSUE THREAD

**Issue by Drakkim** [Direwolf20-MC/LaserIO#60]
### LaserIO version

1.3.0

### Minecraft Version

1.18.2

### Forge Version

40.1.52

### Modpack & Version

Direwolf20 1.18

### Do you have optifine installed?

No

### Describe the issue

Laser Nodes with an energy card draw lasers to the Mekanism cables, but don't insert or retreive energy

### Steps to reproduce

1. Connect a Mekanism Universal Cable to some power source
2. Place a Laser Node adjacent to that cable
3. Place Redstone Furnace adjacent to the Node, but not the cable
4. Insert an Energy card on the cable side, on Import
5. Insert an Energy card on the Furnace side, on Export

The yellow lasers are visible to the cable and the furnace, but no power transfers
Replace that Universal Cable with a Redstone Flux Cell and it works as expected

### Expected behaviour

Power should transfer from the Universal Cable to the LaserIO Laser Node

**Comment by Direwolf20-MC** [comment]
This should be fixed by https://github.com/Direwolf20-MC/LaserIO/commit/728b3bcf07b3db6b6c477b46eeccb23c57a514e0

I'll release v1.3.1 shortly to include this commit.

Let me know if not :D
