### ISSUE TITLE
Game crash on Inserting 9 max output export cards on 1 side

### ISSUE THREAD

**Issue by H20Slicer** [Direwolf20-MC/LaserIO#61]
### LaserIO version

1.0.7

### Minecraft Version

1.18.2

### Forge Version

40.1.47

### Modpack & Version

DW20 1.18 V1.4.1

### Do you have optifine installed?

Yes

### Describe the issue

I placed 9 export cards each with 4 overclocking upgrades into a laser node (all on the same side) with only 2 insert cards on a different side and my game crashes every time I log in now. 

### Steps to reproduce

Place 1 AE2 matter condenser with 256k ME storage component set to Singularity, 1 laser node, 1 drawer fill with cobblestone (in my case it was filled with 62 minion cobblestone)

Place 2 node overclockers and 2 item import cards on the matter condenser side, 1 set to white, one set to orange. 

Place 2 node overclockers and 9 export item cards on the storage side, each card is set to 64 blocks at 1 tick using 4 card overclocking upgrades. 8 cards are set to white, 1 set to orange. 

The item cards were inserted by right clicking the card on the preferred node side with the export cards being done last.

### Expected behaviour

Client Side Crash, Repeated Crashing on Login Attempt

### Log files

[crash-2022-06-23_21.56.34-client.txt](https://github.com/Direwolf20-MC/LaserIO/files/8972745/crash-2022-06-23_21.56.34-client.txt)

### Additional information

I'm not running the latest mod pack version as the server I play on is still on 1.4.1

**Comment by Direwolf20-MC** [comment]
Can you try updating to the latest - 1.3,0 - and see if that fixes it?

**Comment by H20Slicer** [comment]
> Can you try updating to the latest - 1.3,0 - and see if that fixes it?

I tried rejoining without optifine and it still crashes. I'm updating to 1.6.0 and will set it up in a test world to see if I can recreate it.

**Comment by Direwolf20-MC** [comment]
Note if you update the direwolf20 pack to 1.6.0 there’s a render bug caused by another mod. Find the tempads client config and disable fancy doors

**Comment by H20Slicer** [comment]
> Note if you update the direwolf20 pack to 1.6.0 there’s a render bug caused by another mod. Find the tempads client config and disable fancy doors

So I recreated the setup (also tested with drawers) in 1.6.1 and I didn't crash. There could of been other factors at play that could of contributed to me crashing. Anyways

![2022-06-24_23 18 18](https://user-images.githubusercontent.com/62770014/175756285-947525a9-f867-4b0e-b8ea-4187023f7f78.png)
 
On an off topic note, is there a way to disable the Infinity Nuke without plugins or mods on DW20 1.18?

**Comment by Direwolf20-MC** [comment]
Thanks, let me know if it happens again :)
