### ISSUE TITLE
AE2 Energy Accepter not taking Energy from nodes

### ISSUE THREAD

**Issue by generilisk** [Direwolf20-MC/LaserIO#62]
### LaserIO version

1.3.0

### Minecraft Version

1.18.2

### Forge Version

40.1.52

### Modpack & Version

Direwolf20 1.18 v1.6.0

### Do you have optifine installed?

No

### Describe the issue

Despite showing a laser, No power is being given to the energy acceptor. 

### Steps to reproduce

Connect AE2 energy acceptor to laser node via energy card
Watch as no energy is transferred.

### Expected behaviour

Energy to be accepted as from other sources/cables.

**Comment by Direwolf20-MC** [comment]
![image](https://user-images.githubusercontent.com/39863894/175798494-cb5ef30b-9cac-4393-b52c-457a330f5660.png)

Tested in my dev world, and it seems to be working. This will be v1.3.1 -- I didn't make any changes that should have fixed this though...

Check again that you have a place for the energy to go?
