### ISSUE TITLE
Does not pull energy directly from a Tesseract

### ISSUE THREAD

**Issue by Sougent** [Direwolf20-MC/LaserIO#63]
### LaserIO version

1.3.0

### Minecraft Version

1.18

### Forge Version

40.1.52

### Modpack & Version

Direwolf20 1.18 v1.6.1

### Do you have optifine installed?

No

### Describe the issue

I am unable to use LaserIO to pull energy directly from a Tesseract set to an energy channel.

### Steps to reproduce

Place a Tesseract and set it to an energy channel, place a LaserIO node next to it and configure an energy card to extract energy from the direction that the Tesseract is placed.    Several blocks away place a Redstone Flux Cell or machine that has no energy, Place a LaserIO node next to it and configure an energy card to insert into the flux cell or machine.      

For me, nothing happens, no energy is transferred.    If I move the Tesseract and place it one block away from the LaserIO node, placing a Redstone Flux Cell between the Tesseract and the node as a buffer, the flux cell is charged from the Tesseract and the LaserIO node pulls power from it successfully with no change to configuration, it just doesn't want to pull from the Tesseract directly.    

I have not attempted to use LaserIO to pull items or fluids from the Tesseract, I do not know if that works or not.

### Expected behaviour

Expect the node to pull energy directly from the Tesseract with no buffer, ideally one would be able to configure a single node to pull energy, items and fluids from the same tesseract.

**Comment by Sougent** [comment]
FYI, tested pulling items from the Tesseract which does appear to work.   One possible issue, before I had started the builder to do the mining I activated the mining channel and apparently the node sucked the quarry card out of the builder through the tesseract, never had that happen with anything else.

**Comment by Direwolf20-MC** [comment]
This should be fixed by https://github.com/Direwolf20-MC/LaserIO/commit/728b3bcf07b3db6b6c477b46eeccb23c57a514e0

Let me know if not :D
