### ISSUE TITLE
Minor Spelling Error in Book

### ISSUE THREAD

**Issue by Lolzorous** [Direwolf20-MC/LaserIO#64]
LaserIO v 1.3.0

Found under the Card category in the Redstone Card chapter:
![image](https://user-images.githubusercontent.com/103785070/175793715-9dc4ea40-ca39-452f-b613-55268bf24b78.png)

"level" is probably suppose to be "lever"

After noticing this I did read the rest of the book, I did not notice anything else, I am also notoriously bad at reading so take this with a grain of salt.

Apologies if this does constitute a bug. A bug report felt a little bit like overkill though. Especially the required steps to recreate section "Step one: open book, step two: read"

**Comment by Direwolf20-MC** [comment]
Fixed in: https://github.com/Direwolf20-MC/LaserIO/commit/ddeea23a934d5928c2e10e0803ea542e2c4b7bc6

Thanks for the heads up :)
