### ISSUE TITLE
Feature Request: Some options and additional feedback

### ISSUE THREAD

**Issue by Remixed-Witch** [Direwolf20-MC/LaserIO#65]
### Describe the feature you'd like to have added

I'm sorry if these should be in separate requests, I've never used Github before today.
Features 
1. When configuring a card, when you are changing the block side you are going to insert/extract from for example, you cycle through the options until you find what you want. However, if you miss it you need to cycle all the way around again, if you could go backwards on right click that would make the experience better. It's weird that this feautre is on the channel slelection but not anything else.
2. It might be nice to be able to access the opposite side from what you are looking at with shift-rightclick.
3. "Wrench-Mod" for the wrench where it will just instantly pick up a node like the similar mode for the Mekanism configurator.

Feedback
I am loving this mod personally, it truly is becoming my favourite pipe system to use now. 
1. Energy Priority, now ive not tested but the idea that I can priorities my ME system to have power before anything else is amazing.
2. The Patchouli book is well layout, everything makes sense and is very clear. However, it does take me out of the professional looking book when I suddenly see a squished aspect ratio image. 
3. I love that I have only opened the book like 3 times, I've managed to fully use 85% of this mod without needing to look at the reference material really shows how well you have re-created the ease of use of the original EnderIO conduits.

**Comment by Direwolf20-MC** [comment]
Added #1 :) its a common request.  https://github.com/Direwolf20-MC/LaserIO/commit/9f9c0da8cc746995e14151d195130df0a7004a49

#2 and #3 i'm going to pass on for now. 

Thank you for the kind words and feedback :)
