### ISSUE TITLE
Bug: Can only increase the priority of energy cards by 100s or 1000s

### ISSUE THREAD

**Issue by Remixed-Witch** [Direwolf20-MC/LaserIO#66]
### LaserIO version

1.3.0

### Minecraft Version

1.18.2

### Forge Version

40.1.52

### Modpack & Version

Direwolf20 - 1.18.2 ver 1.6.1

### Do you have optifine installed?

Yes

### Describe the issue

Can only increase the priority of energy cards by 100s or 1000s

### Steps to reproduce

Place energy card in node.
Try to increase priority holding nothing, which should +1
Only can +100.
Same happens on decrease.

### Expected behaviour

When editing the priority, it should +/- 1 when you are not holding shift or ctrl

**Comment by Direwolf20-MC** [comment]
Resolved in v1.3.1 thank you! :)
