### ISSUE TITLE
Auto-connect nodes when shift-placed on another node

### ISSUE THREAD

**Issue by gman4161** [Direwolf20-MC/LaserIO#69]
### Describe the feature you'd like to have added

Whenever you shift-click another node with a node, it should place the node and auto-connect it to the existing node. I've personally had the same derps as the lets play where nodes weren't connected and I thought I was going crazy.

### Additional information

Absolutely loving the mod. I use it for almost all my item/fluid/energy transfer needs and it's been working great. Keep up the good work!

**Comment by Direwolf20-MC** [comment]
Good suggestion but its not really how I want it to work :) sorry!
