### ISSUE TITLE
Suggestion: General Suggestions

### ISSUE THREAD

**Issue by Script20** [Direwolf20-MC/LaserIO#7]
So I have been playing with the mod in the DW20 pack and loving it, I am having use cases for a sorting system I wish was a thing.

Insert anything matching chest contents.
Mod filter so you put a mods block/item in the filter and it gets the mod id.
Advanced Item filter for more item spaces, basic has 15 maybe 30 would be good.

QoL features: 
An option to make the lasers disappear, or only visible when moving items, or only when holding Laser Wrench

**Comment by Direwolf20-MC** [comment]
Most of these are planned features, but I have higher priorities right now :)
