### ISSUE TITLE
Feature Request: A "Gas" Card for Mekanism Gases

### ISSUE THREAD

**Issue by Kyaenos** [Direwolf20-MC/LaserIO#71]
### Describe the feature you'd like to have added

I would pretty much like as the title describes. To my current knowledge I don't think any of the cards can handle that and I think it would just be super helpful for interactions with Mekanism. I figure it would work pretty much the same as any of the other cards just with gases. 

I super love using this mod and would love to be able to fully use it to get things around.

**Comment by Direwolf20-MC** [comment]
Planned eventually :)
