### ISSUE TITLE
Mekanism cardboard box not filtered

### ISSUE THREAD

**Issue by jollycar** [Direwolf20-MC/LaserIO#72]
### LaserIO version

1.3.0

### Minecraft Version

1.18.2

### Forge Version

40.1.52

### Modpack & Version

Plexiglass Mountain

### Do you have optifine installed?

No

### Describe the issue

Mekanism cardboard box with block data can't be filtered

### Steps to reproduce

Assume you have a working sorting system with 1 input chest (like in your letsplay series)

Add item card to a laser node
add basic filter
add carboard box as filter (NBT disabled by default)
put a cardboard box with block data in the input chest
result: cardboard box doesnt get filtered

### Expected behaviour

Cardboard box should be pulled into the inventory with the item filter

### Additional information

love your mod, simply great!

**Comment by jollycar** [comment]
I feel so stupid. It was not a problem with LaserIO, I had a problem in my setup (backlogged items). Sorry to have been wasting your time.

**Comment by Direwolf20-MC** [comment]
No worries :)
