### ISSUE TITLE
don't place blocks from offhand while using wrench

### ISSUE THREAD

**Issue by jollycar** [Direwolf20-MC/LaserIO#73]
### LaserIO version

1.3.0

### Minecraft Version

1.18.2

### Forge Version

40.1.52

### Modpack & Version

Plexiglass Mountain

### Do you have optifine installed?

No

### Describe the issue

When using the wrench to connect nodes AND you have blocks or items in your offhand, the blocks get placed AND the wrench is interacting with the node

### Steps to reproduce

place node
put cobble in offhand
use wrench on node (either normal rightclick or shift+ rightclick)

result: cobble is placed in the world

### Expected behaviour

i expect the wrench to only interact with the node and not to place blocks from offhand

### Additional information

I think this is a real bug

**Comment by Direwolf20-MC** [comment]
Resolved by: https://github.com/Direwolf20-MC/LaserIO/commit/e5a9e07c3e17201b3b7bdb773c05f8bd18c09c44
