### ISSUE TITLE
Particle display from Digital Miner to Node is on wrong side

### ISSUE THREAD

**Issue by Sougent** [Direwolf20-MC/LaserIO#74]
### LaserIO version

1.3.0

### Minecraft Version

1.18

### Forge Version

40.1.52

### Modpack & Version

Direwolf20 1.18 v1.6.1

### Do you have optifine installed?

No

### Describe the issue

Node extracting from Digital Miner showing particles from wrong side

### Steps to reproduce

Use a node with item extract card to pull items from active Mekanism Digital Miner, the particle effect showing node activity is displaying as coming from the opposite direction from where it should be (see screenshots) .   Node functions correctly, just a visual bug.    Also laser is pointing at an angle downward rather than directly at the port on the miner that it's opposite from.

### Expected behaviour

Expected the particles to be riding the laser in from the other side.

### Screenshots

![2022-07-02_11 43 48](https://user-images.githubusercontent.com/4349792/177009384-710dc940-9c01-472f-8c18-4883d9483102.png)
![2022-07-02_11 43 50](https://user-images.githubusercontent.com/4349792/177009385-526e7e0a-b038-458b-849f-5efb76f14d69.png)
![2022-07-02_11 43 53](https://user-images.githubusercontent.com/4349792/177009388-57e54dfd-4fa4-42d2-81cd-26580288ccfe.png)
![2022-07-02_11 43 57](https://user-images.githubusercontent.com/4349792/177009389-8ceb1d16-fada-4376-a3ee-79a740732df9.png)

**Comment by Direwolf20-MC** [comment]
Resolved by: https://github.com/Direwolf20-MC/LaserIO/commit/3787a23074e4bc053c1c8a785ae4488091a6ec28
