### ISSUE TITLE
Ability to increase range

### ISSUE THREAD

**Issue by Sougent** [Direwolf20-MC/LaserIO#75]
### Describe the feature you'd like to have added

An upgrade card or higher tier (more expensive to craft) item to increase the range of the lasers from node to node, node to connector and connector to connector.    Netherite ingots rather than iron in the recipes to increase the range to 16.    Some other absurdly expensive to get material to increase to 32 blocks (though I'd be happy with just 16).      Higher tiers could be restricted to require a clear line of sight for the lasers, no intervening blocks other than glass or other clear blocks.

**Comment by Direwolf20-MC** [comment]
I have plans for an infinite range 'tesseract' style connector. It'll be infinite range - just not ready to work on it just yet :)
