### ISSUE TITLE
Waterloggable nodes and connectors

### ISSUE THREAD

**Issue by albertquiroga** [Direwolf20-MC/LaserIO#79]
### Describe the feature you'd like to have added

Right now placing laser nodes and connectors underwater looks pretty bad since they cannot be waterlogged

Picture of a LaserIO node vs a Pipez item pipe for comparison (the pipe looks much better since it can be waterlogged):

![image](https://user-images.githubusercontent.com/5863660/177202967-08e3fe8e-5265-4003-9903-c3269fe92c76.png)

**Comment by Direwolf20-MC** [comment]
Added to wishlist.
