### ISSUE TITLE
Tag filter not finding all tags

### ISSUE THREAD

**Issue by KindarConrath** [Direwolf20-MC/LaserIO#81]
### LaserIO version

1.3.1

### Minecraft Version

1.18.2

### Modpack & Version

Direwolf20 1.18

### Do you have optifine installed?

No

### Describe the issue

The Tag filter finds some tags, but not all kinds of tags

### Steps to reproduce

Press F3+H to see tags
Regular Item (e.g. String Has White tags, and greyed out tags)

open the tag filter
place string in
Only white tags are found

Enchanted book has tag, but only a greyed out one, minecraft:enchanted_book
open tag filter
place enchanted book in
no tags found.

### Expected behaviour

I would expect all tags to show up

**Comment by Direwolf20-MC** [comment]
I think its item vs block tags - and I'm only looking up item tags.  I'll consider adding the block tag support, but not sure,
