### ISSUE TITLE
Sensor augment for redstone card

### ISSUE THREAD

**Issue by Overseer9** [Direwolf20-MC/LaserIO#82]
### Describe the feature you'd like to have added

An augment for redstone card that change the behaviour of the card. Instead of reading redstone signals, it reads contents inside of tanks or chests and emits redstone signal in the same channel when condition(s) are met

### Additional information

A same feature from refined storage's detectors but with LaserIO

**Comment by Direwolf20-MC** [comment]
Planned feature: will be added to all other card types (Item/fluid/Energy) as a new mode.
