### ISSUE TITLE
Suggestion: Sticky mode for filters

### ISSUE THREAD

**Issue by jinks** [Direwolf20-MC/LaserIO#83]
### Describe the feature you'd like to have added

EnderIO allowed filters to be set to "Sticky Mode", this would ensure, that the items set in that filter could **only** go to that specific connection, no other. This immensely simplifies some sorting system since you didn't have to blacklist the item on every other connection.

I'd love to see that feature find its way into LaserIO.

### Additional information

It's been a while so I can't remember what would happen if you set two connections to sticky the same item. Probably bad things. :)

**Comment by Direwolf20-MC** [comment]
The way laserIO works, this would be tricky (ish) to implement. It would mean visiting all the nodes, checking for sticky, and then revisiting them all if not sticky mode. For performance reasons, i'd rather not :). But I'll consider it if i can find a less performance impacting way to do it.
