### ISSUE TITLE
Mekanism Support 

### ISSUE THREAD

**Issue by GalaxyOfZero** [Direwolf20-MC/LaserIO#84]
### Describe the feature you'd like to have added

Gas Support for the Mekanism mod, so your have all on the Note an needs Not a extra Pipe for Gases

**Comment by Direwolf20-MC** [comment]
Planned

**Comment by G33kman** [comment]
I just spent a day and a half trying to get 5x ore processing working. This definitely makes sense why it isn't working... Lol
Thanks for an awesome mod though @Direwolf20-MC !
Also, thanks for all your YT content. My son and I watch all the time. It's one of the things that I can actually still connect with him on (teenagers...) so, I just wanted to thanks for all the work you put into these things. :)
