### ISSUE TITLE
Weird interaction with compact machine tunnel

### ISSUE THREAD

**Issue by gman4161** [Direwolf20-MC/LaserIO#85]
### LaserIO version

1.3.1

### Minecraft Version

1.18.2

### Forge Version

40.1.54

### Modpack & Version

Direwolf 20 1.18.2

### Do you have optifine installed?

No

### Describe the issue

Laser doesn't draw to compact machine tunnel, but node still attempts to transfer items(it doesn't)

### Steps to reproduce

1. get compact machine
2. setup tunnel
3. setup insert card facing tunnel
4. setup inventory corresponding to proper tunnel side
5. attempt to transfer items

### Expected behaviour

properly transfer items to external inventory

### Screenshots

![image](https://user-images.githubusercontent.com/28549680/178223909-29c16bf8-9525-4ccc-b2a7-f344c20a2433.png)

### Additional information

The laser doesn't draw to the tunnel yet it still "transfers" items. I say this with quotes because they are actually voided. Both the internal and external of the CM were force loaded. The particles still draw as if the laser were supposed to be there, but the items are voided nonetheless

**Comment by gman4161** [comment]
After further testing, Laserio isn't voiding, I misunderstood how tunnels worked exactly(i thought it would push to external inventory. You have to force extract from the other side). 

It still doesn't draw lasers on either the interior or exterior of the tunnel. Exterior doesn't even show transferring particles.
![image](https://user-images.githubusercontent.com/28549680/178226325-f270a43a-6847-4bf8-8a38-0c4397ba484d.png)

**Comment by Direwolf20-MC** [comment]
This might just be a visual issue that won't be easy to resolve :).
