### ISSUE TITLE
Ability to automatically link placed nodes if wrench is in offhand

### ISSUE THREAD

**Issue by SamusAranon** [Direwolf20-MC/LaserIO#86]
### Describe the feature you'd like to have added

If possible, something similar to the way that you can hold the locking card in your offhand while placing storage drawers and have them be placed already locked. If you place your laser wrench in the offhand and select a node, all new nodes placed within range will automatically be connected to that node.

Hold wrench in offhand
Shift Right click node with wrench to use as source
Place new node within range of source node
Node is automatically connected to source node

**Comment by Direwolf20-MC** [comment]
I'll add it to the 'nice to have' list :). Not a priority though, because of the range checking i'd have to do when placing the nodes - which would likely mean doing a forge event.
