### ISSUE TITLE
Seperate Laser IO networks

### ISSUE THREAD

**Issue by grignardopii** [Direwolf20-MC/LaserIO#90]
### Describe the feature you'd like to have added

It would be nice to be able to create separate networks with configurable node to node laser colors. The color of the nodes central cube should also reflect this color.  

The laser connector should be able to act as a passthrough for multiple networks with out connecting the individual network data.

**Comment by Direwolf20-MC** [comment]
You can currently have 15 different channels within a single network, which seems like it would fit your needs? I do plan to let you change the color of the lasers between nodes though it won't affect the color of the nodes themselves.
