### ISSUE TITLE
Redstone Card not taking input from redstone Wire

### ISSUE THREAD

**Issue by Tiefseetauchner** [Direwolf20-MC/LaserIO#91]
### LaserIO version

1.3.1

### Minecraft Version

1.18.2

### Forge Version

40.1.54

### Modpack & Version

FTB Presents Direwolf20 1.18 1.7.0

### Do you have optifine installed?

No

### Describe the issue

The redstone Card connects visually on both the redstone and the node end, but does not convey a signal

### Steps to reproduce

1. Open world
2. Place a Node (I cannot detect any method to this madness)
3. Place a Redstone wire
5. Insert a Redstone card into of the node. The Laser will be drawn and the Wire visually connect
6. Activate the redstone wire (Workaround, use super circuit maker, which works, as well as levers)

(edit I accidentially submitted before testing the north aspect, happens on every side)

### Expected behaviour

The Laser turns bright and other lasers on the same channel activate and output the redstone signal 

### Screenshots

(Accidentially submitted early, edit to include screenshots)

![image](https://user-images.githubusercontent.com/48085877/179273052-bfaf36ef-1249-4057-aebb-9d1d1a8133e5.png)

**Comment by Direwolf20-MC** [comment]
Resolved by: https://github.com/Direwolf20-MC/LaserIO/commit/6ddb5dd72b407ad1661cd412fd13b40f9e1b68bd
