### ISSUE TITLE
FTB Industrial Contraptions

### ISSUE THREAD

**Issue by bookerthegeek** [Direwolf20-MC/LaserIO#92]
### Describe the feature you'd like to have added

Ability to transfer FTB Industrial Contraptions energy through LaserIO

### Additional information

I could see having either different tiers for their energy tiers or use their transformer upgrade in your card to handle the higher energy tiers.

**Comment by Direwolf20-MC** [comment]
Nah I think they want their energy separate. Plus I don’t want to :). Too specific
