### ISSUE TITLE
Basic Filter in Fluid Card should accept Water (fluid) from JEI via drag and drop

### ISSUE THREAD

**Issue by TimWerdin** [Direwolf20-MC/LaserIO#94]
### LaserIO version

1.3.1

### Minecraft Version

1.18.2

### Forge Version

40.1.54

### Do you have optifine installed?

No

### Describe the issue

Basic Filter in Fluid Card does not accept Water from JEI

### Steps to reproduce

1. Open Fluid Card
2. Place Basic Filter in it
3. Try to drap and drop Water from JEI into one of the filter slots (this works e.g. in a Fluid Interface from Refined Storage)

### Expected behaviour

Being able to drag and drop water (fluid) into the filter slot

### Additional information

I know that I can use a Water Bucket or any other storage item to filter for a specific liquid but it feels counter intuitive for me as I'm used to be able to drag and drop the fluid in Refined Storage. 
Also with fluids from some mods there might not be a bucket version of that liquid as it might not be intended to store the liquid in an item in that case it would be impossible to add the fluid filter on the Fluid Card

**Comment by Direwolf20-MC** [comment]
Added by: https://github.com/Direwolf20-MC/LaserIO/commit/4d277c9014d4f8b00e8c8f6a12d1101362d45910
