### ISSUE TITLE
Differentiating redstone channels & card channels

### ISSUE THREAD

**Issue by Vapaman** [Direwolf20-MC/LaserIO#97]
### Describe the feature you'd like to have added

Add text to indicate the type of channel. For examble: "Redstone channel: 2" & "Card channel: 2"
![kuva](https://user-images.githubusercontent.com/77460466/179440456-f275de2e-4e18-4de5-bfe4-d379f110d03e.png)
![kuva](https://user-images.githubusercontent.com/77460466/179440480-b48053ec-678d-4c45-a823-73c53f77b91a.png)

### Additional information

Right now redstone channels and card channel are very easily mixed up. Adding this small change would make thing a lot more clearer to the player.

**Comment by Mistborn-First-Era** [comment]
Agreed, I thought it was bugged. Just a simple little bit of text could fix it.

**Comment by Direwolf20-MC** [comment]
Resolved by: https://github.com/Direwolf20-MC/LaserIO/commit/ea2c842b9a737d69ce3571ff67ee381167fccd0f
