### ISSUE TITLE
Description on Curseforge project page is incorrect

### ISSUE THREAD

**Issue by James103** [Direwolf20-MC/LaserIO#99]
### LaserIO version

1.3.3

### Minecraft Version

1.18.2

### Forge Version

40.1.x

### Modpack & Version

None (bug is in metadata)

### Do you have optifine installed?

No

### Describe the issue

The description on the Curseforge page for this mod is outdated.

### Steps to reproduce

In a browser, open https://www.curseforge.com/minecraft/mc-mods/laserio

The description could use the following improvements.
* "LaserIO seeks to replicate the mechanics of EnderIO - allowing you to interacted with items, fluids, and energy -- all from the same block face!"
  Replace "interacted" with "interact"
* "Currently only Items are supported - but fluids, energy, and even redstone are planned additions for the near future."
  Replace with: "Items, fluids, energy, and even redstone are supported, with more to come."

### Expected behaviour

The description on the Curseforge page for this mod should be up-to-date.

**Comment by Direwolf20-MC** [comment]
Resolved thank you :)
